AdfUIComponents.createComponentClass("AdfUIDecorateCollection",{componentType:"org.apache.myfaces.trinidad.DecorateCollection",namingContainer:!0});
function AdfPanelCollectionDialogFetchEvent(a,b){this.Init(a,b)}AdfObject.createSubclass(AdfPanelCollectionDialogFetchEvent,AdfComponentEvent);AdfPanelCollectionDialogFetchEvent.DIALOG_FETCH_EVENT_TYPE="panelCollectionDialogFetch";AdfPanelCollectionDialogFetchEvent.prototype.Init=function(a,b){AdfPanelCollectionDialogFetchEvent.superclass.Init.call(this,a,AdfPanelCollectionDialogFetchEvent.DIALOG_FETCH_EVENT_TYPE);this._dlgType=b;this.setPartial(!0);this.setRoot(a)};
AdfPanelCollectionDialogFetchEvent.prototype.AddMarshalledProperties=function(a){AdfPanelCollectionDialogFetchEvent.superclass.AddMarshalledProperties.call(this,a);a.dialogType=this._dlgType};AdfPanelCollectionDialogFetchEvent.prototype.propagatesToServer=function(){return!0};AdfPanelCollectionDialogFetchEvent.prototype.isValidationNeeded=function(){return!0};
AdfUIComponents.createComponentClass("AdfRichPanelCollection",{componentType:"oracle.adf.RichPanelCollection",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0}],namingContainer:!0,superclass:AdfUIDecorateCollection});
AdfRichPanelCollection.prototype.isEventRoot=function(){return!0};
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlPanelCollectionPeer",!1);
AdfDhtmlPanelCollectionPeer.InitSubclass=function(){this._AUTO_HEIGHT_TOP_ID="_ahTp";this._AUTO_HEIGHT_BOTTOM_ID="_ahBt";this._AUTO_HEIGHT_CENTER_ID="_ahCt";this._AGGREGATED_CHILD_ID="_afrAC";this._HIDDEN_COL_COUNT="_afrHCC";this._COLUMN_CONTEXT_MENU_ID="_clmCxt";this._TOOLBAR_SPACER_ID="_tbrSpr";this._FREEZE_MENUITEM_ID="_frzMn";this._UNFREEZE_MENUITEM_ID="_ufzMn";this._FREEZE_TOOLBARITEM_ID="_frzTbr";this._DETACH_MENUITEM_ID="_dchMn";this._DETACH_TOOLBARITEM_ID="_dchTbr";this._SORT_ASCENDING_MENUITEM_ID=
"_srtAsc";this._SORT_DESCENDING_MENUITEM_ID="_srtDsc";this._SORT_ADVANCED_MENUITEM_ID="_srtAvd";this._REORDER_MENUITEM_ID="_rdrMn";this._RESIZECOLUMN_MENUITEM_ID="_rszClm";this._QBE_TOOLBARITEM_ID="_qbeTbr";this._QBE_MENUITEM_ID="_qbeMn";this._WRAP_MENUITEM_ID="_wrpMn";this._WRAP_TOOLBARITEM_ID="_wrpTbr";this._VIEW_MENU_ID="_vw";this._COLUMNS_MENU_ID="_clmns";this._COLUMNS_SHOWALL_MENUITEM_ID="_shwAll";this._COLUMNS_SHOWCOLUMN_MENUITEM_ID="_shwClm";this._COLUMNS_SHOWMORE_MENUITEM_ID="_shwMr";this._ROWS_SELECTED_TEXT_ID=
"_rwSctT";this._ROWS_SELECTED_COUNT_ID="_rwSctC";this._COLUMNS_HIDDEN_TEXT_ID="_clmHdnT";this._COLUMNS_HIDDEN_COUNT_ID="_clmHdnC";this._COLUMNS_FROZEN_TEXT_ID="_clmFrzT";this._COLUMNS_FROZEN_COUNT_ID="_clmFrzC";this._EXPAND_MENUITEM_ID="_xpdItm";this._EXPAND_ALL_BELOW_MENUITEM_ID="_xpdBlw";this._COLLAPSE_ALL_BELOW_MENUITEM_ID="_cpsBlw";this._EXPAND_ALL_MENUITEM_ID="_xpdAll";this._COLLAPSE_ALL_MENUITEM_ID="_cpsAll";this._SHOW_AS_TOP_MENUITEM_ID="_shwTp";this._GO_TO_TOP_MENUITEM_ID="_goTp";this._SCROLL_TO_FIRST_MENUITEM_ID=
"_sclFst";this._SCROLL_TO_LAST_MENUITEM_ID="_sclLst";this._SHOW_AS_TOP_TOOLBARITEM_ID="_shwTpTbr";this._GO_UP_TOOLBARITEM_ID="_upTbr";this._GO_TO_TOP_TOOLBARITEM_ID="_tpTbr";this._COL_IDS_WITH_MENUS_KEY="_afrClmWMn";this._DIALOG_TYPE_SORT="_afrSortDialog";this._DIALOG_TYPE_SORT_ID="sortDlg";this._DIALOG_TYPE_SHOW_COLS="_afrShowColsDialog";this._DIALOG_TYPE_REORDER_COLS="_afrReorderDialog";this._DIALOG_TYPE_RESIZE_COL="_afrResizeColDialog";this._SHOWCOLUMNS_DIALOG_SHUTTLE_ID="_shwClmDS";this._POPUP_ID=
"_PCPop";this._SORT_DIALOG_CHOICE_ID="_srtDlgC";this._SORT_DIALOG_RADIO_ID="_srtDlgR";this._MAX_SORT_COLUMNS=3;this._RESIZECOLUMN_DIALOG_SPIN_ID="_rszDSpn";this._RESIZECOLUMN_DIALOG_SELECTONE_ID="_rszDSct1";this._DETACH_DIALOG_CONTAINER_ID="_dchDlgC";this._DETACH_DIALOG_WRAPPER_ID="_dchDlgW";this._DETACH_DIALOG_POPUP_ID="_dchDlgP";this._ALL_TEXT=this._COLUMNS_FROZEN_TEXT=this._COLUMNS_HIDDEN_TEXT=this._ROWS_SELECTED_TEXT=null;AdfRichUIPeer.addComponentEventHandlers(this,AdfActionEvent.ACTION_EVENT_TYPE,
AdfDialogEvent.EVENT_TYPE,AdfPopupClosedEvent.POPUP_CLOSED_EVENT_TYPE,AdfTableShowColumnsEvent.SHOW_COLUMN_EVENT_TYPE,AdfValueChangeEvent.VALUE_CHANGE_TYPE,AdfPopupOpeningEvent.POPUP_OPENING_EVENT_TYPE);var a=this._ACTION_HANDLER_MAP={},b=AdfDhtmlPanelCollectionPeer.prototype;a[this._FREEZE_MENUITEM_ID]=b.freezeColumns;a[this._UNFREEZE_MENUITEM_ID]=b.unfreezeColumns;a[this._FREEZE_TOOLBARITEM_ID]=b.toggleFreeze;a[this._DETACH_MENUITEM_ID]=a[this._DETACH_TOOLBARITEM_ID]=b.detach;a[this._SORT_ASCENDING_MENUITEM_ID]=
b.sortAscending;a[this._SORT_DESCENDING_MENUITEM_ID]=b.sortDescending;a[this._SORT_ADVANCED_MENUITEM_ID]=b.sortAdvanced;a[this._REORDER_MENUITEM_ID]=b.reorderColumns;a[this._QBE_TOOLBARITEM_ID]=b.showQBE;a[this._QBE_MENUITEM_ID]=b.showQBE;a[this._RESIZECOLUMN_MENUITEM_ID]=b.resizeColumn;a[this._WRAP_MENUITEM_ID]=a[this._WRAP_TOOLBARITEM_ID]=b.wrapColumns;a[this._COLUMNS_SHOWALL_MENUITEM_ID]=b.showAllColumns;a[this._COLUMNS_SHOWCOLUMN_MENUITEM_ID]=b.showColumn;a[this._COLUMNS_SHOWMORE_MENUITEM_ID]=
b.showMoreColumns;a[this._EXPAND_MENUITEM_ID]=b.expandNode;a[this._EXPAND_ALL_BELOW_MENUITEM_ID]=b.expandAllNodesBelow;a[this._COLLAPSE_ALL_BELOW_MENUITEM_ID]=b.collapseAllNodesBelow;a[this._EXPAND_ALL_MENUITEM_ID]=b.expandAllNodes;a[this._COLLAPSE_ALL_MENUITEM_ID]=b.collapseAllNodes;a[this._SHOW_AS_TOP_MENUITEM_ID]=b.showNodeAsTop;a[this._GO_TO_TOP_MENUITEM_ID]=b.goToTopNode;a[this._SCROLL_TO_FIRST_MENUITEM_ID]=b.scrollToFirst;a[this._SCROLL_TO_LAST_MENUITEM_ID]=b.scrollToLast;a[this._SHOW_AS_TOP_TOOLBARITEM_ID]=
b.showNodeAsTop;a[this._GO_UP_TOOLBARITEM_ID]=b.goUpNode;a[this._GO_TO_TOP_TOOLBARITEM_ID]=b.goToTopNode};AdfDhtmlPanelCollectionPeer.prototype.Init=function(a,b){AdfDhtmlPanelCollectionPeer.superclass.Init.call(this,a,b);this._aggregatedChild=null;this._hasMultiRowSelection=this._hasColumnSelection=this._isInitialized=this._isTree=this._isStandAloneTree=this._hasColumns=!1};AdfDhtmlPanelCollectionPeer.prototype.toolboxRefreshNotify=function(){this.updateRowSelectionContext();this.updateStandardMenuToolbarItems()};
AdfDhtmlPanelCollectionPeer.prototype._initialize=function(){if(!this._isInitialized){var a=this._aggregatedChild;a||(a=this.getDomElement().getAttribute(AdfDhtmlPanelCollectionPeer._AGGREGATED_CHILD_ID),a=this._aggregatedChild=AdfPage.PAGE.findComponent(a));var b=a instanceof AdfRichTable,d=a instanceof AdfRichTreeTable,e=a instanceof AdfRichTree;this._isStandAloneTree=e;this._hasColumns=b||d;this._isTree=d||e;e||(b=a.getColumnSelection(),null!=b&&(b=b.toLowerCase()),this._hasColumnSelection=null!=
b&&("single"==b||"multiple"==b),a=a.getRowSelection(),null!=a&&(a=a.toLowerCase()),this._hasMultiRowSelection=null!=a&&-1!=a.toLowerCase().indexOf("multiple"));this._isInitialized=!0;a=this.getComponent();a.getProperty("_afrDetached")&&this._detachContent(a)}};AdfDhtmlPanelCollectionPeer.prototype.resetState=function(){var a=this.getDomElement().getAttribute(AdfDhtmlPanelCollectionPeer._AGGREGATED_CHILD_ID);this._aggregatedChild=AdfPage.PAGE.findComponent(a)};
AdfDhtmlPanelCollectionPeer.prototype.updateStandardMenuToolbarItems=function(){this._initialize();if(this._hasColumns){var a=AdfPage.PAGE,b=this._aggregatedChild,d=b.getPeer(),e=this.getComponent().getClientId(),f=d.__getSelectedColumns(),g=0<f.length,h,k;h=a.findComponent(e+":"+AdfDhtmlPanelCollectionPeer._SORT_ASCENDING_MENUITEM_ID);k=a.findComponent(e+":"+AdfDhtmlPanelCollectionPeer._SORT_DESCENDING_MENUITEM_ID);if(h&&k){var l=!1;if(g)for(d=f.length-1;0<=d;--d){var m=f[d];if(m&&m.getSortProperty()&&
m.getSortable()){l=!0;break}}else for(var n=d.__getVisibleLeafColumns(),d=n.length-1;0<=d;--d)if((m=n[d])&&m.getSortProperty()&&m.getSortable()){l=!0;break}l?(h.getParent().setProperty("disabled",!1,!1,AdfUIComponent.PROPAGATE_LOCALLY),this._updateSortMenuItems(b,f,h,k)):h.getParent().setProperty("disabled",!0,!1,AdfUIComponent.PROPAGATE_LOCALLY)}if(this._hasColumnSelection){h=a.getLookAndFeel();k=g?this._isNodeStampColumnSelected(b,f):!1;var l=this._isFreezeDisabled(f),p,b=a.findComponent(e+":"+
AdfDhtmlPanelCollectionPeer._RESIZECOLUMN_MENUITEM_ID);(m=a.findComponent(e+":"+AdfDhtmlPanelCollectionPeer._FREEZE_MENUITEM_ID))&&(p=a.findComponent(e+":"+AdfDhtmlPanelCollectionPeer._UNFREEZE_MENUITEM_ID));d=a.findComponent(e+":"+AdfDhtmlPanelCollectionPeer._FREEZE_TOOLBARITEM_ID);if(m){var q=this._hasFrozenColumn();m.setProperty("disabled",l,!1,AdfUIComponent.PROPAGATE_LOCALLY);m.setProperty("visible",!q,!1,AdfUIComponent.PROPAGATE_LOCALLY);p.setProperty("visible",q,!1,AdfUIComponent.PROPAGATE_LOCALLY)}d&&
(d.setProperty("selected",q,!1,AdfUIComponent.PROPAGATE_LOCALLY),p=q?h.getTranslatedString("af_panelCollection.TIP_BUTTON_UNFREEZE"):h.getTranslatedString("af_panelCollection.TIP_BUTTON_FREEZE"),d.setProperty("shortDesc",p,!1,AdfUIComponent.PROPAGATE_LOCALLY),d.getSelected()||d.setProperty("disabled",l,!1,AdfUIComponent.PROPAGATE_LOCALLY));p=a.findComponent(e+":"+AdfDhtmlPanelCollectionPeer._WRAP_MENUITEM_ID);a=a.findComponent(e+":"+AdfDhtmlPanelCollectionPeer._WRAP_TOOLBARITEM_ID);e=!g||k;f=!e&&
!f[0].getNoWrap();p&&(p.setProperty("disabled",e,!1,AdfUIComponent.PROPAGATE_LOCALLY),p.setProperty("selected",f,!1,AdfUIComponent.PROPAGATE_LOCALLY));a&&(a.setProperty("disabled",e,!1,AdfUIComponent.PROPAGATE_LOCALLY),a.setProperty("selected",f,!1,AdfUIComponent.PROPAGATE_LOCALLY),f=f?h.getTranslatedString("af_panelCollection.TIP_BUTTON_UNWRAP"):h.getTranslatedString("af_panelCollection.TIP_BUTTON_WRAP"),a.setProperty("shortDesc",f,!1,AdfUIComponent.PROPAGATE_LOCALLY));b&&b.setProperty("disabled",
!g,!1,AdfUIComponent.PROPAGATE_LOCALLY)}}};
AdfDhtmlPanelCollectionPeer.prototype._isFreezeDisabled=function(a){var b=this._aggregatedChild,d=b.getPeer(),e=a.length;if(!(0<e))return!0;var f=d.__getVisibleLeafColumns();if(2>f.length)return!0;if(1==e)if("end"==b.getFreezeDirection()){if(a[0]==f[0])return!0}else if(a[0]==f[f.length-1])return!0;a=a[e-1];b=this._getRootColumn(a,d);return null!=b&&(d=a.getPeer().getDomElement(),a=b.getPeer().getDomElement(),b=AdfAgent.AGENT,b.getIntAttribute(a,"_d_index",-1)+parseInt(a.colSpan)-1!=b.getIntAttribute(d,
"_d_index",-1))?!0:!1};AdfDhtmlPanelCollectionPeer.prototype._getRootColumn=function(a,b){for(var d=null,e=b.__getParentColumn(a);null!=e;)d=e,e=b.__getParentColumn(e);return d};AdfDhtmlPanelCollectionPeer.prototype._hasFrozenColumn=function(){return null!=this._getFrozenColumn(this._aggregatedChild)};
AdfDhtmlPanelCollectionPeer.prototype._getFrozenColumn=function(a){a=a.getPeer();for(var b=a.__getVisibleLeafColumns(),d=b.length,e=0;e<d;e++){var f=b[e];if(f){if(f&&f.getFrozen())return f;f=this._getRootColumn(f,a);if(null!=f){if(f.getFrozen())return f;f=f.getPeer().getDomElement();e+=parseInt(f.colSpan)-1}}}return null};
AdfDhtmlPanelCollectionPeer.prototype._isNodeStampColumnSelected=function(a,b){if(!this._isTree)return!1;for(var d=a.getPeer().getNodeStampColumn(),e=0;e<b.length;e++)if(b[e]==d)return!0;return!1};
AdfDhtmlPanelCollectionPeer.prototype._updateSortMenuItems=function(a,b,d,e){if(1==b.length&&(a=b[0],a.getSortProperty()&&a.getSortable())){d.setProperty("disabled",!1,!1,AdfUIComponent.PROPAGATE_LOCALLY);e.setProperty("disabled",!1,!1,AdfUIComponent.PROPAGATE_LOCALLY);a=AdfDhtmlTableBasePeer.__getSortOrderForColumn(a.getClientId());1==a?(d.setProperty("selected",!0,!1,AdfUIComponent.PROPAGATE_LOCALLY),e.setProperty("selected",!1,!1,AdfUIComponent.PROPAGATE_LOCALLY)):0==a?(e.setProperty("selected",
!0,!1,AdfUIComponent.PROPAGATE_LOCALLY),d.setProperty("selected",!1,!1,AdfUIComponent.PROPAGATE_LOCALLY)):(d.setProperty("selected",!1,!1,AdfUIComponent.PROPAGATE_LOCALLY),e.setProperty("selected",!1,!1,AdfUIComponent.PROPAGATE_LOCALLY));return}d.setProperty("selected",!1,!1,AdfUIComponent.PROPAGATE_LOCALLY);d.setProperty("disabled",!0,!1,AdfUIComponent.PROPAGATE_LOCALLY);e.setProperty("selected",!1,!1,AdfUIComponent.PROPAGATE_LOCALLY);e.setProperty("disabled",!0,!1,AdfUIComponent.PROPAGATE_LOCALLY)};
AdfDhtmlPanelCollectionPeer.prototype.updateStandardStatusbarItems=function(){this._initialize();if(!this._isStandAloneTree){for(var a=this._aggregatedChild.getPeer(),b=a.__getVisibleLeafColumns(),d=0,e=0,e=b.length-1;0<=e;e--){var f=b[e];if(f)if(f.getFrozen())d++;else if(0<d&&!f.getRowHeader())d++;else if(f=this._getRootColumn(f,a),null!=f){var g=f.getPeer().getDomElement(),g=parseInt(g.colSpan),e=e-(g-1);f.getFrozen()&&(d+=g)}}a._freezeColumnsToEnd()&&(d=a.__getVisibleLeafColumns().length-d+1);
e=a.getDomElement().getAttribute(AdfDhtmlPanelCollectionPeer._HIDDEN_COL_COUNT);a=this.getComponent().getClientId();b=AdfPage.PAGE;this._hasColumns&&(f=b.findComponent(a+":"+AdfDhtmlPanelCollectionPeer._COLUMNS_FROZEN_TEXT_ID),g=b.findComponent(a+":"+AdfDhtmlPanelCollectionPeer._COLUMNS_FROZEN_COUNT_ID),f&&(AdfDhtmlPanelCollectionPeer._COLUMNS_FROZEN_TEXT||(AdfDhtmlPanelCollectionPeer._COLUMNS_FROZEN_TEXT=f.getValue()),f.setProperty("value",0<d?AdfDhtmlPanelCollectionPeer._COLUMNS_FROZEN_TEXT:"",
!1,AdfUIComponent.PROPAGATE_LOCALLY)),g&&(0<d?g.setProperty("value",d.toString(),!1,AdfUIComponent.PROPAGATE_LOCALLY):g.setProperty("value","",!1,AdfUIComponent.PROPAGATE_LOCALLY)));f=b.findComponent(a+":"+AdfDhtmlPanelCollectionPeer._COLUMNS_HIDDEN_TEXT_ID);g=b.findComponent(a+":"+AdfDhtmlPanelCollectionPeer._COLUMNS_HIDDEN_COUNT_ID);f&&(AdfDhtmlPanelCollectionPeer._COLUMNS_HIDDEN_TEXT||(AdfDhtmlPanelCollectionPeer._COLUMNS_HIDDEN_TEXT=f.getValue()),f.setProperty("value",0<e?AdfDhtmlPanelCollectionPeer._COLUMNS_HIDDEN_TEXT:
"",!1,AdfUIComponent.PROPAGATE_LOCALLY));g&&(0<e?g.setProperty("value",e.toString(),!1,AdfUIComponent.PROPAGATE_LOCALLY):g.setProperty("value","",!1,AdfUIComponent.PROPAGATE_LOCALLY))}};
AdfDhtmlPanelCollectionPeer.prototype.updateRowSelectionContext=function(){this._initialize();var a=this._aggregatedChild,b=!1,d=0,e=null,f=a.getSelectedRowKeys(),g;for(g in f){if(g==AdfDhtmlTableBasePeer.SELECTALL_KEY_PROPERTY){b=f[AdfDhtmlTableBasePeer.SELECTALL_KEY_PROPERTY];break}0==d&&(e=g);d++}this._hasMultiRowSelection&&this._updateRowSelectionCount(b,d);this._isTree&&this._updateTreeRowSelectionContext(a,b,d,e)};
AdfDhtmlPanelCollectionPeer.prototype._updateRowSelectionCount=function(a,b){var d=AdfPage.PAGE,e=this.getComponent().getClientId(),f=d.findComponent(e+":"+AdfDhtmlPanelCollectionPeer._ROWS_SELECTED_TEXT_ID),e=d.findComponent(e+":"+AdfDhtmlPanelCollectionPeer._ROWS_SELECTED_COUNT_ID);f&&(AdfDhtmlPanelCollectionPeer._ROWS_SELECTED_TEXT||(AdfDhtmlPanelCollectionPeer._ROWS_SELECTED_TEXT=f.getValue()),f.setProperty("value",a||0<b?AdfDhtmlPanelCollectionPeer._ROWS_SELECTED_TEXT:"",!1,AdfUIComponent.PROPAGATE_LOCALLY));
e&&(a?(AdfDhtmlPanelCollectionPeer._ALL_TEXT||(AdfDhtmlPanelCollectionPeer._ALL_TEXT=d.getLookAndFeel().getTranslatedString("af_panelCollection.LABEL_STATUSBARITEM_ROWS_SELECTED_ALL")),0<b?e.setProperty("value","",!1,AdfUIComponent.PROPAGATE_LOCALLY):e.setProperty("value",AdfDhtmlPanelCollectionPeer._ALL_TEXT,!1,AdfUIComponent.PROPAGATE_LOCALLY)):0<b?e.setProperty("value",b.toString(),!1,AdfUIComponent.PROPAGATE_LOCALLY):e.setProperty("value","",!1,AdfUIComponent.PROPAGATE_LOCALLY))};
AdfDhtmlPanelCollectionPeer.prototype._updateTreeRowSelectionContext=function(a,b,d,e){this._initialize();var f=this.getComponent().getClientId(),g=a.getPeer(),h=AdfPage.PAGE,k=h.findComponent(f+":"+AdfDhtmlPanelCollectionPeer._EXPAND_MENUITEM_ID),l=h.findComponent(f+":"+AdfDhtmlPanelCollectionPeer._EXPAND_ALL_BELOW_MENUITEM_ID),m=h.findComponent(f+":"+AdfDhtmlPanelCollectionPeer._COLLAPSE_ALL_BELOW_MENUITEM_ID),n=h.findComponent(f+":"+AdfDhtmlPanelCollectionPeer._SHOW_AS_TOP_MENUITEM_ID),p=h.findComponent(f+
":"+AdfDhtmlPanelCollectionPeer._GO_TO_TOP_MENUITEM_ID),q=h.findComponent(f+":"+AdfDhtmlPanelCollectionPeer._SCROLL_TO_FIRST_MENUITEM_ID),r=h.findComponent(f+":"+AdfDhtmlPanelCollectionPeer._SCROLL_TO_LAST_MENUITEM_ID),t=h.findComponent(f+":"+AdfDhtmlPanelCollectionPeer._SHOW_AS_TOP_TOOLBARITEM_ID),u=h.findComponent(f+":"+AdfDhtmlPanelCollectionPeer._GO_UP_TOOLBARITEM_ID),v=h.findComponent(f+":"+AdfDhtmlPanelCollectionPeer._GO_TO_TOP_TOOLBARITEM_ID),w=h.findComponent(f+":"+AdfDhtmlPanelCollectionPeer._COLUMN_CONTEXT_MENU_ID+
AdfDhtmlPanelCollectionPeer._SORT_ASCENDING_MENUITEM_ID),f=h.findComponent(f+":"+AdfDhtmlPanelCollectionPeer._COLUMN_CONTEXT_MENU_ID+AdfDhtmlPanelCollectionPeer._SORT_DESCENDING_MENUITEM_ID);e&&!g.FindRowByKey(e)&&(e=null);var y=g.hasPathStamp(),A=h=!1;if(b||null==e||1<d)k&&k.setProperty("disabled",!0,!1,AdfUIComponent.PROPAGATE_LOCALLY),w&&w.setProperty("disabled",!0,!1,AdfUIComponent.PROPAGATE_LOCALLY),f&&f.setProperty("disabled",!0,!1,AdfUIComponent.PROPAGATE_LOCALLY),l&&l.setProperty("disabled",
!0,!1,AdfUIComponent.PROPAGATE_LOCALLY),m&&m.setProperty("disabled",!0,!1,AdfUIComponent.PROPAGATE_LOCALLY),n&&n.setProperty("disabled",!0,!1,AdfUIComponent.PROPAGATE_LOCALLY),t&&t.setProperty("disabled",!0,!1,AdfUIComponent.PROPAGATE_LOCALLY);else{b=e==a.getFocusRowKey();h=g.isLeaf(e);d=g.getDepth(e);var B=g.isMultiRoot(),A=a.isPathExpanded(e);k&&(k.setProperty("disabled",h,!1,AdfUIComponent.PROPAGATE_LOCALLY),k.setProperty("selected",!A,!1,AdfUIComponent.PROPAGATE_LOCALLY));y&&(a=b||h||!B&&0==d,
n&&n.setProperty("disabled",a,!1,AdfUIComponent.PROPAGATE_LOCALLY),t&&t.setProperty("disabled",a,!1,AdfUIComponent.PROPAGATE_LOCALLY));w&&f&&(n=g.getNodeStampColumn())&&n.getSortProperty()&&n.getSortable()&&(w.setProperty("disabled",!1,!1,AdfUIComponent.PROPAGATE_LOCALLY),f.setProperty("disabled",!1,!1,AdfUIComponent.PROPAGATE_LOCALLY),w.setProperty("selected",!1,!1,AdfUIComponent.PROPAGATE_LOCALLY),f.setProperty("selected",!1,!1,AdfUIComponent.PROPAGATE_LOCALLY));l&&l.setProperty("disabled",h,!1,
AdfUIComponent.PROPAGATE_LOCALLY);m&&m.setProperty("disabled",h||!A,!1,AdfUIComponent.PROPAGATE_LOCALLY)}g=!g.isSelectorIconVisible();p&&p.setProperty("disabled",g,!1,AdfUIComponent.PROPAGATE_LOCALLY);v&&(v.setProperty("disabled",g,!1,AdfUIComponent.PROPAGATE_LOCALLY),u.setProperty("disabled",g,!1,AdfUIComponent.PROPAGATE_LOCALLY));r&&r.setProperty("disabled",!1,!1,AdfUIComponent.PROPAGATE_LOCALLY);q&&q.setProperty("disabled",!1,!1,AdfUIComponent.PROPAGATE_LOCALLY)};
AdfDhtmlPanelCollectionPeer.prototype.showColumnContextMenu=function(a,b){this._initialize();if(this._hasColumns){var d=this._aggregatedChild,e=d.getPeer(),f=AdfPage.PAGE,g=this.getComponent().getClientId(),h=f.findComponent(g+":"+AdfDhtmlPanelCollectionPeer._COLUMN_CONTEXT_MENU_ID),k,l,m,n;if(h){var p=this._hasFrozenColumn(),q=e.__getSelectedColumns();k=f.findComponent(g+":"+AdfDhtmlPanelCollectionPeer._COLUMN_CONTEXT_MENU_ID+AdfDhtmlPanelCollectionPeer._SORT_ASCENDING_MENUITEM_ID);l=f.findComponent(g+
":"+AdfDhtmlPanelCollectionPeer._COLUMN_CONTEXT_MENU_ID+AdfDhtmlPanelCollectionPeer._SORT_DESCENDING_MENUITEM_ID);(m=f.findComponent(g+":"+AdfDhtmlPanelCollectionPeer._COLUMN_CONTEXT_MENU_ID+AdfDhtmlPanelCollectionPeer._FREEZE_MENUITEM_ID))&&(n=f.findComponent(g+":"+AdfDhtmlPanelCollectionPeer._COLUMN_CONTEXT_MENU_ID+AdfDhtmlPanelCollectionPeer._UNFREEZE_MENUITEM_ID));m&&(m.setProperty("disabled",this._isFreezeDisabled(q),!1,AdfUIComponent.PROPAGATE_LOCALLY),m.setProperty("visible",!p,!1,AdfUIComponent.PROPAGATE_LOCALLY),
n.setProperty("visible",p,!1,AdfUIComponent.PROPAGATE_LOCALLY));if(k){m=!0;for(n=q.length-1;0<=n;n--)if(p=q[n],p.getSortProperty()&&p.getSortable()){m=!1;break}m?k.getParent().setProperty("disabled",!0,!1,AdfUIComponent.PROPAGATE_LOCALLY):(k.getParent().setProperty("disabled",!1,!1,AdfUIComponent.PROPAGATE_LOCALLY),this._updateSortMenuItems(d,q,k,l))}if(f=f.findComponent(g+":"+AdfDhtmlPanelCollectionPeer._COLUMN_CONTEXT_MENU_ID+AdfDhtmlPanelCollectionPeer._WRAP_MENUITEM_ID))k=(g=0<q.length)?this._isNodeStampColumnSelected(d,
q):!1,g=!g||k,q=!g&&!q[0].getNoWrap(),f.setProperty("disabled",g,!1,AdfUIComponent.PROPAGATE_LOCALLY),f.setProperty("selected",q,!1,AdfUIComponent.PROPAGATE_LOCALLY);e.showContextMenu(a,h.getClientId(),null,b,null,d.getClientId())}}};AdfDhtmlPanelCollectionPeer.prototype.HandleComponentAction=function(a){var b=a.getSource().getClientId(),d=AdfDhtmlPanelCollectionPeer._ACTION_HANDLER_MAP,e;for(e in d)if(0<=b.indexOf(e)){d[e].call(this,a);a.cancel();a.stopBubbling();break}};
AdfDhtmlPanelCollectionPeer.prototype.showAllColumns=function(){var a=new AdfTableShowColumnsEvent(this._aggregatedChild,null,"showAll");AdfPage.PAGE.queueEventToServer(a);this._updateShowColMenuItems(!0);this._checkUpdateViewMenu("all")};
AdfDhtmlPanelCollectionPeer.prototype._updateShowColMenuItems=function(a,b){var d=AdfPage.PAGE,e=this.getComponent().getClientId();if(!this._columnIdWithMenus){var f=AdfAgent.AGENT.getAttribute(this.getDomElement(),AdfDhtmlPanelCollectionPeer._COL_IDS_WITH_MENUS_KEY);this._columnIdWithMenus=eval(f)}var f=this._columnIdWithMenus,g=AdfDhtmlPanelCollectionPeer._COLUMNS_SHOWCOLUMN_MENUITEM_ID,h=AdfDhtmlPanelCollectionPeer._COLUMN_CONTEXT_MENU_ID,k=d.findComponent(e+":"+AdfDhtmlPanelCollectionPeer._COLUMN_CONTEXT_MENU_ID);
k&&d.addPartialTargets(k);if(f)for(k=f.length-1;0<=k;--k){var l=f[k],m=e+":"+g+l,n=d.findComponent(m),m=e+":"+h+g+l,m=d.findComponent(m);null!=n&&(l=a||-1!=AdfCollections.indexOf(b,l),n.setSelected(l),d.addPartialTargets(n),null!=m&&(m.setSelected(l),d.addPartialTargets(m)))}};
AdfDhtmlPanelCollectionPeer.prototype.showColumn=function(a){var b=AdfPage.PAGE,d=this.getComponent().getClientId(),e=a.getSource().getClientId(),f=AdfDhtmlPanelCollectionPeer._COLUMNS_SHOWCOLUMN_MENUITEM_ID,g=e.substr(e.indexOf(f)+f.length),g=g.replace(/_afrSep_/g,":"),h=this._aggregatedChild;a=h.findComponent(g);h=new AdfTableShowColumnsEvent(h,h.getClientId()+":"+g,a?"hide":"show");b.queueEventToServer(h);0<=e.indexOf(AdfDhtmlPanelCollectionPeer._COLUMN_CONTEXT_MENU_ID)?b=b.findComponent(d+":"+
f+g):(d=d+":"+AdfDhtmlPanelCollectionPeer._COLUMN_CONTEXT_MENU_ID+f+g,b=b.findComponent(d));b&&(b.setSelected(null==a),AdfPage.PAGE.addPartialTargets(b));this._checkUpdateViewMenu(a?"hide":"show")};
AdfDhtmlPanelCollectionPeer.prototype._checkUpdateViewMenu=function(a){var b;if("multiple"!=a){var d=this._aggregatedChild.getPeer().__getVisibleLeafColumns();b=d.length;for(var e=0;e<b;++e){var f=d[e];if(f&&f.getRowHeader()){--b;break}}}switch(a){case "show":if(1!=b)return;break;case "hide":if(2!=b)return;break;case "all":if(2<=b)return}a=this.getComponent().getClientId();(a=AdfPage.PAGE.findComponent(a+":"+AdfDhtmlPanelCollectionPeer._VIEW_MENU_ID))&&AdfPage.PAGE.addPartialTargets(a)};
AdfDhtmlPanelCollectionPeer.prototype.toggleFreeze=function(){this._hasFrozenColumn(this._aggregatedChild)?this.unfreezeColumns():this.freezeColumns()};
AdfDhtmlPanelCollectionPeer.prototype.freezeColumns=function(){var a=this._aggregatedChild,b=a.getPeer();this._hasFrozenColumn(a)&&this.unfreezeColumns();for(var d=null,e=b.__getVisibleLeafColumns(),f=e.length,g=f-1;null==d&&0<=g;){var h=e[g];h&&h.getSelected()&&g!=f-1&&(d=h);g--}null!=d&&(b=this._getRootColumn(d,b),null!=b&&(d=b),d.setProperty(AdfRichColumn.FROZEN,!0,!0),AdfPage.PAGE.addPartialTargets(a))};
AdfDhtmlPanelCollectionPeer.prototype.unfreezeColumns=function(){var a=this._aggregatedChild;frozenColumn=this._getFrozenColumn(a);null!=frozenColumn&&(frozenColumn.setProperty(AdfRichColumn.FROZEN,!1,!0),AdfPage.PAGE.addPartialTargets(a))};AdfDhtmlPanelCollectionPeer.prototype.isDetached=function(){return this.getComponent().getProperty("_afrDetached")};
AdfDhtmlPanelCollectionPeer.prototype._getDOMContent=function(){var a=AdfAgent.AGENT,b,d=this.getComponent().getClientId();b=AdfRichUIPeer.CreateSubId(d,AdfDhtmlPanelCollectionPeer._AUTO_HEIGHT_CENTER_ID);var e=a.getElementById(b);if(e){b=this.getDomDocument().createElement("div");b.style.cssText="position:absolute;width:100%;height:100%";var f=AdfRichUIPeer.CreateSubId(d,AdfDhtmlPanelCollectionPeer._AUTO_HEIGHT_TOP_ID),f=a.getElementById(f),d=AdfRichUIPeer.CreateSubId(d,AdfDhtmlPanelCollectionPeer._AUTO_HEIGHT_BOTTOM_ID),
a=a.getElementById(d);f&&b.appendChild(f);b.appendChild(e);a&&b.appendChild(a)}else for(b=this.getDomElement().firstChild;b&&1!=b.nodeType;)b=b.nextSibling;return b};AdfDhtmlPanelCollectionPeer.prototype.__getAutoHeightTopFacetId=function(){return AdfDhtmlPanelCollectionPeer._AUTO_HEIGHT_TOP_ID};AdfDhtmlPanelCollectionPeer.prototype.__getAutoHeightBottomFacetId=function(){return AdfDhtmlPanelCollectionPeer._AUTO_HEIGHT_BOTTOM_ID};
AdfDhtmlPanelCollectionPeer.prototype._restoreDOMContent=function(){var a=this.getComponent(),b=AdfAgent.AGENT,d=a.getClientId(),a=this.getDomElement(),e=AdfRichUIPeer.CreateSubId(d,AdfDhtmlPanelCollectionPeer._AUTO_HEIGHT_CENTER_ID),e=b.getElementById(e),f=AdfRichUIPeer.CreateSubId(d,AdfDhtmlPanelCollectionPeer._DETACH_DIALOG_WRAPPER_ID),f=b.getElementById(f);if(e){var g=AdfRichUIPeer.CreateSubId(d,AdfDhtmlPanelCollectionPeer._AUTO_HEIGHT_TOP_ID),g=b.getElementById(g),d=AdfRichUIPeer.CreateSubId(d,
AdfDhtmlPanelCollectionPeer._AUTO_HEIGHT_BOTTOM_ID);(b=b.getElementById(d))&&a.insertBefore(b,a.firstChild);a.insertBefore(e,a.firstChild);g&&a.insertBefore(g,a.firstChild);f.removeChild(f.firstChild)}else a.insertBefore(f.firstChild,a.firstChild)};AdfDhtmlPanelCollectionPeer.prototype.detach=function(){var a=this.getComponent();a.getProperty("_afrDetached")?this.hidePopup(a,AdfDhtmlPanelCollectionPeer._DETACH_DIALOG_POPUP_ID):(a.setProperty("_afrDetached",!0,!1,!0),this._detachContent(a))};
AdfDhtmlPanelCollectionPeer.prototype._detachContent=function(a){var b=a.getClientId(),d=AdfRichUIPeer.CreateSubId(b,AdfDhtmlPanelCollectionPeer._DETACH_DIALOG_CONTAINER_ID),e=AdfAgent.AGENT,f=AdfPage.PAGE;this._restoreFocusElement=f.getActiveDomElement();if(d=e.getElementById(d)){for(var g=d.firstChild;g&&1!=g.nodeType;)g=g.nextSibling;var d=this._aggregatedChild.getPeer(),h=d.__getScrollPos(),k=this._getDOMContent(),l=this.getDomElement(),m=AdfRichUIPeer.CreateSubId(b,AdfDhtmlPanelCollectionPeer._DETACH_DIALOG_WRAPPER_ID),
m=e.getElementById(m);m.className=l.className;l=g.id;AdfAssert.assertString(l);l=f.findComponent(l);AdfAssert.assertPrototype(l,AdfRichPanelWindow);var n=e.getWindowWidth(),e=e.getWindowHeight();l.setContentWidth(Math.max(100,n-60));l.setContentHeight(Math.max(100,e-80));m.appendChild(k);e=AdfPage.PAGE.getLocaleContext().isRightToLeft()?6:1;k={};k[AdfDhtmlPopupHints.MOUSEPOSITION]={x:e,y:1};k[AdfDhtmlPopupHints.MODAL]=!0;k[AdfDhtmlPopupHints.AUTODISMISS]=AdfDhtmlPopupHints.AUTODISMISS_NEVER;this.showPopup(a,
g,k,AdfDhtmlPanelCollectionPeer._DETACH_DIALOG_POPUP_ID);d.isHeightAutoSized()&&(d.__fixPanelCollectionDimensions(!1),f.doResizeNotifyDom(d.getDomElement(),!0));a=f.findComponent(b+":"+AdfDhtmlPanelCollectionPeer._DETACH_TOOLBARITEM_ID);b=f.findComponent(b+":"+AdfDhtmlPanelCollectionPeer._DETACH_MENUITEM_ID);a&&(a.setSelected(!0),f=f.getLookAndFeel().getTranslatedString("af_panelCollection.TIP_BUTTON_REDUCE"),a.setShortDesc(f),a.getText()&&a.setText(f));b&&b.setSelected(!0);null!=h&&d.__restoreScrollerPositions(h.x,
h.y)}};
AdfDhtmlPanelCollectionPeer.prototype.PopupClosed=function(a,b,d){AdfDhtmlPanelCollectionPeer.superclass.PopupClosed.call(this,a,b);var e=AdfAgent.AGENT;if("true"!=b.getAttribute(AdfDhtmlPopupWindow.__REPLACEDOM_EXPANDO)&&d==AdfDhtmlPanelCollectionPeer._DETACH_DIALOG_POPUP_ID){var f=this._aggregatedChild.getPeer(),g=f.__getScrollPos();d=AdfPage.PAGE;var h=a.getClientId();this._restoreDOMContent();var k=this.getDomElement(),l=AdfRichUIPeer.CreateSubId(h,AdfDhtmlPanelCollectionPeer._DETACH_DIALOG_CONTAINER_ID);e.getElementById(l).appendChild(b);
b=d.findComponent(h+":"+AdfDhtmlPanelCollectionPeer._DETACH_TOOLBARITEM_ID);(h=d.findComponent(h+":"+AdfDhtmlPanelCollectionPeer._DETACH_MENUITEM_ID))&&h.setSelected(!1);b&&(b.setSelected(!1),h=d.getLookAndFeel().getTranslatedString("af_panelCollection.TIP_BUTTON_DETACH"),b.setShortDesc(h),b.getText()&&b.setText(h));a.setProperty("_afrDetached",!1,!1,!0);f.isHeightAutoSized()?(f.__fixPanelCollectionDimensions(!1),f.GetDataBody().style.height="auto",d.doResizeNotifyDom(f.getDomElement(),!0)):d.doResizeNotifyDom(k,
!1);null!=g&&f.__restoreScrollerPositions(g.x,g.y);AdfAgent.AGENT.getPlatform()==AdfAgent.IE_PLATFORM&&AdfPage.PAGE.addPartialTargets(f.getComponent());this._restoreFocusElement&&(e.getPlatform()==AdfAgent.IE_PLATFORM?(a={},a.focusElement=this._restoreFocusElement,d.scheduleTimer(this,this._delayedIECheckedFocus,a,10,{isSynchronized:!0})):AdfFocusUtils.isFocusable(this._restoreFocusElement)&&AdfFocusUtils.focusElement(this._restoreFocusElement))}};
AdfDhtmlPanelCollectionPeer.prototype._delayedIECheckedFocus=function(a){AdfFocusUtils.focusElement(a.focusElement)};AdfDhtmlPanelCollectionPeer.prototype._getTheSelectedColumn=function(a){a=a.getPeer().__getVisibleLeafColumns();for(var b=null,d=a.length,e=0;e<d;e++){var f=a[e];if(f&&f.getSelected()){b=f;break}}return b};
AdfDhtmlPanelCollectionPeer.prototype._triggerSortEvent=function(a){this._initialize();var b=this._aggregatedChild,d=this._getTheSelectedColumn(b);if(d){var e=d.getSortProperty();e&&(AdfAssert.assertBoolean(a),AdfDhtmlTableBasePeer.__getSortOrderForColumn(d.getClientId())!=a&&AdfTableUtils.queueSortEvent(b,e,a))}};AdfDhtmlPanelCollectionPeer.prototype.sortAscending=function(){this._triggerSortEvent(!0)};AdfDhtmlPanelCollectionPeer.prototype.sortDescending=function(){this._triggerSortEvent(!1)};
AdfDhtmlPanelCollectionPeer.prototype.sortAdvanced=function(){this._showAdvancedDialog(AdfDhtmlPanelCollectionPeer._DIALOG_TYPE_SORT)};AdfDhtmlPanelCollectionPeer.prototype.reorderColumns=function(){this._showAdvancedDialog(AdfDhtmlPanelCollectionPeer._DIALOG_TYPE_REORDER_COLS)};AdfDhtmlPanelCollectionPeer.prototype.showMoreColumns=function(a,b){this._showAdvancedDialog(AdfDhtmlPanelCollectionPeer._DIALOG_TYPE_SHOW_COLS)};
AdfDhtmlPanelCollectionPeer.prototype._showAdvancedDialog=function(a){var b=this.getComponent(),d=b.getClientId(),e=AdfPage.PAGE,b=new AdfPanelCollectionDialogFetchEvent(b,a);e.queueEventToServer(b);this._openedDialogType=a;e.findComponent(d+":"+AdfDhtmlPanelCollectionPeer._POPUP_ID).show()};
AdfDhtmlPanelCollectionPeer.prototype.showQBE=function(){var a=this._aggregatedChild,b=this.getComponent().getClientId(),d=AdfPage.PAGE,e=!a.getFilterVisible(),d=AdfPage.PAGE,f=d.getLookAndFeel().getTranslatedString("AFResponseCompleteStatus");d.announceToAssistiveTechnology(f);a.setProperty(AdfRichTable.FILTER_VISIBLE,e,!0);d.addPartialTargets(a);f=new AdfQueryEvent(a);e||f.setClearAll(!0);a.queueEvent(f);a=d.findComponent(b+":"+AdfDhtmlPanelCollectionPeer._QBE_TOOLBARITEM_ID);b=d.findComponent(b+
":"+AdfDhtmlPanelCollectionPeer._QBE_MENUITEM_ID);a.setSelected(e);b&&b.setSelected(e)};AdfDhtmlPanelCollectionPeer.prototype.resizeColumn=function(){this._showAdvancedDialog(AdfDhtmlPanelCollectionPeer._DIALOG_TYPE_RESIZE_COL)};
AdfDhtmlPanelCollectionPeer.prototype.HandleComponentPopupOpening=function(a){null!=this._openedDialogType&&this._openedDialogType==AdfDhtmlPanelCollectionPeer._DIALOG_TYPE_SORT&&(a=this.getComponent().getClientId()+":"+AdfDhtmlPanelCollectionPeer._DIALOG_TYPE_SORT_ID,AdfPage.PAGE.findComponent(a).getPeer().__setDefaultButtonDisabled(a,!0))};
AdfDhtmlPanelCollectionPeer.prototype.HandleComponentValueChange=function(a){if(null!=this._openedDialogType&&this._openedDialogType==AdfDhtmlPanelCollectionPeer._DIALOG_TYPE_SORT){var b=this.getComponent().getClientId();a=AdfPage.PAGE;for(var d=AdfDhtmlPanelCollectionPeer._MAX_SORT_COLUMNS,e=!1,f=0;f<d;++f){var g=a.findComponent(b+":"+AdfDhtmlPanelCollectionPeer._SORT_DIALOG_CHOICE_ID+f);null!=g&&g.getValue()&&(e=!0)}b=b+":"+AdfDhtmlPanelCollectionPeer._DIALOG_TYPE_SORT_ID;a.findComponent(b).getPeer().__setDefaultButtonDisabled(b,
!e)}};AdfDhtmlPanelCollectionPeer.prototype.HandleComponentPopupClosed=function(a){delete this._openedDialogType};
AdfDhtmlPanelCollectionPeer.prototype.HandleComponentDialog=function(a){if(null!=this._openedDialogType){var b=!0;if(a.getOutcome()==AdfDialogEvent.OUTCOME_OK){var d=this._openedDialogType;d==AdfDhtmlPanelCollectionPeer._DIALOG_TYPE_SORT?this._handleAdvancedSortOK(a):d==AdfDhtmlPanelCollectionPeer._DIALOG_TYPE_SHOW_COLS||d==AdfDhtmlPanelCollectionPeer._DIALOG_TYPE_REORDER_COLS?this._handleShowColumnsOK(a):d==AdfDhtmlPanelCollectionPeer._DIALOG_TYPE_RESIZE_COL&&(b=this._handleResizeColumnOK(a));a.cancel();
b&&(a=this.getComponent().getClientId(),AdfPage.PAGE.findComponent(a+":"+AdfDhtmlPanelCollectionPeer._POPUP_ID).hide())}}};
AdfDhtmlPanelCollectionPeer.prototype._handleAdvancedSortOK=function(a){a=this.getComponent().getClientId();for(var b=AdfPage.PAGE,d=[],e=[],f=AdfDhtmlPanelCollectionPeer._MAX_SORT_COLUMNS,g=0;g<f;++g){var h=b.findComponent(a+":"+AdfDhtmlPanelCollectionPeer._SORT_DIALOG_CHOICE_ID+g);if(null!=h&&h.getValue()){var k=b.findComponent(a+":"+AdfDhtmlPanelCollectionPeer._SORT_DIALOG_RADIO_ID+g);d.push(h.getValue());e.push("Ascending"==k.getValue())}}AdfTableUtils.queueSortEvent(this._aggregatedChild,d,e)};
AdfDhtmlPanelCollectionPeer.prototype._handleShowColumnsOK=function(a){var b=this._aggregatedChild,d=this.getComponent().getClientId();a=AdfPage.PAGE;var e=a.findComponent(d+":"+AdfDhtmlPanelCollectionPeer._SHOWCOLUMNS_DIALOG_SHUTTLE_ID).getSubmittedValue(),f=this._openedDialogType==AdfDhtmlPanelCollectionPeer._DIALOG_TYPE_SHOW_COLS,b=new AdfTableShowColumnsEvent(b,e,f?"showColumns":"reorderColumns");a.queueEventToServer(b);f?(this._updateShowColMenuItems(!1,e),this._checkUpdateViewMenu("multiple")):
(d=a.findComponent(d+":"+AdfDhtmlPanelCollectionPeer._COLUMNS_MENU_ID))&&a.addPartialTargets(d)};
AdfDhtmlPanelCollectionPeer.prototype._handleResizeColumnOK=function(a){var b=this._aggregatedChild.getPeer(),d=this.getComponent().getClientId(),e=AdfPage.PAGE;a=d+":"+AdfDhtmlPanelCollectionPeer._RESIZECOLUMN_DIALOG_SPIN_ID;var f=e.findComponent(a),g=e.findComponent(d+":"+AdfDhtmlPanelCollectionPeer._RESIZECOLUMN_DIALOG_SELECTONE_ID),d=f.getValue(),e=b.__getSelectedColumns(),h=e.length,k=!1,l=1,m=1E3,g=g.getValue();"Pixel"==g?(l=f.getProperty("_rszDSpnMinPix"),d<l&&(k=!0)):"Percent"==g&&(m=100,
d<l||d>m)&&(k=!0);if(k)return AdfPage.PAGE.clearMessages(a),b=TrFastMessageFormatUtils.format(f.getProperty("_rszDSpnErrDtl"),null,null,l,m),f=new AdfFacesMessage(AdfFacesMessage.TYPE_ERROR,f.getProperty("_rszDSpnErrMsg"),b),AdfPage.PAGE.addMessage(a,f,!1),AdfPage.PAGE.showMessages(a),!1;AdfPage.PAGE.clearMessages(a);"Percent"==g&&(d=b.__getPixelWidthFromPercent(d));for(a=0;a<h;a++)d=Math.max(d,e[a].getMinimumWidth());for(a=0;a<h;a++)e[a].setProperty(AdfRichColumn.WIDTH,d,!0);return!0};
AdfDhtmlPanelCollectionPeer.prototype.wrapColumns=function(){for(var a=this._aggregatedChild,b=a.getPeer().__getVisibleLeafColumns(),d=[],e=b.length,f=0;f<e;f++){var g=b[f];g&&g.getSelected()&&d.push(g)}for(var h,e=d.length,f=0;f<e;f++)g=d[f],0==f&&(h=!g.getNoWrap()),g.setProperty(AdfRichColumn.NO_WRAP,h,!0),AdfPage.PAGE.addPartialTargets(a)};
AdfDhtmlPanelCollectionPeer.prototype.HandleComponentShowColumns=function(a){if("reorderColumn"==a.getShowType()){var b=this.getComponent().getClientId();a=AdfPage.PAGE;var d=a.findComponent(b+":"+AdfDhtmlPanelCollectionPeer._COLUMNS_MENU_ID);d&&(this._hasColumnSelection?(b=a.findComponent(b+":"+AdfDhtmlPanelCollectionPeer._COLUMN_CONTEXT_MENU_ID+AdfDhtmlPanelCollectionPeer._COLUMNS_MENU_ID),a.addPartialTargets(d,b)):a.addPartialTargets(d))}};
AdfDhtmlPanelCollectionPeer.prototype.expandNode=function(){var a=this._aggregatedChild,b=a.getPeer(),d=null,e=a.getSelectedRowKeys(),f;for(f in e)if(AdfAssert.assert(f!=AdfDhtmlTableBasePeer.SELECTALL_KEY_PROPERTY,"expand node cannot be invoked on selectAll"),isLeafNode=b.isLeaf(f),isExpanded=a.isPathExpanded(f),null==d&&(d=!isExpanded),!isLeafNode)if(d&&!isExpanded){a.setDisclosedRowKey(f,!0);break}else if(!d&&isExpanded){a.setDisclosedRowKey(f,!1);break}};
AdfDhtmlPanelCollectionPeer.prototype.expandAllNodesBelow=function(){var a=this._aggregatedChild,b=a.getPeer(),a=a.getSelectedRowKeys(),d;for(d in a){b.discloseAll(d,!0);break}};AdfDhtmlPanelCollectionPeer.prototype.collapseAllNodesBelow=function(){var a=this._aggregatedChild,b=a.getPeer(),a=a.getSelectedRowKeys(),d;for(d in a){b.discloseAll(d,!1);break}};AdfDhtmlPanelCollectionPeer.prototype.expandAllNodes=function(){this._aggregatedChild.getPeer().discloseAll("",!0)};
AdfDhtmlPanelCollectionPeer.prototype.collapseAllNodes=function(){this._aggregatedChild.getPeer().discloseAll("",!1)};AdfDhtmlPanelCollectionPeer.prototype.showNodeAsTop=function(){var a=this._aggregatedChild,b=a.getPeer(),a=a.getSelectedRowKeys(),d;for(d in a){b.showAsTop(d);break}};AdfDhtmlPanelCollectionPeer.prototype.scrollToLast=function(){var a=this._aggregatedChild;a.setProperty("displayRow",null,!1,AdfUIComponent.PROPAGATE_NEVER);a.setProperty("displayRow","last",!1,AdfUIComponent.PROPAGATE_ALWAYS)};
AdfDhtmlPanelCollectionPeer.prototype.scrollToFirst=function(){var a=this._aggregatedChild;a.setProperty("displayRow",null,!1,AdfUIComponent.PROPAGATE_NEVER);a.setProperty("displayRow","first",!1,AdfUIComponent.PROPAGATE_ALWAYS)};AdfDhtmlPanelCollectionPeer.prototype.goToTopNode=function(){this._aggregatedChild.getPeer().showAsTop(null)};AdfDhtmlPanelCollectionPeer.prototype.goUpNode=function(){this._aggregatedChild.getPeer().goUp()};
AdfDhtmlPanelCollectionPeer.prototype.getDescendantComponents=function(a,b){if(a.getProperty("_afrDetached")){var d=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlPopupWindow.__POPUP_CONTAINER_ID);node=document.getElementById(d);AdfAssert.assertDomElement(node);return AdfAgent.AGENT.getDescendantComponentsForNode(node,b)}return AdfDhtmlPanelCollectionPeer.superclass.getDescendantComponents.call(this,a,b)};