AdfUIComponents.createComponentClass("AdfRichPanelGridLayout",{componentType:"oracle.adf.RichPanelGridLayout",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"landmark",type:"String","default":"none"},{name:"dimensionsFrom",type:"String","default":"auto"}],superclass:AdfUIPanel});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlPanelGridLayoutPeer",!1);AdfDhtmlPanelGridLayoutPeer.InitSubclass=function(){AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichPanelGridLayout.INLINE_STYLE)};
AdfDhtmlPanelGridLayoutPeer.prototype.ComponentInlineStyleChanged=function(a,b,d,e){var f=b.style,g=f.display,h=f.position,k=f.left,l=f.right,m=f.top,n=f.bottom,p=f.width,q=f.minWidth,r=f.maxWidth,t=f.height,u=f.minHeight,v=f.maxHeight,w=[];if("n"==AdfAgent.AGENT.getAttribute(b,"_afrm")){var y=f.msGridColumns,f=f.msGridRows;AdfDhtmlPanelGridLayoutPeer.superclass.ComponentInlineStyleChanged.call(this,a,b,d,e);null!=y&&""!=y&&w.push("-ms-grid-columns:"+y);null!=f&&""!=f&&w.push("-ms-grid-rows:"+f)}else AdfDhtmlPanelGridLayoutPeer.superclass.ComponentInlineStyleChanged.call(this,
a,b,d,e),null!=this._forcedDimensionStyles&&AdfDomUtils.addInlineStyle(b,this._forcedDimensionStyles,!0);null!=g&&""!=g&&w.push("display:"+g);null!=h&&""!=h&&w.push("position:"+h);null!=k&&""!=k&&w.push("left:"+k);null!=l&&""!=l&&w.push("right:"+l);null!=m&&""!=m&&w.push("top:"+m);null!=n&&""!=n&&w.push("bottom:"+n);null!=p&&""!=p&&w.push("width:"+p);null!=q&&""!=q&&w.push("min-width:"+q);null!=r&&""!=r&&w.push("max-width:"+r);null!=t&&""!=t&&w.push("height:"+t);null!=u&&""!=u&&w.push("min-height:"+
u);null!=v&&""!=v&&w.push("max-height:"+v);0<w.length&&AdfDomUtils.addInlineStyle(b,w.join(";"),!0)};AdfDhtmlPanelGridLayoutPeer.prototype.needsResizeNotify=function(a){return!0};AdfDhtmlPanelGridLayoutPeer.prototype.needsChildVisibilityChanges=function(a){return!0};AdfDhtmlPanelGridLayoutPeer.prototype.ComponentRemoved=function(a){this._registeredForDescendantResize&&AdfPage.PAGE.__unregisterDescendantResizeNotifyComponent(a)};
AdfDhtmlPanelGridLayoutPeer.prototype.ResizeNotify=function(a,b,d,e){a=this.getComponent();if(null!=this._forcedDimensionStyles){b=-1!=this._getColumns(a).indexOf("%");var f=-1!=this._getRows(a).indexOf("%"),g=-1!=this._getColumns(a).indexOf("auto"),h=-1!=this._getRows(a).indexOf("auto");if(!(b||f||g||h))return}b=this.getDomElement();null!=AdfDomUtils.getFirstChildElement(b)&&(d=this._repositionPanes(d,e),this._registeredForDescendantResize&&!d?(AdfPage.PAGE.__unregisterDescendantResizeNotifyComponent(a),
this._registeredForDescendantResize=!1):d&&(AdfPage.PAGE.__registerDescendantResizeNotifyComponent(a),this._registeredForDescendantResize=!0),"hidden"==b.style.visibility&&(b.style.visibility="visible"))};AdfDhtmlPanelGridLayoutPeer.prototype.ChildVisibilityChanged=function(a,b,d){return this._isChild(b)?(AdfDomUtils.setVisible(b.parentNode,d),this._repositionPanes(),AdfDomUtils.setVisible(b,d),AdfPage.PAGE.doResizeNotify(this.getComponent()),!0):!1};
AdfDhtmlPanelGridLayoutPeer.prototype._isChild=function(a){return a.parentNode.parentNode==this.getDomElement()};AdfDhtmlPanelGridLayoutPeer.prototype._getColumns=function(a){null==this._columns&&(this._columns=a.getProperty("_privateColumns"));return this._columns};AdfDhtmlPanelGridLayoutPeer.prototype._getRows=function(a){null==this._rows&&(this._rows=a.getProperty("_privateRows"));return this._rows};
AdfDhtmlPanelGridLayoutPeer.prototype._repositionPanes=function(a,b){var d=this.getDomElement(),e=AdfAgent.AGENT;if("n"==e.getAttribute(d,"_afrm"))return!1;for(var f=this.getComponent(),g=this._getColumns(f).split(" "),h=this._getRows(f).split(" "),k=0,l=0,m=AdfDomUtils.getChildElements(d),n=[],p=AdfLogger.LOGGER,q=null,r=-1!=this._getColumns(f).indexOf("%"),t=-1!=this._getRows(f).indexOf("%"),u,v,w,y,A=m.length-1,B=0;B<=A;B++){var z=m[B];if(null!=e.getAttribute(z,"_afrc")||null!=e.getAttribute(z,
"_afrr")){var D=AdfDomUtils.getFirstChildElement(z);null==D&&(D=AdfDomUtils.getFirstChildNodeByType(z,3));if(null==D)B==A&&null!=e.getAttribute(z,"_afrr")?q=z:p.finest("The grid layout ("+f.getClientId()+") has an empty grid cell under wrapper index \x3d "+B+", wrapper.innerHTML \x3d "+z.innerHTML+")");else if(3==D.nodeType||AdfDomUtils.isVisible(D)){var E=this._getAttribute(e,z,"_afrc","1 1 1 1 stretch stretch").split(" ");u=parseInt(E[0],10);v=parseInt(E[1],10);w=parseInt(E[2],10);y=parseInt(E[3],
10);var C=E[4],E=E[5];0<u&&0<w&&(data={wrapper:z,child:D,col:u,cspan:v,row:w,rspan:y,halign:C,valign:E},k=Math.max(k,u+v-1),l=Math.max(l,w+y-1),n.push(data))}else p.isLoggable(AdfLogger.FINE)&&p.fine("The grid layout ("+f.getClientId()+") has an invisible child (wrapper index \x3d "+B+", child.id \x3d "+D.id+", wrapper.innerHTML \x3d "+z.innerHTML+")")}}if(0==n.length)return p.isLoggable(AdfLogger.FINE)&&p.fine("The grid layout ("+f.getClientId()+") has no child data to process (wrappers.length \x3d "+
m.length+")."),!1;m=AdfPage.PAGE.getLocaleContext().isRightToLeft();A=!1;u=this._resolveSizes(g,k,d,n,"col","cspan","halign","clientWidth",a);y=this._resolveSizes(h,l,d,n,"row","rspan","valign","clientHeight",b);v=u[0];w=y[0];A||(A=u[1]||y[1]);null==q&&(q=d.ownerDocument.createElement("div"),e.setAttribute(q,"_afrr","y"),d.appendChild(q));AdfDomUtils.addInlineStyle(q,"width:"+v+"px;height:"+w+"px",!0);u="";r||(u+="max-width:"+v+"px;min-width:"+v+"px;");t||(u+="max-height:"+w+"px;min-height:"+w+"px;");
""!=u&&(AdfDomUtils.addInlineStyle(d,u,!0),this._forcedDimensionStyles=u);p.isLoggable(AdfLogger.FINE)&&(p.fine("Grid layout details for "+f.getClientId()+" (childData.length \x3d "+n.length+")"),p.fine("Columns: "+g),p.fine("Rows: "+h),p.fine("Grid (permanent) dimensions: "+v+"px and "+w+"px."));r=n.length;for(B=0;B<r;B++)data=n[B],"center"==data.halign&&(data.sw=data.wrapper.scrollWidth),"middle"==data.valign&&(data.sh=data.wrapper.scrollHeight);for(B=0;B<r;B++)data=n[B],z=data.wrapper,u=data.col,
v=data.cspan,w=data.row,y=data.rspan,C=data.halign,E=data.valign,t=[],"center"==C?(A=!0,e=this._getFirstEdge(g,u),q=this._getFirstEdge(g,u+v),e=e+Math.ceil(Math.max(0,q-e)/2-data.sw/2)+"px",m?t.push("right:"+e):t.push("left:"+e)):"stretch"==C?(e=this._getFirstEdge(g,u),q=this._getFirstEdge(g,u+v),m?t.push("right:"+e+"px"):t.push("left:"+e+"px"),t.push("width:"+(q-e)+"px")):m?("end"!=C&&t.push("right:"+this._getFirstEdge(g,u)+"px"),"start"!=C&&(e=this._getLastEdge(g,u+v-1),t.push("left:"+e+"px"))):
("end"!=C&&t.push("left:"+this._getFirstEdge(g,u)+"px"),"start"!=C&&(e=this._getLastEdge(g,u+v-1),t.push("right:"+e+"px"))),"middle"==E?(A=!0,e=this._getFirstEdge(h,w),q=this._getFirstEdge(h,w+y),t.push("top:"+(e+Math.ceil(Math.max(0,q-e)/2-data.sh/2))+"px")):"stretch"==E?(e=this._getFirstEdge(h,w),q=this._getFirstEdge(h,w+y),t.push("top:"+e+"px"),t.push("height:"+(q-e)+"px")):("bottom"!=E&&t.push("top:"+this._getFirstEdge(h,w)+"px"),"top"!=E&&(e=this._getLastEdge(h,w+y-1),t.push("bottom:"+e+"px"))),
0<t.length&&AdfDomUtils.addInlineStyle(z,t.join(";"),!0),p.isLoggable(AdfLogger.FINE)&&p.fine("child "+B+": c\x3d"+u+" (span\x3d"+v+") halign\x3d"+C+" -- r\x3d"+w+" (span\x3d"+y+") valign\x3d"+E);a!=d.clientWidth||b!=d.clientHeight?this._repositionPanesDirty(f,d,a,b):this._cancelRepositionCallback();return A};AdfDhtmlPanelGridLayoutPeer.prototype._stopRepositionCallback=function(){this._repositionTimer=this._repositionCount=null};
AdfDhtmlPanelGridLayoutPeer.prototype._cancelRepositionCallback=function(){null!=this._repositionTimer&&AdfPage.PAGE.cancelTimer(this._repositionTimer);this._repositionTimer=this._repositionCount=null};AdfDhtmlPanelGridLayoutPeer.prototype._startRepositionCallback=function(){this._repositionCount=1;this._repositionTimer=AdfPage.PAGE.scheduleTimer(this,this._stopRepositionCallback,{},1E3)};
AdfDhtmlPanelGridLayoutPeer.prototype._repositionPanesDirty=function(a,b,d,e){var f=AdfLogger.LOGGER;if(null==this._repositionCount)this._startRepositionCallback();else{if(10<++this._repositionCount&&(null==d||d>b.clientWidth||null==e||e>b.clientHeight)){f.isLoggable(AdfLogger.FINE)&&f.fine("Unsable structure encountered, stopping repositioning attempts (case a).");this._cancelRepositionCallback();return}if(15<++this._repositionCount){f.isLoggable(AdfLogger.FINE)&&f.fine("Unsable structure encountered, stopping repositioning attempts (case b).");
this._cancelRepositionCallback();return}}f.isLoggable(AdfLogger.FINE)&&f.fine("Grid layout size change, notifying ancestors: panelGridLayout\x3d"+b.id+" oldW\x3d"+d+", newW\x3d"+b.clientWidth+", oldH\x3d"+e+", newH\x3d"+b.clientHeight);AdfPage.PAGE.__queueDescendantResizeNotifySource(a);AdfPage.PAGE.__doDescendantResizeNotify()};AdfDhtmlPanelGridLayoutPeer.prototype._getFirstEdge=function(a,b){for(var d=0,e=0;e<b-1;e++)d+=a[e];return d};
AdfDhtmlPanelGridLayoutPeer.prototype._getLastEdge=function(a,b){for(var d=0,e=a.length-1;e>=b;e--)d+=a[e];return d};AdfDhtmlPanelGridLayoutPeer.prototype._getAttribute=function(a,b,d,e){a=a.getAttribute(b,d);return null==a?e:a};
AdfDhtmlPanelGridLayoutPeer.prototype._resolveSizes=function(a,b,d,e,f,g,h,k,l){h=0;var m,n,p,q,r=a.length;for(m=b-r;0<m;m--)a.push("auto");b=!1;var t=0,r=a.length;for(m=0;m<r;m++)n=a[m],"auto"==n?(b=!0,n=["auto"]):-1!=n.indexOf("%")?t+=parseFloat(n):(n=AdfDomUtils.getOffsetSizeFromCssLength(d,n),h+=n),a[m]=n;if(b){n=AdfAgent.AGENT;var u=[],v,w,y,A=e.length;for(m=0;m<A;m++)if(p=e[m],v=p[f]-1,w=v+p[g]-1,v!=w)AdfLogger.LOGGER.isLoggable(AdfLogger.FINE)&&AdfLogger.LOGGER.fine("Skipped auto resolution for a multi-span child because firstLineIndex \x3d "+
v+" and lastLineIndex \x3d "+w);else{y=-1;for(q=v;q<=w;q++)if("object"==typeof a[q]){y=q;break}-1!=y&&(q=p.wrapper,AdfDomUtils.addInlineStyle(q,"top:auto;top:auto;bottom:auto;left:auto;right:auto;width:auto;height:auto;max-width:none;max-height:none",!0),u.push([q,v,w,y]))}e=u.length;for(m=0;m<e;m++)for(f=u[m],q=f[0],v=f[1],w=f[2],y=f[3],f=0,"clientWidth"==k?(f=q.scrollWidth,n.getPlatform()==AdfAgent.GECKO_PLATFORM&&1.8<n.getVersion()&&++f):f=q.scrollHeight,q=v;q<=w;q++){if(y==q){a[q].push(f);break}g=
a[q];if("number"==typeof g&&(f=Math.max(0,f-g),0==f))break}for(q=0;q<r;q++)if(n=a[q],u=0,"object"==typeof n){w=n.length;for(m=1;m<w;m++)u=Math.max(u,n[m]);a[q]=u;h+=u}}m=0;if(0<t){m=Math.max(0,null==l?d[k]:l);r=a.length;for(q=0;q<r&&0<m;q++)n=a[q],"number"==typeof n&&(m=Math.max(0,m-n));for(q=0;q<r;q++)n=a[q],"string"==typeof n&&(d=parseFloat(n),a[q]=Math.floor(m*d/t))}return[h,b]};