AdfUIComponents.createComponentClass("AdfRichPanelHeader",{componentType:"oracle.adf.RichPanelHeader",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"helpTopicId",type:"String"},{name:"text",type:"String"},{name:"icon",type:"String"},{name:"type",type:"String","default":"default"},{name:"contentStyle",type:"String"},{name:"messageType",
type:"String","default":"none"},{name:"size",type:"Number","default":-1},{name:"headerLevel",type:"Number","default":-1},{name:"helpType",type:"String","default":"inline"}],superclass:AdfUIPanel});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlPanelHeaderPeer",!1);AdfDhtmlPanelHeaderPeer.InitSubclass=function(){AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfDialogEvent.EVENT_TYPE);this._DYNAMIC_HELP_POPUP="_afrHlpPop";this._DYNAMIC_HELP_DIALOG="_afrHlpCnt";this._TITLE_TEXT_SUBID="_afrTtxt";this._STRETCH_CELL_SUBID="_afrStr";this._MINIMUM_TITLE_TEXT_WIDTH=0;this._HEADER_TITLE_TABLE_EXPANDO="data-afr-hdr-tbl"};
AdfDhtmlPanelHeaderPeer.prototype.Init=function(a){AdfDhtmlPanelHeaderPeer.superclass.Init.call(this,a);this._stretchedOnLastResize=!0};AdfDhtmlPanelHeaderPeer.prototype.needsResizeNotify=function(a){return!0};AdfDhtmlPanelHeaderPeer.prototype.ComponentRemoved=function(a){delete this._stretchedOnLastResize;delete this._minimumTitleWidth;delete this._preferredTitleTextWidth;AdfDhtmlPanelHeaderPeer.superclass.ComponentRemoved.call(this,a)};
AdfDhtmlPanelHeaderPeer.prototype.HandleComponentClick=function(a){var b=this.getComponent(),d=b.getClientId(),e=AdfRichUIPeer.CreateSubId(d,"_afrHlpLnk"),f=AdfAgent.AGENT,g=a.getNativeEvent(),h=f.getEventTarget(g),h="A"!=h.tagName?h.parentNode:h;if(a.isLeftButtonPressed()&&h.id==e){a=AdfRichUIPeer.CreateSubId(d,"_afrHlpCtr");if(a=f.getElementById(a)){for(a=a.firstChild;a&&1!=a.nodeType;)a=a.nextSibling;null!=a&&(d={},d[AdfRichPopup.HINT_ALIGN]=AdfRichPopup.ALIGN_AFTER_START,d[AdfRichPopup.HINT_ALIGN_ID]=
e,this.showPopup(b,a,d,AdfDhtmlPanelHeaderPeer._DYNAMIC_HELP_POPUP))}f.preventDefault(g);return!0}};AdfDhtmlPanelHeaderPeer.prototype.HandleComponentDialog=function(a){var b=this.getComponent(),d=b.getClientId();AdfRichUIPeer.CreateSubId(d,AdfDhtmlPanelHeaderPeer._DYNAMIC_HELP_DIALOG)==a.getSource().getClientId()&&(a.cancel(),this.hidePopup(b,AdfDhtmlPanelHeaderPeer._DYNAMIC_HELP_POPUP))};
AdfDhtmlPanelHeaderPeer.prototype.PopupClosed=function(a,b,d){AdfDhtmlPanelHeaderPeer._DYNAMIC_HELP_POPUP==d&&(AdfDhtmlPanelHeaderPeer.superclass.PopupClosed.call(this,a,b),a=a.getClientId(),a=AdfRichUIPeer.CreateSubId(a,"_afrHlpCtr"),(a=AdfAgent.AGENT.getElementById(a))&&a.appendChild(b))};
AdfDhtmlPanelHeaderPeer.prototype.ResizeNotify=function(a,b,d,e){a=this._minimumTitleWidth;null==this._minimumTitleWidth&&(a=this._calculateMinimumTitleWidth());d>=a?this._stretchTitle():2<a-d&&this._truncateTitle(a-d)};
AdfDhtmlPanelHeaderPeer.prototype._calculateMinimumTitleWidth=function(){var a=AdfAgent.AGENT,b=this.getDomElement(),d=0,e=AdfAgent.getCSSLengthAsInt,f=a.getComputedStyle(b),f=e(f.paddingLeft)+e(f.paddingRight),d=d+f,f=AdfDomUtils.getFirstDescendentElement(b,"table"),g=AdfDomUtils.getFirstDescendentElement(f,"tr"),g=AdfDomUtils.getChildElements(g),h=f.getAttribute(AdfDhtmlPanelHeaderPeer._HEADER_TITLE_TABLE_EXPANDO);if(3==g.length&&h)var k=!0;if(k){k=AdfDomUtils.getFirstDescendentElement(f,"tr");
if(null==k)return d;k=AdfDomUtils.getChildElements(k);d+=k[0].offsetWidth;d+=k[2].offsetWidth;f=k[1];k=AdfDomUtils.getFirstDescendentElement(k[1],"table")}else k=f;f=a.getComputedStyle(f);e=e(f.paddingLeft)+e(f.paddingRight);d+=e;e=this._getTitleTextElement();f=AdfDomUtils.getFirstChildElement(e);f.style.whiteSpace="nowrap";g=Math.ceil(f.getBoundingClientRect().width);f.style.whiteSpace="";this._preferredTitleTextWidth=g;d+=g;e.style.width=g+"px";e.style.maxWidth=g+"px";a.getPlatform()==AdfAgent.GECKO_PLATFORM&&
1.8==a.getVersion()&&(e.style.overflow="hidden");a=AdfDomUtils.getFirstDescendentElement(k,"tr");a=AdfDomUtils.getChildElements(a);e=b.getAttribute("id");b=AdfRichUIPeer.CreateSubId(e,AdfDhtmlPanelHeaderPeer._TITLE_TEXT_SUBID);e=AdfRichUIPeer.CreateSubId(e,AdfDhtmlPanelHeaderPeer._STRETCH_CELL_SUBID);k=a.length;for(h=0;h<k;h++)f=a[h],g=f.getAttribute("id"),b!=g&&e!=g&&(d+=f.offsetWidth);return this._minimumTitleWidth=d};
AdfDhtmlPanelHeaderPeer.prototype._truncateTitle=function(a){a=this._preferredTitleTextWidth-a;var b=AdfDhtmlPanelHeaderPeer._MINIMUM_TITLE_TEXT_WIDTH;a=a<b?b:a;b=this._getTitleTextElement();b.style.width=a+"px";b.style.maxWidth=a+"px";this._stretchedOnLastResize=!1};AdfDhtmlPanelHeaderPeer.prototype._stretchTitle=function(){if(!this._stretchedOnLastResize){var a=this._getTitleTextElement(),b=this._preferredTitleTextWidth;a.style.width=b+"px";a.style.maxWidth=b+"px";this._stretchedOnLastResize=!0}};
AdfDhtmlPanelHeaderPeer.prototype._getTitleTextElement=function(){var a=this.getDomElement().getAttribute("id"),a=AdfRichUIPeer.CreateSubId(a,AdfDhtmlPanelHeaderPeer._TITLE_TEXT_SUBID),a=AdfAgent.AGENT.getElementById(a);return AdfDomUtils.getFirstChildElement(a)};
AdfUIComponents.createComponentClass("AdfRichShowDetailHeader",{componentType:"oracle.adf.RichShowDetailHeader",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"helpTopicId",type:"String"},{name:"text",type:"String"},{name:"icon",type:"String"},{name:"type",type:"String","default":"default"},{name:"contentStyle",type:"String"},{name:"messageType",
type:"String","default":"none"},{name:"size",type:"Number","default":-1},{name:"headerLevel",type:"Number","default":-1},{name:"persist",type:"Array"},{name:"dontPersist",type:"Array"},{name:"handleDisclosure",type:"String","default":"server"},{name:"showMaximize",type:"String","default":"auto"},"maximizeListener",{name:"maximized",type:"Boolean","default":!1},{name:"contentDelivery",type:"String","default":"lazyUncached"},{name:"disclosedTransient",type:"Boolean","default":!1},{name:"helpType",type:"String",
"default":"inline"}],superclass:AdfUIShowDetail});
AdfRichUIPeer.createPeerClass(AdfDhtmlPanelHeaderPeer,"AdfDhtmlShowDetailHeaderPeer",!1);AdfDhtmlShowDetailHeaderPeer._INNER_SD_PEER=AdfRichUIPeer.createInnerPeerClassWithSubId(AdfDhtmlShowDisclosurePeer,"InnerSDHShowDetailPeer","_afrDscl");InnerSDHShowDetailPeer.InitSubclass=function(){AdfDhtmlTogglePeer.Config(this,{toggledStyleClass:"af|showDetailHeader::disclosed-icon-style",untoggledStyleClass:"af|showDetailHeader::undisclosed-icon-style"})};
InnerSDHShowDetailPeer.prototype.HandleClientSideToggle=function(a){return InnerSDHShowDetailPeer.superclass.HandleClientSideToggle.call(this,a)?this.outerThis.__handleClientSideDisclosure(a):!1};
InnerSDHShowDetailPeer.prototype.EventPropagatesToServer=function(a){var b=InnerSDHShowDetailPeer.superclass.EventPropagatesToServer.call(this);if(0==b){var d=this.outerThis.getComponent();if("lazy"===d.getPropertyValue("contentDelivery")&&0==this.outerThis.__isContentLoaded()||0==a&&AdfPage.PAGE.getDirtyStateService().hasDirtyData(d))b=!0}return b};
AdfDhtmlShowDetailHeaderPeer.prototype.Init=function(a){AdfDhtmlShowDetailHeaderPeer.superclass.Init.call(this,a);this._disclosurePeer=new AdfDhtmlShowDetailHeaderPeer._INNER_SD_PEER(a,this);var b=a.getPropertyKeys().disclosed;null!=b&&b[AdfUIComponent.PROPERTY_DISCONNECTED]&&(b=AdfCollections.copyInto({},b),delete b[AdfUIComponent.PROPERTY_DISCONNECTED],a.getPropertyKeys().disclosed=b);this._ignoreUpAndDownArrowKey="false"==AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|showDetailHeader-tr-disclose-with-up-down-arrow")};
AdfDhtmlShowDetailHeaderPeer.prototype.initialize=function(a){AdfDhtmlShowDetailHeaderPeer.superclass.initialize.call(this,a);this._disclosurePeer.initialize(a)};AdfDhtmlShowDetailHeaderPeer.InitSubclass=function(){AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.KEY_UP_EVENT_TYPE,AdfDisclosureEvent.EVENT_TYPE);AdfRichUIPeer.addComponentPropertyChanges(this,"disclosed")};
AdfDhtmlShowDetailHeaderPeer.prototype.HandleComponentClick=function(a){AdfDhtmlShowDetailHeaderPeer.superclass.HandleComponentClick.call(this,a);this._disclosurePeer.HandleComponentClick(a)};AdfDhtmlShowDetailHeaderPeer.prototype.HandleComponentKeyUp=function(a){var b=!0;this._ignoreUpAndDownArrowKey&&(b=a.getNativeEvent(),b=AdfAgent.AGENT.getKeyCode(b),b=b!=AdfKeyStroke.ARROWUP_KEY&&b!=AdfKeyStroke.ARROWDOWN_KEY);b&&this._disclosurePeer.HandleComponentKeyUp(a)};
AdfDhtmlShowDetailHeaderPeer.prototype.HandleComponentDisclosure=function(a){this._disclosurePeer.HandleComponentDisclosure(a)};AdfDhtmlShowDetailHeaderPeer.prototype.ComponentDisclosedChanged=function(a,b,d,e){return"immediate"==a.getPropertyValue("contentDelivery")||"lazy"==a.getPropertyValue("contentDelivery")&&this.__isContentLoaded()?this._disclosurePeer.ComponentDisclosedChanged(a,b,d,e):!1};
AdfDhtmlShowDetailHeaderPeer.prototype.__handleClientSideDisclosure=function(a){var b=this._getContentDomElement();return b?(b.style.display=a?"":"none",!0):!1};AdfDhtmlShowDetailHeaderPeer.prototype.__isContentLoaded=function(){return null!=this._getContentDomElement()};AdfDhtmlShowDetailHeaderPeer.prototype._getContentDomElement=function(){return this.getDomElement().childNodes[1]};