AdfUIComponents.createComponentClass("AdfUIInputPopup",{componentType:"oracle.adf.InputPopup",propertyKeys:[{name:"launchPopupListener",type:"Object",secured:!0},{name:"model",type:"Object",secured:!0},{name:"returnPopupListener",type:"Object",secured:!0},{name:"returnPopupDataListener",type:"Object",secured:!0},{name:"returnPopupDataValue",type:"Object",secured:!0},{name:"createPopupId",type:"String",secured:!0},{name:"editMode",type:"String","default":"input",secured:!0},{name:"resultsTableColumnStretching",
type:"String","default":"last",secured:!0}],eventNames:["launchPopup","returnPopupData","returnPopup"],superclass:AdfUIInput});
function AdfLovInternalEvent(a,b){this.Init(a,b)}AdfLovInternalEvent.ACTION_CLICK="click";AdfLovInternalEvent.ACTION_TAB="tab";AdfObject.createSubclass(AdfLovInternalEvent,AdfComponentEvent);AdfLovInternalEvent.EVENT_TYPE="lovInternal";AdfLovInternalEvent.prototype.Init=function(a,b){AdfLovInternalEvent.superclass.Init.call(this,a,AdfLovInternalEvent.EVENT_TYPE);this.setRoot(a);this._action=b};AdfLovInternalEvent.prototype.getAction=function(){return this._action};
AdfLovInternalEvent.prototype.AddMarshalledProperties=function(a){a.action=this._action};AdfLovInternalEvent.prototype.propagatesToServer=function(){return!0};AdfLovInternalEvent.prototype.isImmediate=function(){return this.getSource().getImmediate()};AdfLovInternalEvent.queue=function(a,b,d){b=new AdfLovInternalEvent(a,b);d&&b.setPartial(!0);a.queueEvent(b)};
function AdfLovInternalPopupClosedEvent(a){this.Init(a,AdfLovInternalPopupClosedEvent.OPERATION_TOOLBAR_CLOSED)}function AdfLovInternalPopupClosedEvent(a,b){this.Init(a,b)}AdfObject.createSubclass(AdfLovInternalPopupClosedEvent,AdfComponentEvent);AdfLovInternalPopupClosedEvent.EVENT_TYPE="lovInternalpopupclosed";AdfLovInternalPopupClosedEvent.OPERATION_CANCEL="CANCEL";AdfLovInternalPopupClosedEvent.OPERATION_TOOLBAR_CLOSED="TOOLBAR_CLOSED";
AdfLovInternalPopupClosedEvent.prototype.Init=function(a,b){AdfLovInternalPopupClosedEvent.superclass.Init.call(this,a,AdfLovInternalPopupClosedEvent.EVENT_TYPE);this.setRoot(a);this._operation=b};AdfLovInternalPopupClosedEvent.prototype.getOperation=function(){return this._operation};AdfLovInternalPopupClosedEvent.prototype.AddMarshalledProperties=function(a){a.operation=this._operation};AdfLovInternalPopupClosedEvent.prototype.propagatesToServer=function(){return!0};
AdfLovInternalPopupClosedEvent.prototype.isImmediate=function(){return!0};AdfLovInternalPopupClosedEvent.queue=function(a,b,d){b=new AdfLovInternalPopupClosedEvent(a,b);d&&b.setPartial(!0);a.queueEvent(b)};
AdfUIComponents.createComponentClass("AdfRichInputListOfValues",{componentType:"oracle.adf.RichInputListOfValues",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"changed",type:"Boolean","default":!1},{name:"changedDesc",type:"String"},{name:"autoSubmit",type:"Boolean","default":!1},{name:"accessKey",type:"String"},{name:"contentStyle",type:"String"},
{name:"helpTopicId",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"label",type:"String"},{name:"labelStyle",type:"String"},{name:"readOnly",type:"Boolean","default":!1,secured:!0},{name:"showRequired",type:"Boolean","default":!1},{name:"simple",type:"Boolean","default":!1},{name:"editable",type:"String","default":"inherit"},{name:"placeholder",type:"String"},{name:"usage",type:"String","default":"auto"},{name:"autoTab",type:"Boolean","default":!1},{name:"autoComplete",
type:"String"},{name:"columns",type:"Number"},{name:"maximumLength",type:"Number"},{name:"characterCountBy",type:"String"},{name:"popupTitle",type:"String"},{name:"searchDesc",type:"String"}],superclass:AdfUIInputPopup});
AdfRichUIPeer.createPeerClass(AdfDhtmlInputBasePeer,"AdfDhtmlInputListOfValuesSuperBasePeer");
AdfDhtmlInputListOfValuesSuperBasePeer.InitSubclass=function(){AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.DOUBLE_CLICK_EVENT_TYPE,AdfPopupOpeningEvent.POPUP_OPENING_EVENT_TYPE,AdfPopupClosedEvent.POPUP_CLOSED_EVENT_TYPE,AdfDialogEvent.EVENT_TYPE,AdfUIInputEvent.KEY_PRESS_EVENT_TYPE);this._POPUP_SUFFIX_ID="_afrLovPopupId";this._SHOWN="_shown";this._DIALOG_CONTENT_HEIGHT="_dialogContentHeight";this._DIALOG_CONTENT_WIDTH="_dialogContentWidth";this._INTERNAL_TABLE_SUFFIX_ID="_afrLovInternalTableId";
this._INTERNAL_QUERY_ID="_afrLovInternalQueryId";this._LOVINTERNAL_EVENT_QUEUED="_afrLovInternalEventQueued";this._LOVINTERNAL_DIALOG_SUFFIX_ID="_afrLovDialogId";this._OK_PRESSED=!1;this._EDIT_MODE_SELECT="select";this._clientId=null;AdfRichUIPeer.addSuppressedPPRAttributes(this,AdfDhtmlInputListOfValuesSuperBasePeer._DIALOG_CONTENT_HEIGHT,AdfDhtmlInputListOfValuesSuperBasePeer._DIALOG_CONTENT_WIDTH,AdfDhtmlInputListOfValuesSuperBasePeer._SHOWN)};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.InitDomElement=function(a,b){AdfDhtmlInputListOfValuesSuperBasePeer.superclass.InitDomElement.call(this,a,b);var d=AdfAgent.AGENT,e=AdfDhtmlEditableValuePeer.getContentNode(a);d.getPlatform()==AdfAgent.IE_PLATFORM&&9>d.getVersion()?d.addBubbleEventListener(e,"propertychange",this.createCallback(this._handleInput)):d.addBubbleEventListener(e,"input",this.createCallback(this._handleInput))};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.getConvertedObject=function(a,b){var d=a.getConverter();null!=d&&d instanceof AdfMissingConverter&&this.SetDisplayValue(a,this.getDomElement(),b.toString());return AdfDhtmlInputListOfValuesSuperBasePeer.superclass.getConvertedObject.call(this,a,b)};AdfDhtmlInputListOfValuesSuperBasePeer.FocusInputElement=function(a){a=AdfDhtmlEditableValuePeer.getContentNode(a);AdfDhtmlInputBasePeer.setLastValue(a);AdfFocusUtils.focusElement(a)};
AdfDhtmlInputListOfValuesSuperBasePeer.GetLabelText=function(a){var b=a.getLabel();if(b)return b;b=AdfDhtmlEditableValuePeer.getContentNode(a);if(b=b.labels?b.labels[0]:document.querySelector("label[for\x3d'"+AdfDhtmlEditableValuePeer.GetContentNodeId(a)+"']"))return b.textContent;AdfLogger.LOGGER.info("Application hasn't provided label for ",a.getClientId())};AdfDhtmlInputListOfValuesSuperBasePeer.prototype.AnnounceAutoComplete=function(){AdfAssert.failedInAbstractFunction()};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.HandleComponentClickOrTouch=function(a){AdfAssert.failedInAbstractFunction()};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.ComponentRemoved=function(a){var b=this._busyStateListenerCallback;b&&this.getComponent()==a&&(AdfPage.PAGE.removeBusyStateListener(this,b),delete this._busyStateListenerCallback);(b=this._popupClosedCallback)&&AdfLogger.LOGGER.info("Potential callback leak detected - LOV _popupClosedCallback: ",b);AdfDhtmlInputListOfValuesSuperBasePeer.superclass.ComponentRemoved.call(this,a)};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.SetDisplayValue=function(a,b,d){AdfAssert.assertString(d);b=AdfDhtmlEditableValuePeer.getContentNode(a);var e="INPUT"==b.tagName;a.getReadOnly()?AdfAgent.AGENT.setTextContent(b,d):(b.title=d,e?b.value=d:AdfAgent.AGENT.setTextContent(b,d))};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.HandleComponentDblClick=function(a){var b=a.getSource();b instanceof AdfRichTable||(b=b.getParent());if(b instanceof AdfRichTable)for(a=this.getComponent(),b=b.getParent();b!=a&&null!=b;){if(b instanceof AdfRichDialog){(new AdfDialogEvent(b,AdfDialogEvent.OUTCOME_OK)).queue();break}b=b.getParent()}};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.HandleComponentDialog=function(a){var b=this.getComponent(),d=a.getSource(),e=b.getClientId()+AdfDhtmlInputListOfValuesSuperBasePeer._LOVINTERNAL_DIALOG_SUFFIX_ID;if(d.getClientId()==e){a.setRoot(b);if(this._OK_PRESSED=a.getOutcome()==AdfDialogEvent.OUTCOME_OK){e=b.getClientId()+AdfDhtmlInputListOfValuesSuperBasePeer._INTERNAL_QUERY_ID;if(e=AdfPage.PAGE.findComponent(e)){var f=e.getPeer();f.bind(e);if(!f.validateCriterionFields()){a.cancel();a.stopBubbling();
return}this.bind(b)}this.setMarkDirtyFlag(!0);AdfReturnPopupDataEvent.queue(b,!0)}else AdfLovInternalPopupClosedEvent.queue(b,AdfLovInternalPopupClosedEvent.OPERATION_CANCEL,!0);AdfDhtmlInputListOfValuesSuperBasePeer.FocusInputElement(b);if(a=this._busyStateListenerCallback)AdfPage.PAGE.removeBusyStateListener(this,a),delete this._busyStateListenerCallback;b.setProperty(AdfDhtmlInputListOfValuesSuperBasePeer._DIALOG_CONTENT_HEIGHT,d.getContentHeight(),!1,AdfUIComponent.PROPAGATE_ALWAYS);b.setProperty(AdfDhtmlInputListOfValuesSuperBasePeer._DIALOG_CONTENT_WIDTH,
d.getContentWidth(),!1,AdfUIComponent.PROPAGATE_ALWAYS)}};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.HandleComponentKeyUp=function(a){var b=this.getComponent(),d=a.getKeyCode();if(AdfKeyStroke.ENTER_KEY!=d&&AdfKeyStroke.TAB_KEY!=d||!b.getProperty(AdfDhtmlInputListOfValuesSuperBasePeer._LOVINTERNAL_EVENT_QUEUED)){if(!a.isCanceled()&&AdfKeyStroke.ENTER_KEY==d){var e=b.getClientId()+AdfDhtmlInputListOfValuesSuperBasePeer._INTERNAL_TABLE_SUFFIX_ID,f=a.getSource().getClientId();if(f&&f==e){a.cancel();a.stopBubbling();return}}a.getEventPhase()==AdfBaseEvent.AT_TARGET_PHASE&&
(d!=AdfKeyStroke.TAB_KEY&&this.AutoTab(b,a.getNativeEventTarget()),delete this._nodeLength);AdfDhtmlInputListOfValuesSuperBasePeer.superclass.HandleComponentKeyUp.call(this,a)}else a.cancel(),a.stopBubbling(),b.setProperty(AdfDhtmlInputListOfValuesSuperBasePeer._LOVINTERNAL_EVENT_QUEUED,!1,!1,AdfUIComponent.PROPAGATE_NEVER)};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.AutoTab=function(a,b){if(a.getAutoTab&&a.getAutoTab()){var d=a.getMaximumLength();if(!(1>d)){var e=b.value?b.value.length:0;e>=d&&e>this._nodeLength&&this.FocusNextElement(b)}}};AdfDhtmlInputListOfValuesSuperBasePeer.prototype.FocusNextElement=function(a){AdfAssert.failedInAbstractFunction()};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.HandleComponentKeyPress=function(a){this.StopArrowKeyBubbling(a);var b=this.getComponent(),d=a.getKeyCode();if(AdfKeyStroke.ENTER_KEY!=d&&AdfKeyStroke.TAB_KEY!=d||!b.getProperty(AdfDhtmlInputListOfValuesSuperBasePeer._LOVINTERNAL_EVENT_QUEUED)){if(!a.isCanceled()&&AdfKeyStroke.ENTER_KEY==d&&(b=b.getClientId()+AdfDhtmlInputListOfValuesSuperBasePeer._INTERNAL_TABLE_SUFFIX_ID,(d=a.getSource().getClientId())&&d==b)){a.cancel();a.stopBubbling();return}a=
a.getNativeEventTarget();this._nodeLength=a.value?a.value.length:0}else a.cancel(),a.stopBubbling()};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.HandleComponentKeyDown=function(a){this.StopArrowKeyBubbling(a);var b=a.getKeyCode(),d=this.getComponent();switch(b){case AdfKeyStroke.ENTER_KEY:if(window.AdfAutoSuggestBehaviorImpl&&AdfAutoSuggestBehaviorImpl.isPopupVisible(d,this)){a.cancel();a.stopBubbling();break}case AdfKeyStroke.TAB_KEY:var e=a.getNativeEventTarget();this.IsKeyEventInInput(d,a)&&(this._queueLovInternalEvent(d,e)?(a.cancel(),a.stopBubbling(),d.setProperty(AdfDhtmlInputListOfValuesSuperBasePeer._LOVINTERNAL_EVENT_QUEUED,
!0,!1,AdfUIComponent.PROPAGATE_NEVER),b==AdfKeyStroke.TAB_KEY&&(this.preventNextValueSubmission(),AdfFocusUtils.focusNextTabStop(e))):b==AdfKeyStroke.ENTER_KEY&&this.RunValidation(d,e));break;case AdfKeyStroke.BACKSPACE_KEY:d.getEditMode()==AdfDhtmlInputListOfValuesSuperBasePeer._EDIT_MODE_SELECT&&this.IsCancelBackSpaceKeyEvent(d,a)&&a.cancel()}};AdfDhtmlInputListOfValuesSuperBasePeer.prototype.IsCancelBackSpaceKeyEvent=function(a,b){AdfAssert.failedInAbstractFunction()};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.IsKeyEventInInput=function(a,b){var d=AdfDhtmlEditableValuePeer.GetContentNodeId(a);return b.getNativeEventTarget().id==d?!0:!1};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.HandleComponentPopupClosed=function(a){a=a.getSource();var b=this.getComponent(),d=b.getClientId()+AdfDhtmlInputListOfValuesSuperBasePeer._POPUP_SUFFIX_ID;a.getClientId()==d&&(AdfDhtmlInputListOfValuesSuperBasePeer._setShown(b,null),1==this._OK_PRESSED&&(this.setMarkDirtyFlag(!0),AdfReturnPopupDataEvent.queue(b,!0)))};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.HandleComponentPopupOpening=function(a){a=a.getSource();var b=this.getComponent(),d=b.getClientId();a==AdfDhtmlInputListOfValuesSuperBasePeer._getLovPopup(d)&&(this.HideNoteWindow(),AdfDhtmlInputListOfValuesSuperBasePeer._setShown(b,d),a=this._busyStateListenerCallback,a||(this._busyStateListenerCallback=a=this.createCallback(this._busyStateListener)),AdfPage.PAGE.addBusyStateListener(this,a))};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype._busyStateListener=function(a){var b=this.getComponent();null==b&&AdfLogger.LOGGER.severe("Unexpected null component! ",a);b=b.getClientId();if(this.IsLovPopupVisible(b)){var b=b+AdfDhtmlInputListOfValuesSuperBasePeer._LOVINTERNAL_DIALOG_SUFFIX_ID,d=AdfPage.PAGE.findComponent(b);d&&d.getPeer().__setDefaultButtonDisabled(b,a.isBusy())}};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.IsLovPopupVisible=function(a){return(a=AdfDhtmlInputListOfValuesSuperBasePeer._getLovPopup(a))&&a.isPopupVisible()?!0:!1};AdfDhtmlInputListOfValuesSuperBasePeer.prototype.ShowNoteWindow=function(a,b){a||(a=this.getComponent());a&&this.getDomElement()&&AdfDhtmlInputListOfValuesSuperBasePeer.superclass.ShowNoteWindow.call(this,a,b)};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.IsNoteWindowVisible=function(a){a||(a=this.getComponent());return a&&this.getDomElement()?AdfDhtmlInputListOfValuesSuperBasePeer.superclass.IsNoteWindowVisible.call(this,a):!1};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype._queueLovInternalEvent=function(a,b){var d=AdfDhtmlEditableValuePeer.getContentNode(a);if(b==d&&"INPUT"==b.tagName){var e=AdfDhtmlInputBasePeer.getLastValue(d),f=b.value;if(f!=e&&0<f.length&&a.getAutoSubmit())return this.setMarkDirtyFlag(!0),AdfDhtmlInputBasePeer.setLastValue(d,f),AdfLovInternalEvent.queue(a,AdfLovInternalEvent.ACTION_TAB,!0),!0}return!1};
AdfDhtmlInputListOfValuesSuperBasePeer._getLovPopup=function(a){return AdfPage.PAGE.findComponent(a+AdfDhtmlInputListOfValuesSuperBasePeer._POPUP_SUFFIX_ID)};AdfDhtmlInputListOfValuesSuperBasePeer._setShown=function(a,b){a.setProperty(AdfDhtmlInputListOfValuesSuperBasePeer._SHOWN,b,!1,!0)};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype.showToolbarPopup=function(a,b){this._clientId=a;var d=a+"_afrLovToolbar",e=AdfPage.PAGE.findComponent(b);null!=e&&(this._popupClosedCallback||(this._popupClosedCallback=this.createCallback(this._toolbarPopupClosed),e.addEventListener(AdfPopupClosedEvent.POPUP_CLOSED_EVENT_TYPE,this._popupClosedCallback)),e.show({align:AdfRichPopup.ALIGN_AFTER_END,alignId:d}))};
AdfDhtmlInputListOfValuesSuperBasePeer.prototype._toolbarPopupClosed=function(a){a=AdfPage.PAGE.findComponent(this._clientId);null!=a&&AdfLovInternalPopupClosedEvent.queue(a,AdfLovInternalPopupClosedEvent.OPERATION_TOOLBAR_CLOSED,!0)};AdfDhtmlInputListOfValuesSuperBasePeer.prototype._handleInput=function(a){if(a=this.getComponent()){var b=AdfDhtmlEditableValuePeer.getContentNode(a);this.CheckLength(a,b)}};
AdfRichUIPeer.createPeerClass(AdfDhtmlInputListOfValuesSuperBasePeer,"AdfDhtmlInputListOfValuesBasePeer");AdfDhtmlInputListOfValuesBasePeer.InitSubclass=function(){AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.CLICK_EVENT_TYPE)};AdfDhtmlInputListOfValuesBasePeer.prototype.HandleComponentClick=function(a){AdfDhtmlInputListOfValuesBasePeer.superclass.HandleComponentClick.call(this,a);a.isLeftButtonPressed()&&this.HandleComponentClickOrTouch(a)};
AdfRichUIPeer.createPeerClass(AdfDhtmlInputListOfValuesBasePeer,"AdfDhtmlInputListOfValuesPeer");
AdfDhtmlInputListOfValuesPeer.InitSubclass=function(){AdfObject.ensureClassInitialization(AdfDhtmlInputListOfValuesBasePeer);AdfRichUIPeer.addComponentPropertyGetters(this,AdfRichInputListOfValues.LABEL);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.KEY_DOWN_EVENT_TYPE,AdfUIInputEvent.KEY_UP_EVENT_TYPE,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.MOUSE_DOWN_EVENT_TYPE,AdfUIInputEvent.BLUR_EVENT_TYPE);this._ICON_ID="lovIconId";this._EDIT_MODE_SELECT="select";this._AUTOCOMPLETE_ANNOUNCE_MSG=
"af_inputListOfValues.AUTOCOMPLETE_ANNOUNCE_MSG"};AdfDhtmlInputListOfValuesPeer.prototype.AnnounceAutoComplete=function(){var a=this.getComponent(),b=AdfPage.PAGE;b.announceToAssistiveTechnology(b.getLookAndFeel().getTranslatedString(AdfDhtmlInputListOfValuesPeer._AUTOCOMPLETE_ANNOUNCE_MSG,AdfDhtmlInputListOfValuesSuperBasePeer.GetLabelText(a),a.getValue()))};
AdfDhtmlInputListOfValuesPeer.prototype.HandleComponentMouseDown=function(a){var b=this.getComponent();b.getDisabled()||(a=a.getNativeEventTarget(),b=this._getSearchIconElement(b),a!=b&&a.parentNode!=b||this.preventNextValueSubmission())};
AdfDhtmlInputListOfValuesPeer.prototype.HandleComponentClick=function(a){AdfDhtmlInputListOfValuesPeer.superclass.HandleComponentClick.call(this,a);var b=this.getComponent();a.isLeftButtonPressed()&&!b.getDisabled()&&this._isEventTargetSearchIcon(b,a)&&AdfDhtmlInputListOfValuesPeer._openSearchDialog(b,a)};
AdfDhtmlInputListOfValuesPeer.prototype.HandleComponentClickOrTouch=function(a){var b=this.getComponent();if(!b.getDisabled()){var d=a.getNativeEventTarget();b.getEditMode()==AdfDhtmlInputListOfValuesPeer._EDIT_MODE_SELECT&&d==AdfDhtmlEditableValuePeer.getContentNode(b)&&AdfDhtmlInputListOfValuesPeer._openSearchDialog(b,a)}};
AdfDhtmlInputListOfValuesPeer.prototype.HandleComponentKeyUp=function(a){AdfDhtmlInputListOfValuesPeer.superclass.HandleComponentKeyUp.call(this,a);var b=this.getComponent();if(!a.isCanceled()&&!b.getDisabled())switch(a.getKeyCode()){case AdfKeyStroke.SPACE_KEY:this._isEventTargetSearchIcon(b,a)&&AdfDhtmlInputListOfValuesPeer._openSearchDialog(b,a)}};AdfDhtmlInputListOfValuesPeer.prototype.IsCancelBackSpaceKeyEvent=function(a,b){return this.IsKeyEventInInput(a,b)};
AdfDhtmlInputListOfValuesPeer.prototype.FocusNextElement=function(a){a=AdfFocusUtils.getNextTabStop(a);AdfFocusUtils.focusNextTabStop(a)};AdfDhtmlInputListOfValuesPeer._openSearchDialog=function(a,b){AdfPage.PAGE.clearMessages(a.getClientId());AdfLaunchPopupEvent.queue(a,!0);AdfAgent.AGENT.preventDefault(b.getNativeEvent())};AdfDhtmlInputListOfValuesPeer.prototype._isEventTargetSearchIcon=function(a,b){var d=b.getNativeEventTarget(),e=this._getSearchIconElement(a);return d==e||d.parentNode==e};
AdfDhtmlInputListOfValuesPeer.prototype._getSearchIconElement=function(a){a=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlInputListOfValuesPeer._ICON_ID);return AdfAgent.AGENT.getElementById(a)};
AdfUIComponents.createComponentClass("AdfRichInputComboboxListOfValues",{componentType:"oracle.adf.RichInputComboboxListOfValues",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"changed",type:"Boolean","default":!1},{name:"changedDesc",type:"String"},{name:"autoSubmit",type:"Boolean","default":!1},{name:"accessKey",type:"String"},{name:"contentStyle",
type:"String"},{name:"helpTopicId",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"label",type:"String"},{name:"labelStyle",type:"String"},{name:"readOnly",type:"Boolean","default":!1,secured:!0},{name:"showRequired",type:"Boolean","default":!1},{name:"simple",type:"Boolean","default":!1},{name:"editable",type:"String","default":"inherit"},{name:"placeholder",type:"String"},{name:"usage",type:"String","default":"auto"},{name:"autoTab",type:"Boolean","default":!1},{name:"autoComplete",
type:"String"},{name:"columns",type:"Number"},{name:"contentDelivery",type:"String","default":"lazyUncached"},{name:"maximumLength",type:"Number"},{name:"characterCountBy",type:"String"},{name:"popupTitle",type:"String"},{name:"searchDesc",type:"String"},{name:"items",type:"Array"},{name:"recentItems",type:"Array"},{name:"searchDialog",type:"String","default":"default"}],superclass:AdfUIInputPopup});
AdfRichUIPeer.createPeerClass(AdfDhtmlInputListOfValuesBasePeer,"AdfDhtmlInputComboboxListOfValuesPeer");
AdfDhtmlInputComboboxListOfValuesPeer.InitSubclass=function(){AdfObject.ensureClassInitialization(AdfDhtmlInputListOfValuesBasePeer);AdfRichUIPeer.addComponentPropertyGetters(this,AdfRichInputComboboxListOfValues.LABEL);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.KEY_DOWN_EVENT_TYPE,AdfUIInputEvent.KEY_UP_EVENT_TYPE,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.MOUSE_DOWN_EVENT_TYPE,AdfUIInputEvent.BLUR_EVENT_TYPE,AdfActionEvent.ACTION_EVENT_TYPE,AdfDialogEvent.EVENT_TYPE,AdfPopupOpeningEvent.POPUP_OPENING_EVENT_TYPE);
this._POPUP_SUFFIX_ID="_afrDropDownPopup";this._POPUP_SEARCH_SUFFIX_ID="_afrPopupSearch";this._CONTAINER_DIALOG_SUBID="cntnr";this._DROPDOWN_CONTENT_SUFFIX_ID="_afrDropDownContent";this._DROPDOWN_ICON_ID="lovIconId";this._DEPRESSED_STYLE_CLASS="p_AFDepressed";this._MRU_ROW_SEPARATOR="_afrSeparator";this._LOVINTERNAL_EVENT_QUEUED="_afrLovInternalEventQueued";this._CONTENT_DELIVERY_LAZY_UNCACHED="lazyUncached";this._EDIT_MODE_SELECT="select";this._AUTOCOMPLETE_ANNOUNCE_MSG="af_inputComboboxListOfValues.AUTOCOMPLETE_ANNOUNCE_MSG"};
AdfDhtmlInputComboboxListOfValuesPeer.prototype.AnnounceAutoComplete=function(){var a=this.getComponent(),b=AdfPage.PAGE;b.announceToAssistiveTechnology(b.getLookAndFeel().getTranslatedString(AdfDhtmlInputComboboxListOfValuesPeer._AUTOCOMPLETE_ANNOUNCE_MSG,AdfDhtmlInputListOfValuesSuperBasePeer.GetLabelText(a),a.getValue()))};AdfDhtmlInputComboboxListOfValuesPeer.prototype.FocusNextElement=function(a){AdfFocusUtils.focusNextTabStop(a)};
AdfDhtmlInputComboboxListOfValuesPeer.prototype.IsCancelBackSpaceKeyEvent=function(a,b){return this.IsKeyEventInInput(a,b)||this._isInDropdownTable(a,b)||AdfDhtmlInputComboboxListOfValuesPeer._isEventTargetSearchLink(a,b)};AdfDhtmlInputComboboxListOfValuesPeer.prototype.VetoShowNoteWindow=function(a){var b=a.getClientId();return this.IsLovPopupVisible(b)||AdfDhtmlInputComboboxListOfValuesPeer._getDropdownPopup(a).isPopupVisible()?!0:AdfDhtmlInputComboboxListOfValuesPeer.superclass.VetoShowNoteWindow.call(this)};
AdfDhtmlInputComboboxListOfValuesPeer.prototype.HandleComponentAction=function(a){var b=this.getComponent();AdfDhtmlInputComboboxListOfValuesPeer._getDropdownPopup(b).hide();AdfDhtmlInputComboboxListOfValuesPeer._isEventTargetSearchLink(b,a)&&(a.cancel(),AdfLaunchPopupEvent.queue(b,!0))};
AdfDhtmlInputComboboxListOfValuesPeer.prototype.HandleComponentBlur=function(a){var b=this.getComponent();b.getProperty(AdfDhtmlInputComboboxListOfValuesPeer._LOVINTERNAL_EVENT_QUEUED)&&b.setProperty(AdfDhtmlInputComboboxListOfValuesPeer._LOVINTERNAL_EVENT_QUEUED,!1,!1,AdfUIComponent.PROPAGATE_NEVER);AdfDhtmlInputComboboxListOfValuesPeer.superclass.HandleComponentBlur.call(this,a)};
AdfDhtmlInputComboboxListOfValuesPeer.prototype.HandleComponentClick=function(a){AdfDhtmlInputComboboxListOfValuesPeer.superclass.HandleComponentClick.call(this,a);var b=this.getComponent();if(a.isLeftButtonPressed()&&!b.getDisabled()){var d=a.getNativeEventTarget(),e=this._getDropdownElement(b);d==e||d.parentNode==e?AdfDhtmlInputComboboxListOfValuesPeer._showDropdown(b):this._isInDropdownTable(b,a)&&this._handleDropdownTableClick(b,a)}};
AdfDhtmlInputComboboxListOfValuesPeer.prototype.HandleComponentClickOrTouch=function(a){var b=this.getComponent();b.getDisabled()||(a=a.getNativeEventTarget(),b.getEditMode()==AdfDhtmlInputComboboxListOfValuesPeer._EDIT_MODE_SELECT&&a==AdfDhtmlEditableValuePeer.getContentNode(b)&&AdfDhtmlInputComboboxListOfValuesPeer._showDropdown(b))};
AdfDhtmlInputComboboxListOfValuesPeer.prototype.HandleComponentKeyDown=function(a){AdfDhtmlInputComboboxListOfValuesPeer.superclass.HandleComponentKeyDown.call(this,a);if(!a.isCanceled()){var b=a.getKeyCode(),d=this.getComponent();switch(b){case AdfKeyStroke.TAB_KEY:case AdfKeyStroke.ENTER_KEY:this.IsKeyEventInInput(d,a)&&AdfDhtmlInputComboboxListOfValuesPeer._getDropdownPopup(d).hide();break;case AdfKeyStroke.ARROWDOWN_KEY:b=a.getNativeEvent(),d!=a.getSource()||d.getDisabled()||(!b.altKey||b.ctrlKey||
b.shiftKey)&&window.AdfAutoSuggestBehavior&&AdfAutoSuggestBehaviorImpl.isPopupVisible(d,this)||(AdfDhtmlInputComboboxListOfValuesPeer._showDropdown(d),this.preventNextValueSubmission(),a.cancel())}}};
AdfDhtmlInputComboboxListOfValuesPeer.prototype.HandleComponentKeyUp=function(a){AdfDhtmlInputComboboxListOfValuesPeer.superclass.HandleComponentKeyUp.call(this,a);if(!a.isCanceled()){var b=a.getKeyCode();if(b==AdfKeyStroke.SPACE_KEY||b==AdfKeyStroke.ENTER_KEY){var d=this.getComponent();!this.IsKeyEventInInput(d,a)&&AdfDhtmlInputComboboxListOfValuesPeer._getDropdownPopup(d).isPopupVisible()&&(this._returnTableSelection(d,a),b==AdfKeyStroke.ENTER_KEY&&(a.cancel(),a.stopBubbling()))}}};
AdfDhtmlInputComboboxListOfValuesPeer.prototype.HandleComponentMouseDown=function(a){var b=this.getComponent();b.getDisabled()||(a=a.getNativeEventTarget(),b=this._getDropdownElement(b),a!=b&&a.parentNode!=b||this.preventNextValueSubmission())};
AdfDhtmlInputComboboxListOfValuesPeer.prototype.HandleComponentPopupOpening=function(a){AdfDhtmlInputComboboxListOfValuesPeer.superclass.HandleComponentPopupOpening.call(this,a);var b=this.getComponent(),d=b.getClientId();a.getSource()==AdfDhtmlInputComboboxListOfValuesPeer._getDropdownPopup(b)&&(this.HideNoteWindow(),b=this._getDropdownElement(b).parentNode,AdfDomUtils.addCSSClassName(b,AdfDhtmlInputComboboxListOfValuesPeer._DEPRESSED_STYLE_CLASS),a=a.getHints(),AdfAgent.AGENT.getPlatform()==AdfAgent.IE_PLATFORM&&
AdfPage.PAGE.getLocaleContext().isRightToLeft()||(a[AdfRichPopup.HINT_ALIGN_ID]=AdfRichUIPeer.createSubId(d,AdfDhtmlInputComboboxListOfValuesPeer._CONTAINER_DIALOG_SUBID)),a[AdfDhtmlPopupHints.CLOSE_ON_ESCAPE]=!0,a[AdfDhtmlPopupHints.FOCUS]=!0,a[AdfRichPopup.HINT_LAUNCH_ID]=d,a[AdfDhtmlPopupHints.TYPE]=AdfDhtmlPopupHints.TYPE_LOVCOMBOBOX,a[AdfDhtmlPopupHints.CLOSE_HANDLER]=this.createCallback(this._clearDepressed))};
AdfDhtmlInputComboboxListOfValuesPeer._createPopupSubId=function(a){return a.getClientId()+AdfDhtmlInputComboboxListOfValuesPeer._POPUP_SUFFIX_ID};AdfDhtmlInputComboboxListOfValuesPeer._getDropdownPopup=function(a){a=AdfDhtmlInputComboboxListOfValuesPeer._createPopupSubId(a);a=AdfPage.PAGE.findComponent(a);AdfAssert.assertObject(a);return a};AdfDhtmlInputComboboxListOfValuesPeer._getDropdownTable=function(a){a=a.getClientId()+AdfDhtmlInputComboboxListOfValuesPeer._DROPDOWN_CONTENT_SUFFIX_ID;return AdfPage.PAGE.findComponent(a)};
AdfDhtmlInputComboboxListOfValuesPeer._getSelectedRowKeys=function(a){if(a=AdfDhtmlInputComboboxListOfValuesPeer._getDropdownTable(a)){a=a.getSelectedRowKeys();var b=[],d;for(d in a)b.push(d);return b}};AdfDhtmlInputComboboxListOfValuesPeer._isEventTargetSearchLink=function(a,b){var d=a.getClientId()+AdfDhtmlInputComboboxListOfValuesPeer._POPUP_SEARCH_SUFFIX_ID;return b.getSource().getClientId()==d};
AdfDhtmlInputComboboxListOfValuesPeer._isEventTargetSeparator=function(a){var b=AdfAgent.AGENT;a=a.getNativeEvent();a=b.getEventTarget(a);"TR"==a.tagName&&(a=AdfDomUtils.getFirstChildElement(a));return b.getAttribute(a,AdfDhtmlInputComboboxListOfValuesPeer._MRU_ROW_SEPARATOR)};
AdfDhtmlInputComboboxListOfValuesPeer._showDropdown=function(a){var b=a.getClientId(),d=AdfDhtmlInputComboboxListOfValuesPeer._getDropdownPopup(a),e=d.getContentDelivery();d.isPopupVisible()?d.hide():e==AdfDhtmlInputComboboxListOfValuesPeer._CONTENT_DELIVERY_LAZY_UNCACHED?AdfLovInternalEvent.queue(a,AdfLovInternalEvent.ACTION_CLICK,!0):(e={},e[AdfRichPopup.HINT_ALIGN_ID]=AdfDhtmlEditableValuePeer.GetContentNodeId(a),e[AdfRichPopup.HINT_ALIGN]=AdfRichPopup.ALIGN_AFTER_START,e[AdfRichPopup.HINT_LAUNCH_ID]=
b,d.show(e))};AdfDhtmlInputComboboxListOfValuesPeer.prototype._clearDepressed=function(){var a=this._getDropdownElement(this.getComponent()).parentNode;AdfDomUtils.removeCSSClassName(a,AdfDhtmlInputComboboxListOfValuesPeer._DEPRESSED_STYLE_CLASS)};AdfDhtmlInputComboboxListOfValuesPeer.prototype._getDropdownElement=function(a){a=AdfRichUIPeer.createSubId(a.getClientId(),AdfDhtmlInputComboboxListOfValuesPeer._DROPDOWN_ICON_ID);return AdfAgent.AGENT.getElementById(a)};
AdfDhtmlInputComboboxListOfValuesPeer.prototype._handleDropdownTableClick=function(a,b){this._returnTableSelection(a,b);AdfDhtmlInputListOfValuesSuperBasePeer.FocusInputElement(a)};AdfDhtmlInputComboboxListOfValuesPeer.prototype._isInDropdownTable=function(a,b){var d=b.getNativeEventTarget(),e=AdfDhtmlInputComboboxListOfValuesPeer._getDropdownTable(a);return e?AdfDomUtils.isAncestorOrSelf(e.getPeer().getDomElement(),d):!1};
AdfDhtmlInputComboboxListOfValuesPeer.prototype._returnTableSelection=function(a,b){if(!AdfDhtmlInputComboboxListOfValuesPeer._isEventTargetSeparator(b)){var d=AdfDhtmlInputComboboxListOfValuesPeer._getSelectedRowKeys(a);0!=d.length&&(AdfDhtmlInputComboboxListOfValuesPeer._getDropdownPopup(a).hide(),this.setMarkDirtyFlag(!0),AdfReturnPopupEvent.queue(a,d,!0))}};