AdfUIComponents.createComponentClass("AdfRichCommandNavigationItem",{componentType:"oracle.adf.RichCommandNavigationItem",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"useWindow",type:"Boolean","default":!1},{name:"windowModalityType",type:"String","default":"modeless"},{name:"windowEmbedStyle",type:"String","default":"window"},{name:"windowHeight",
type:"Number"},{name:"windowWidth",type:"Number"},{name:"iconDelivery",type:"String","default":"auto"},{name:"accessKey",type:"String"},{name:"destination",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"icon",type:"String"},{name:"messageType",type:"String","default":"none"},{name:"partialSubmit",type:"Boolean","default":!1,secured:!0},{name:"selected",type:"Boolean","default":!1},{name:"showRequired",type:"Boolean","default":!1},{name:"targetFrame",type:"String"},
{name:"text",type:"String"},{name:"visited",type:"Boolean","default":!1},"itemListener",{name:"remove",type:"String","default":"inherit"}],eventNames:["item"],superclass:AdfUICommand});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlCommandNavigationItemPeer");
AdfDhtmlCommandNavigationItemPeer.InitSubclass=function(){AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.KEY_UP_EVENT_TYPE,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.FOCUS_EVENT_TYPE,AdfUIInputEvent.BLUR_EVENT_TYPE);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichCommandNavigationItem.TEXT);AdfRichUIPeer.addComponentPropertyGetters(this,AdfRichCommandNavigationItem.TEXT);AdfAgent.AGENT.isTouchFirstDevice()||AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_IN_EVENT_TYPE);
this._TAB_ANCHOR_ID="disclosureAnchor";this._REMOVE_ICON_ID="rmAbv";this._HIGHLIGHTED_STYLE_CLASS="p_AFHighlighted"};AdfDhtmlCommandNavigationItemPeer.prototype.InitDomElement=function(a,b){AdfDhtmlCommandNavigationItemPeer.superclass.InitDomElement.call(this,a,b)};
AdfDhtmlCommandNavigationItemPeer.prototype.HandleComponentKeyUp=function(a){var b=a.getNativeEvent(),d=a.getKeyCode();b.ctrlKey&&b.altKey&&d==AdfKeyStroke.F4_KEY&&(b=this.getComponent(),!b.getDisabled()&&this.canRemove()&&(this._saveAndRemoveCompressedLayout(),a=a.getNativeEventTarget(),AdfFocusUtils.focusNextTabStop(a,null,!0),AdfItemEvent.queueItemRemoveEvent(b)))};
AdfDhtmlCommandNavigationItemPeer.prototype.HandleComponentClick=function(a){var b=this.getComponent();if(a.getSource()==b)if(this._isDisabled())a.stopBubbling();else if(a.isLeftButtonPressed())if(this._isOnRemoveButton(a)){if(this.canRemove()){this._saveAndRemoveCompressedLayout();var d=a.getNativeEventTarget();AdfFocusUtils.focusNextTabStop(d,null,!0);AdfItemEvent.queueItemRemoveEvent(b)}}else{var e=AdfRichUIPeer.getDomElementForComponent(b),d=e.href;void 0==d&&(d=e.getAttribute("href"));var f=
AdfAgent.AGENT.getDomDocument().location.href,g=f.indexOf("#"),f=-1==g?f:f.substring(0,g);d&&(-1==d.indexOf(f)||1<d.substring(d.indexOf("#")).length)?(AdfPage.PAGE.__perfTimings(!0,!0,!0,"User click Command Navigation , GET request"),d=e.getAttribute("target"),AdfPage.PAGE.__handleNavigation(e.attributes.href.value,d),a.cancel()):(this._saveAndRemoveCompressedLayout(),AdfActionEvent.queue(b,b.getPartialSubmit()))}};
AdfDhtmlCommandNavigationItemPeer.prototype.HandleComponentFocus=function(a){this._isDisabled()?a.stopBubbling():this._handleTabFocusOrBlur(a,!0)};AdfDhtmlCommandNavigationItemPeer.prototype.HandleComponentBlur=function(a){this._handleTabFocusOrBlur(a,!1)};
AdfDhtmlCommandNavigationItemPeer.prototype._handleTabFocusOrBlur=function(a,b){a.cancel();var d=a.getNativeEventTarget().id;null!=d&&(d=d.split("::"),1>=d.length||d[d.length-1]!=AdfDhtmlCommandNavigationItemPeer._TAB_ANCHOR_ID||(d=this.getDomElement(),b?AdfDomUtils.addCSSClassName(d,AdfDhtmlCommandNavigationItemPeer._HIGHLIGHTED_STYLE_CLASS):AdfDomUtils.removeCSSClassName(d,AdfDhtmlCommandNavigationItemPeer._HIGHLIGHTED_STYLE_CLASS)))};
AdfDhtmlCommandNavigationItemPeer.prototype.HandleComponentMouseOver=function(a){this._isDisabled()&&a.stopBubbling()};AdfDhtmlCommandNavigationItemPeer.prototype.GetInlineEditor=function(a){return AdfDhtmlNavigationItemTextEditor.getInlineEditor()};AdfDhtmlCommandNavigationItemPeer.prototype.ComponentTextChanged=function(a,b,d,e){return null!=e&&(b=AdfDhtmlCommandNavigationItemPeer.getInlineEditableTextElement(a,b))?AdfDomUtils.handleTextChangeWithAccessKey(a,b,d):!1};
AdfDhtmlCommandNavigationItemPeer.getInlineEditableTextElement=function(a,b){AdfAssert.assert(null!=a.getProperty("text"));var d=AdfDomUtils.getFirstDescendentElement(b,"a");d||"a"==AdfAgent.AGENT.getNodeName(b).toLowerCase()&&(d=b);if(d)if(AdfDomUtils.getFirstDescendentElement(d,"img")){if(d=AdfDomUtils.getLastChildElement(d),"SPAN"==d.tagName)return d}else return d;return null};
AdfDhtmlCommandNavigationItemPeer.prototype._isOnRemoveButton=function(a){var b=this.getComponent().getClientId(),b=AdfRichUIPeer.createSubId(b,AdfDhtmlCommandNavigationItemPeer._REMOVE_ICON_ID);a=a.getNativeEventTarget();return a.id==b?!0:a.parentNode.id==b};
AdfDhtmlCommandNavigationItemPeer.prototype.canRemove=function(){var a=this.getComponent();if(a.getRemove){var b=a.getRemove();if(b&&("no"==b||"disabled"==b))return!1}b=a.getParent();if(null==b.getItemRemoval)return!1;b=b.getItemRemoval();if(a.getDisabled()||null==b||"none"==b)return!1;if("all"==b)return!0;if("allExceptLast"==b)return a=a.getClientId(),a=AdfRichUIPeer.createSubId(a,AdfDhtmlCommandNavigationItemPeer._REMOVE_ICON_ID),null!=AdfAgent.getAgent().getElementById(a)};
AdfDhtmlCommandNavigationItemPeer.prototype._saveAndRemoveCompressedLayout=function(){var a=this.getComponent().getParent(),b=null!=a?a.getPeer():null;b&&(b.bind(a),b&&b.__saveAndRemoveCompressedLayout&&b.__saveAndRemoveCompressedLayout())};AdfDhtmlCommandNavigationItemPeer.prototype._isDisabled=function(){var a=this.getDomElement();return a.disabled||AdfDomUtils.containsCSSClassName(a,AdfRichUIPeer.DISABLED_STYLECLASS)};
AdfDhtmlCommandNavigationItemPeer.prototype.GetComponentText=function(a,b){"A"!=b.tagName&&(b=AdfDomUtils.getFirstDescendentElement(b,"a"));if(b){var d=AdfAgent.AGENT.getTextContent(b);return""==d?null:d}AdfAssert.assert(!1,"Unable to find the element containing the text")};AdfDhtmlCommandNavigationItemPeer.prototype.GetAccessibleName=function(){return this.getComponent().getText()};
AdfUIComponents.createComponentClass("AdfUINavigationPath",{componentType:"org.apache.myfaces.trinidad.NavigationPath",propertyKeys:["value"],namingContainer:!0,superclass:AdfUICollection});
AdfUIComponents.createComponentClass("AdfRichBreadCrumbs",{componentType:"oracle.adf.RichBreadCrumbs",propertyKeys:[{name:"orientation",type:"String","default":"horizontal"},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0}],namingContainer:!0,superclass:AdfUINavigationPath});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlBreadCrumbsPeer",!1);AdfDhtmlBreadCrumbsPeer.prototype.InitDomElement=function(a,b){AdfDhtmlBreadCrumbsPeer.superclass.InitDomElement.call(this,a,b);var d=a.getClientId(),d=AdfRichUIPeer.CreateSubId(d,"oc");this._overflowContents=AdfAgent.AGENT.getElementById(d);AdfPage.PAGE.__registerDescendantResizeNotifyComponent(a)};AdfDhtmlBreadCrumbsPeer.prototype.needsResizeNotify=function(a){return!0};
AdfDhtmlBreadCrumbsPeer.prototype.ResizeNotify=function(a,b,d,e){a=this.getComponent();this.getDomElement();if(!this._overflowSupport){a=a.getClientId();if(!AdfOverflowSupport.needsOverflow(a))return;this._overflowSupport=new AdfOverflowSupport(a,this,"start","before");a=this._overflowContents.childNodes;for(b=0;d=a[b++];)1==d.nodeType&&("a"==d.tagName.toLowerCase()||0<d.getElementsByTagName("a").length?(this._overflowSupport.createStep(),d=this._createOverflowElement(d),b++,this._overflowSupport.addOverflowElement(d)):
(this._overflowSupport.createStep(),this._overflowSupport.addElement(d)))}this._overflowSupport.handleResize()};AdfDhtmlBreadCrumbsPeer.prototype.ComponentRemoved=function(a){this._overflowSupport&&(this._overflowSupport.removeOverflowSupport(),delete this._overflowSupport);delete this._overflowContents;AdfPage.PAGE.__unregisterDescendantResizeNotifyComponent(a);AdfDhtmlBreadCrumbsPeer.superclass.ComponentRemoved.call(this,a)};
AdfDhtmlBreadCrumbsPeer.prototype._createOverflowElement=function(a){var b=a.ownerDocument.createElement("div"),d=AdfDhtmlBreadCrumbsPeer._overflowElementStyleClass;null==d&&(d=AdfPage.PAGE.getLookAndFeel().getStyleClass("AFOverflowElement"),AdfDhtmlBreadCrumbsPeer._overflowElementStyleClass=d);b.className=d;a=this._overflowSupport.createSwapPosition(a);b.appendChild(a);return b};
AdfDhtmlBreadCrumbsPeer.prototype.ConvertClientIdToLocator=function(a,b,d,e){a=a.getClientId();AdfAssert.assert(0<=d.indexOf(a));d=d.substring(a.length+1);b=d.indexOf(":");0<b&&(d=d.substring(0,b),a=AdfStrings.count(a,":"),e.push([a+1,d]))};
AdfDhtmlBreadCrumbsPeer.prototype.convertLocatorToClientId=function(a,b){var d=a.getClientId(),e=AdfRichUIPeer.CreateSubId(d,"oc");if(e=AdfAgent.AGENT.getElementById(e).getElementsByTagName("a")[b]){e=e.id;if(0<e.substring(d.length+1).indexOf(":"))return e;AdfAssert.assert(!1,"Use of [] locator notation is only supported when breadCrumbs: "+d+" is used with MenuModel")}return null};
AdfUIComponents.createComponentClass("AdfUINavigationLevel",{componentType:"org.apache.myfaces.trinidad.NavigationLevel",propertyKeys:["value",{name:"level",type:"Number","default":0,secured:!0}],namingContainer:!0,superclass:AdfUICollection});
AdfUIComponents.createComponentClass("AdfRichNavigationPane",{componentType:"oracle.adf.RichNavigationPane",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"hint",type:"String","default":"tabs"},{name:"maxTabSize",type:"String","default":"infinity"},{name:"minTabSize",type:"String",
"default":"0px"},{name:"truncationStyle",type:"String","default":"none"},{name:"title",type:"String"},{name:"itemRemoval",type:"String","default":"none"}],eventNames:["item"],namingContainer:!0,superclass:AdfUINavigationLevel});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlNavigationPanePeer",!1);
AdfDhtmlNavigationPanePeer.InitSubclass=function(){AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.KEY_UP_EVENT_TYPE,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.KEY_DOWN_EVENT_TYPE,AdfUIInputEvent.MOUSE_DOWN_EVENT_TYPE);AdfAgent.AGENT.isTouchFirstDevice()||AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_IN_EVENT_TYPE);this._CHOICE_BUTTON_ID="_afrChoiceButton";this._CHOICE_DATA_CONTAINER_ID="_afrChoiceDataContainer";this._POPUP_ID="popupContent";this._POPUP_PANEL_ID=
"_afrChoicePopupPanel";this._POPUP_CLOSED_TIME="_afrPopupClosedTime";this._TAB_HEADER="tabh";this._TAB_HINT="tabs";this._BAR_HINT="bar";this._ANCHOR_SUB_ID="disclosureAnchor";this._TAB_ID_CONVEYOR_SUFFIX="Cnvr";AdfDhtmlNavigationPanePeer._SELECTED_STYLECLASS="p_AFSelected";this._ELLIPSIS_SUBID="_afrEps";this._TAB_CONTENT="_afrTabCnt";this._TAB_CONTENT_DIV="_afrTabDiv";var a=AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|navigationPane-tr-layout-type");this._compressedLayoutMode="overflow"==a?"overflow":
"overflow-droplist"==a?"overflow-droplist":"conveyorBelt"};
AdfDhtmlNavigationPanePeer.prototype.InitDomElement=function(a,b){AdfDhtmlNavigationPanePeer.superclass.InitDomElement.call(this,a,b);var d=a.getClientId(),e=AdfAgent.getAgent();this._stretchedOnLastResize=!0;if(a.getHint()==AdfDhtmlNavigationPanePeer._TAB_HINT){if(d=AdfRichUIPeer.CreateSubId(d,AdfDhtmlNavigationPanePeer._TAB_HEADER),this._headerDiv=e.getElementById(d))d="conveyorBelt"==AdfDhtmlNavigationPanePeer._compressedLayoutMode?AdfRichUIPeer.CreateSubId(d,"cbc"):AdfRichUIPeer.CreateSubId(d,
"oc"),this._headerContentDiv=e.getElementById(d),AdfPage.PAGE.__registerDescendantResizeNotifyComponent(a)}else a.getHint()==AdfDhtmlNavigationPanePeer._BAR_HINT&&(d=AdfRichUIPeer.CreateSubId(d,"oc"),this._barOverflowContent=e.getElementById(d),AdfPage.PAGE.__registerDescendantResizeNotifyComponent(a))};AdfDhtmlNavigationPanePeer.prototype.needsResizeNotify=function(a){return this._headerDiv||a.getHint()==AdfDhtmlNavigationPanePeer._BAR_HINT?!0:!1};
AdfDhtmlNavigationPanePeer.prototype.ResizeNotify=function(a,b,d,e){b=this.getComponent();if(this._headerContentDiv)a!=d&&("ellipsis"==this.getComponent().getTruncationStyle()?this._resizeTabHeader(a,d):this._updateOverflow(d));else if(this._barOverflowContent){if(!this._overflowSupport){a=b.getClientId();if(!AdfOverflowSupport.needsOverflow(a))return;this._overflowSupport=new AdfOverflowSupport(a,this,"both");a=this._barOverflowContent.childNodes;d=this._getActiveChildIndex(a);for(b=-1;e=a[++b];)1==
e.nodeType&&("a"==e.tagName.toLowerCase()||0<e.getElementsByTagName("a").length)&&(-1==d&&(d=b),this._overflowSupport.createStep(),d==b?this._overflowSupport.addElement(e):b>d?(this._addSeparators(a,b,!0),this._overflowSupport.addElement(e)):(this._overflowSupport.addElement(e),this._addSeparators(a,b,!1)),e=this._createBarOverflowElement(e),this._overflowSupport.addOverflowElement(e))}this._overflowSupport.handleResize()}};
AdfDhtmlNavigationPanePeer.prototype._updateOverflow=function(a){var b=this._getChildElements(this._headerDiv.id,this._headerContentDiv);0!=b.length&&this._resizeOverflow(this._headerDiv.id,b,a)};AdfDhtmlNavigationPanePeer.prototype._resizeTabHeader=function(a,b){var d=this._getChildElements(this._headerDiv.id,this._headerContentDiv);0!=d.length&&this._layoutTabs(a,this._headerDiv.offsetWidth,this._headerDiv.id,d)};
AdfDhtmlNavigationPanePeer.prototype._layoutTabs=function(a,b,d,e,f){a=e.length;var g=this.getComponent();this._maxTabSize||(this._maxTabSize=g.getMaxTabSize(),this._maxTabSize=null==this._maxTabSize||"infinity"==this._maxTabSize?0:parseFloat(this._maxTabSize));this._minTabSize||(this._minTabSize=g.getMinTabSize(),this._minTabSize=parseFloat(this._minTabSize),null==this._minTabSize&&(this._minTabSize=32));if(0<this._maxTabSize&&this._minTabSize>this._maxTabSize)AdfLogger.LOGGER.warning("Minimum tab width should not be greater than maximum tab width: min\x3d"+
this._minTabSize+", max\x3d "+this._maxTabSize);else{if(!this._overflowLimit){this._overflowLimit=this._minTabSize*a;!this._tabOverlapWidth&&1<a&&(this._tabOverlapWidth=e[0].offsetWidth-(e[1].offsetLeft-e[0].offsetLeft));for(g=0;g<a;g++){var h=e[g];tabContentElement=this._getTabContentElement(h);this._getEllipsisElement(h).style.display="none";this._overflowLimit+=h.offsetWidth-tabContentElement.offsetWidth-this._tabOverlapWidth}this._tabOverlapWidth&&(this._overflowLimit+=this._tabOverlapWidth)}b<
this._overflowLimit?(this._setTabSizes(e,this._minTabSize),this._resizeOverflow(d,e,b,f)):(b=Math.floor((b-this._tabOverlapWidth)/a),this._hideOverflow(),this._setTabSizes(e,b,!0))}};
AdfDhtmlNavigationPanePeer.prototype._setTabSizes=function(a,b,d){for(var e=!1,f=0;f<a.length;f++){var g=a[f];tabContentElement=this._getTabContentElement(g);var h=this._getEllipsisElement(g),k=tabContentElement.style.width;tabContentElement.style.width="";tabContentElement.style.overflow="";h.style.display="none";g=g.offsetWidth;g=d?b-(g-tabContentElement.offsetWidth)+this._tabOverlapWidth:b;0<this._maxTabSize&&g>this._maxTabSize&&(g=this._maxTabSize);tabContentElement.offsetWidth>g&&(h.style.display=
"inline",tabContentElement.style.overflow="hidden",g-=h.offsetWidth);tabContentElement.style.width=g+"px";e||k==tabContentElement.style.width||(e=!0)}return e};AdfDhtmlNavigationPanePeer.prototype._hideOverflow=function(){"conveyorBelt"==AdfDhtmlNavigationPanePeer._compressedLayoutMode?this._conveyorBeltSupport&&this._conveyorBeltSupport.handleResize():this._overflowSupport&&this._overflowSupport.removeAllItemsFromOverflow()};
AdfDhtmlNavigationPanePeer.prototype._resizeOverflow=function(a,b,d){var e=AdfDhtmlNavigationPanePeer._compressedLayoutMode;"overflow"==e?(this._overflowSupport||(this._overflowSupport=this._getTabOverflowSupport(a,b,"after")),this._overflowSupport&&this._overflowSupport.handleResize()):"overflow-droplist"==e?(this._overflowSupport||(this._overflowSupport=this._getTabOverflowDroplistSupport(a,b,"after")),this._overflowSupport&&this._overflowSupport.handleResize()):"conveyorBelt"==e&&(this._conveyorBeltSupport||
(this._conveyorBeltSupport=this._getTabConveyorBeltSupport(a,b,d)),this._conveyorBeltSupport&&this._conveyorBeltSupport.handleResize())};AdfDhtmlNavigationPanePeer.prototype._getChildElements=function(a,b){for(var d=b.childNodes,e=[],f="conveyorBelt"==AdfDhtmlNavigationPanePeer._compressedLayoutMode,g=f?AdfRichUIPeer.CreateSubId(a,"cbs"):null,h=0;h<d.length;h++){var k=d[h];1!=k.nodeType||f&&k.getAttribute("id")==g||e.push(k)}return e};
AdfDhtmlNavigationPanePeer.prototype._resizeTabsWithCompressedLayout=function(a,b,d,e,f,g){null==a&&(a=b);b>a?(d.handleResize(),f&&this._readjustTabs(b,e)):d.handleResize();AdfDomUtils.setScrollTop(g,0)};AdfDhtmlNavigationPanePeer.prototype.__saveAndRemoveCompressedLayout=function(){var a=this._conveyorBeltSupport;a&&(AdfDhtmlNavigationPanePeer._conveyorBeltFirstItem=a.getFirstItemDisplayed());this._removeCompressedLayoutSupport()};
AdfDhtmlNavigationPanePeer.prototype._getTabOverflowSupport=function(a,b){for(var d=new AdfOverflowSupport(a,this,"both"),e=0;e<b.length;e++){var f=b[e];1==f.nodeType&&(d.createStep(),d.addElement(f),"none"!=f.style.display&&d.addOverflowElement(this._createTabCompressedLayoutPopupElement(f)))}return d};
AdfDhtmlNavigationPanePeer.prototype._getTabOverflowDroplistSupport=function(a,b){for(var d=new AdfOverflowSupport(a,this,"droplist"),e=[],f=0;f<b.length;f++){var g=b[f];1==g.nodeType&&(d.createStep(),d.addElement(g),"none"!=g.style.display&&(d.addOverflowElement(this._createTabCompressedLayoutPopupElement(g)),e.push(this._createTabCompressedLayoutPopupElement(g))))}d.addDropListElements(e);return d};
AdfDhtmlNavigationPanePeer.prototype._getTabConveyorBeltSupport=function(a,b){for(var d=AdfConveyorBeltSupport.createHorizontalSupport(a,this),e=[],f=AdfRichUIPeer.CreateSubId(a,"cbs"),g=0;g<b.length;g++){var h=b[g];1==h.nodeType&&h.getAttribute("id")!=f&&"none"!=h.style.display&&e.push(this._createTabCompressedLayoutPopupElement(h))}d.addDropListElements(e);if(e=AdfDhtmlNavigationPanePeer._conveyorBeltFirstItem)d.setFirstItemDisplayed(e),AdfDhtmlNavigationPanePeer._conveyorBeltFirstItem=null;return d};
AdfDhtmlNavigationPanePeer.prototype.ComponentRemoved=function(a){this._removeCompressedLayoutSupport();this._headerDiv?(delete this._headerDiv,delete this._headerContentDiv):this._barOverflowContent&&delete this._barOverflowContent;AdfPage.PAGE.__unregisterDescendantResizeNotifyComponent(a);AdfDhtmlNavigationPanePeer.superclass.ComponentRemoved.call(this,a)};
AdfDhtmlNavigationPanePeer.prototype._removeCompressedLayoutSupport=function(){this._overflowSupport&&(this._overflowSupport.removeOverflowSupport(),this._overflowSupport=null);this._conveyorBeltSupport&&(this._conveyorBeltSupport.removeConveyorBeltSupport(),this._conveyorBeltSupport=null)};AdfDhtmlNavigationPanePeer.prototype.HandleComponentClick=function(a){a.cancel();return!1};
AdfDhtmlNavigationPanePeer.prototype.HandleComponentKeyUp=function(a){var b=this.getComponent(),d=a.getNativeEvent(),e=AdfAgent.AGENT.getEventTarget(d),f=AdfAgent.AGENT.getKeyCode(d);if(this.isPopupVisible(b,AdfDhtmlNavigationPanePeer._POPUP_PANEL_ID)){var g=!1,h=this._getPopupContentDom(b);switch(f){case AdfKeyStroke.ESC_KEY:g=this._getChoiceDropDownElement(b);AdfFocusUtils.focusElement(g);g=AdfRichUIPeer.CreateSubId(b.getClientId(),AdfDhtmlNavigationPanePeer._CHOICE_BUTTON_ID);AdfPage.PAGE.getDocument().getElementById(g).setAttribute("aria-expanded",
"false");g=!0;break;case AdfKeyStroke.ARROWDOWN_KEY:AdfFocusUtils.focusNextTabStop(e,h);cancelEvt=!0;break;case AdfKeyStroke.ARROWUP_KEY:AdfFocusUtils.focusPreviousTabStop(e,h)}g&&this.hidePopup(b,AdfDhtmlNavigationPanePeer._POPUP_PANEL_ID)}else e==this._getChoiceDropDownElement(b)&&f==AdfKeyStroke.ARROWDOWN_KEY&&this._showChoicePopupPanel(b);a.isCanceled()||(f==AdfKeyStroke.ARROWUP_KEY||f==AdfKeyStroke.ARROWLEFT_KEY?this._isTabLink(e)&&((b=AdfFocusUtils.getPreviousFocusableDescendant(this.getDomElement(),
e))||(b=AdfFocusUtils.getLastFocusableDescendant(this.getDomElement())),b&&(b.focus(),a.cancel())):f!=AdfKeyStroke.ARROWDOWN_KEY&&f!=AdfKeyStroke.ARROWRIGHT_KEY||!this._isTabLink(e)||((b=AdfFocusUtils.getNextFocusableDescendant(this.getDomElement(),e))||(b=AdfFocusUtils.getFirstFocusableDescendant(this.getDomElement())),b&&(b.focus(),a.cancel())),d.ctrlKey&&d.altKey&&87==f||a.cancel())};
AdfDhtmlNavigationPanePeer.prototype._isTabLink=function(a){if(null==a)return!1;a=a.id;if(null==a)return!1;a=a.split("::");return 1>=a.length||a[a.length-1]!=AdfDhtmlNavigationPanePeer._ANCHOR_SUB_ID?!1:!0};
AdfDhtmlNavigationPanePeer.prototype.HandleComponentMouseDown=function(a){var b=a.getNativeEvent();a=a.getSource();var b=AdfAgent.AGENT.getEventTarget(b),d=this._getChoiceDropDownElement(a);if(b==d||b.parentNode==d)this.isPopupVisible(a,AdfDhtmlNavigationPanePeer._POPUP_PANEL_ID)?(b=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlNavigationPanePeer._CHOICE_BUTTON_ID),d=AdfPage.PAGE.getDocument().getElementById(b),d.setAttribute("aria-expanded","false"),this.hidePopup(a,AdfDhtmlNavigationPanePeer._POPUP_PANEL_ID)):
this._showChoicePopupPanel(a)};AdfDhtmlNavigationPanePeer.prototype.HandleComponentMouseOver=function(a){if(this.isPopupVisible(this.getComponent(),AdfDhtmlNavigationPanePeer._POPUP_PANEL_ID)){var b=a.getNativeEventTarget();AdfFocusUtils.focusElement(b)}a.cancel()};AdfDhtmlNavigationPanePeer.prototype.HandleComponentKeyDown=function(a){var b=a.getNativeEvent(),b=AdfAgent.AGENT.getEventTarget(b),d=a.getSource();b==this._getChoiceDropDownElement(d)&&a.getKeyCode()==AdfKeyStroke.ENTER_KEY&&this._showChoicePopupPanel(d)};
AdfDhtmlNavigationPanePeer.prototype.GetPopupAlignmentNode=function(a,b){return this._getChoiceDropDownElement(a)};AdfDhtmlNavigationPanePeer.prototype.PopupClosed=function(a,b,d){d==AdfDhtmlNavigationPanePeer._POPUP_PANEL_ID&&(a=a.getClientId(),a=AdfRichUIPeer.CreateSubId(a,AdfDhtmlNavigationPanePeer._CHOICE_DATA_CONTAINER_ID),AdfAgent.AGENT.getElementById(a).appendChild(b))};
AdfDhtmlNavigationPanePeer.prototype._getChoiceDropDownElement=function(a){a=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlNavigationPanePeer._CHOICE_BUTTON_ID);return AdfAgent.AGENT.getElementById(a)};
AdfDhtmlNavigationPanePeer.prototype._showChoicePopupPanel=function(a){AdfObject.ensureClassInitialization(AdfRichPopup);var b=this._getPopupContentDom(a),d=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlNavigationPanePeer._CHOICE_BUTTON_ID);b.parentNode.removeChild(b);AdfPage.PAGE.getDocument().getElementById(d).setAttribute("aria-expanded","true");var e={};e[AdfDhtmlPopupHints.TYPE]=AdfDhtmlPopupHints.TYPE_MENU;e[AdfRichPopup.HINT_ALIGN]=AdfRichPopup.ALIGN_AFTER_START;e[AdfRichPopup.HINT_ALIGN_ID]=
d;e[AdfDhtmlPopupHints.AUTODISMISS]=AdfDhtmlPopupHints.AUTODISMISS_MENU;this.showPopup(a,b,e,AdfDhtmlNavigationPanePeer._POPUP_PANEL_ID)};AdfDhtmlNavigationPanePeer.prototype._getPopupContentDom=function(a){a=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlNavigationPanePeer._POPUP_ID);return AdfAgent.AGENT.getElementById(a)};
AdfDhtmlNavigationPanePeer.prototype._createTabCompressedLayoutPopupElement=function(a){var b=AdfAgent.AGENT,d=AdfPage.PAGE.getLookAndFeel(),e=a.getAttribute("id"),f,g=a.getElementsByTagName("a")[0],h=a.getElementsByTagName("a")[1],k=a.getElementsByTagName("img")[0];k&&(k=k.cloneNode(!0),k.id&&(k.id+=AdfDhtmlNavigationPanePeer._TAB_ID_CONVEYOR_SUFFIX));if(g&&-1==g.className.indexOf("p_AFDisabled")){g=g.cloneNode(!0);g.id&&(g.id+=AdfDhtmlNavigationPanePeer._TAB_ID_CONVEYOR_SUFFIX);f=AdfDhtmlNavigationPanePeer._tabCompressedLayoutElementStyleClass;
null==f&&(f="conveyorBelt"==AdfDhtmlNavigationPanePeer._compressedLayoutMode?d.getStyleClass("AFConveyorBeltElement"):d.getStyleClass("AFOverflowElement"),AdfDhtmlNavigationPanePeer._tabCompressedLayoutElementStyleClass=f);h&&(h=h.cloneNode(!0),h.id&&(h.id+=AdfDhtmlNavigationPanePeer._TAB_ID_CONVEYOR_SUFFIX),h.setAttribute("_componentId",e),d=this.createCallback(this._handleRemoveButtonClick),b.addBubbleEventListener(h,"click",d));var d=a.getAttribute("href"),l=b.getDomDocument().location.href;if(d&&
-1==d.indexOf(l)){if(g.setAttribute("_href",d),k&&k.setAttribute("_href",d),e=a.getAttribute("target"))g.setAttribute("_target",e),k&&k.setAttribute("_target",e)}else g.setAttribute("_componentId",e),k&&k.setAttribute("_componentId",e);e=this.createCallback(this._handleNavItemClick);b.addBubbleEventListener(g,"click",e);k&&b.addBubbleEventListener(k,"click",e)}else f=g.innerHTML,g=a.ownerDocument.createElement("div"),g.innerHTML=f,f=AdfDhtmlNavigationPanePeer._tabCompressedLayoutElementDisabledStyleClass,
null==f&&(f="conveyorBelt"==AdfDhtmlNavigationPanePeer._compressedLayoutMode?d.getStyleClass("AFConveyorBeltElementDisabled"):d.getStyleClass("AFOverflowElementDisabled"),AdfDhtmlNavigationPanePeer._tabCompressedLayoutElementDisabledStyleClass=f),h&&(h=h.cloneNode(!0),h.id&&(h.id+=AdfDhtmlNavigationPanePeer._TAB_ID_CONVEYOR_SUFFIX));b=a.ownerDocument.createElement("table");b.cellPadding=0;b.cellSpacing=0;b.style.width="100%";e=b.insertRow(-1);d=e.insertCell(-1);k&&d.appendChild(k);k=e.insertCell(-1);
k.style.width="100%";d=a.ownerDocument.createElement("div");d.className=f;k.appendChild(d);d.appendChild(g);g=e.insertCell(-1);h&&(a=a.ownerDocument.createElement("div"),a.className=f,g.appendChild(a),a.appendChild(h));return b};
AdfDhtmlNavigationPanePeer.prototype._createBarOverflowElement=function(a){var b=this.getComponent(),d=AdfDhtmlNavigationPanePeer._barOverflowElementStyleClass;null==d&&(d=AdfPage.PAGE.getLookAndFeel().getStyleClass("AFOverflowElement"),AdfDhtmlNavigationPanePeer._barOverflowElementStyleClass=d);var e=a.ownerDocument.createElement("div");e.className=d;d=a.cloneNode(!0);d.removeAttribute("id");e.appendChild(d);b=AdfPage.PAGE.findComponent(a.id);if(!b.getDisabled()){b=a.href;void 0==b&&(b=a.getAttribute("href"));
var f=AdfAgent.AGENT.getDomDocument().location.href;b&&-1==b.indexOf(f)?(d.setAttribute("_href",b),(a=a.getAttribute("target"))&&d.setAttribute("_target",a)):d.setAttribute("_componentId",a.getAttribute("id"));a=this.createCallback(this._handleNavItemClick);AdfAgent.AGENT.addBubbleEventListener(d,"click",a)}return e};
AdfDhtmlNavigationPanePeer.prototype._handleNavItemClick=function(a){this.hideAllPopups(this.getComponent());var b=AdfAgent.AGENT.getEventTarget(a);"A"!=b.nodeName&&"IMG"!=b.nodeName&&(b=b.parentNode);(a=b.getAttribute("_href"))?(b=b.getAttribute("_target"))?window.open(a,b):self.location=a:(this.__saveAndRemoveCompressedLayout(),a=b.getAttribute("_componentId"),a=AdfPage.PAGE.findComponent(a),AdfActionEvent.queue(a,a.getPartialSubmit()))};
AdfDhtmlNavigationPanePeer.prototype._handleRemoveButtonClick=function(a){a=AdfAgent.AGENT.getEventTarget(a);var b=a.getAttribute("_componentId");null==b&&(b=a.parentNode.getAttribute("_componentId"));a=AdfPage.PAGE.findComponent(b);b=a.getPeer();b.bind(a);b&&b.canRemove&&b.canRemove()&&(this.hideAllPopups(this.getComponent()),this.__saveAndRemoveCompressedLayout(),AdfItemEvent.queueItemRemoveEvent(a))};
AdfDhtmlNavigationPanePeer.prototype._addSeparators=function(a,b,d){var e=b+1;d&&(e=b-1);b=!0;for(var f=a[e];b&&f;){if(1==f.nodeType)if("img"==f.tagName.toLowerCase()||0<f.getElementsByTagName("img").length)this._overflowSupport.addElement(f),b=!1;else if("span"==f.tagName.toLowerCase()||0<f.getElementsByTagName("span").length)this._overflowSupport.addElement(f),b=!1;d?e--:e++;f=a[e]}};
AdfDhtmlNavigationPanePeer.prototype._getActiveChildIndex=function(a){for(var b=-1,d;d=a[++b];)if(AdfDomUtils.containsCSSClassName(d,"p_AFSelected"))return b;return-1};AdfDhtmlNavigationPanePeer.prototype._getTabContentElement=function(a){a=a.getAttribute("id");a=AdfRichUIPeer.CreateSubId(a,AdfDhtmlNavigationPanePeer._TAB_CONTENT);return AdfAgent.AGENT.getElementById(a)};
AdfDhtmlNavigationPanePeer.prototype._getTabTextElement=function(a){a=a.getAttribute("id");a=AdfRichUIPeer.CreateSubId(a,AdfDhtmlNavigationPanePeer._TAB_CONTENT_DIV);return AdfAgent.AGENT.getElementById(a)};AdfDhtmlNavigationPanePeer.prototype._getEllipsisElement=function(a){a=a.getAttribute("id");a=AdfRichUIPeer.CreateSubId(a,AdfDhtmlNavigationPanePeer._ELLIPSIS_SUBID);return AdfAgent.AGENT.getElementById(a)};
AdfDhtmlNavigationPanePeer.prototype.ConvertClientIdToLocator=function(a,b,d,e){a=a.getClientId();AdfAssert.assert(0<=d.indexOf(a));d=d.substring(a.length+1);b=d.indexOf(":");0<b&&(d=d.substring(0,b),a=AdfStrings.count(a,":"),e.push([a+1,d]))};
AdfDhtmlNavigationPanePeer.prototype.convertLocatorToClientId=function(a,b){var d=a.getDescendantComponents()[b];if(d){var e=a.getClientId(),d=d.getClientId();if(0<d.substring(e.length+1).indexOf(":"))return d;AdfAssert.assert(!1,"Use of [] locator notation is only supported when navigationPane: "+e+" is used with MenuModel")}return null};
function AdfConveyorBeltSupport(a,b){this.Init(a,b)}AdfObject.createSubclass(AdfConveyorBeltSupport);AdfConveyorBeltSupport.InitClass=function(){AdfConveyorBeltSupport.CONVEYOR_BELT_STYLE_CLASS="p_AFConveyorBelt";AdfConveyorBeltSupport.DEPRESSED_STYLE_CLASS="p_AFDepressed";AdfConveyorBeltSupport.SELECTED_STYLE_CLASS="p_AFSelected";AdfConveyorBeltSupport.DROPLIST_ID="_afrCbDl"};
AdfConveyorBeltSupport.prototype.Init=function(a,b){AdfConveyorBeltSupport.superclass.Init.call(this);this._peer=b;this._container=AdfAgent.AGENT.getElementById(a)};AdfConveyorBeltSupport.createHorizontalSupport=function(a,b){return new AdfConveyorBeltHorizontal(a,b)};AdfConveyorBeltSupport.createVerticalSupport=function(a,b,d){return new AdfConveyorBeltVertical(a,b,d)};AdfConveyorBeltSupport.prototype.removeConveyorBeltSupport=function(){delete this._peer;delete this._container};
AdfConveyorBeltSupport.prototype.registerAdditionalConveyorBeltSupport=function(a){AdfAssert.failedInAbstractFunction()};AdfConveyorBeltSupport.prototype.handleResize=function(){AdfAssert.failedInAbstractFunction()};AdfConveyorBeltSupport.prototype.addDropListElements=function(a){AdfAssert.failedInAbstractFunction()};AdfConveyorBeltSupport.prototype.scrollNewSelectedItemIntoView=function(a){AdfAssert.failedInAbstractFunction()};AdfConveyorBeltSupport.prototype.getFirstItemDisplayed=function(){AdfAssert.failedInAbstractFunction()};
AdfConveyorBeltSupport.prototype.setFirstItemDisplayed=function(a){AdfAssert.failedInAbstractFunction()};AdfConveyorBeltSupport.prototype.handleFocusChange=function(){AdfAssert.failedInAbstractFunction()};AdfConveyorBeltSupport.prototype.GetPeer=function(){return this._peer};AdfConveyorBeltSupport.prototype.GetContainer=function(){return this._container};
function AdfConveyorBeltHorizontal(a,b){this.Init(a,b)}AdfObject.createSubclass(AdfConveyorBeltHorizontal,AdfConveyorBeltSupport);
AdfConveyorBeltHorizontal.prototype.Init=function(a,b){AdfConveyorBeltHorizontal.superclass.Init.call(this,a,b);var d=AdfRichUIPeer.CreateSubId(a,"scbi");this._startIndicator=AdfAgent.AGENT.getElementById(d);this._initStartButtonEventHandling();d=AdfRichUIPeer.CreateSubId(a,"ecbi");this._endIndicator=AdfAgent.AGENT.getElementById(d);this._initEndButtonEventHandling();d=AdfRichUIPeer.CreateSubId(a,"cbc");this._contentContainer=AdfAgent.AGENT.getElementById(d);for(var e=AdfDomUtils.getChildElements(this._contentContainer),
d=[],f=AdfRichUIPeer.CreateSubId(a,"cbs"),g=0;g<e.length;g++){var h=e[g];1==h.nodeType&&h.getAttribute("id")!=f&&"none"!=h.style.display&&d.push(h)}e=AdfPage.PAGE.getLocaleContext().isRightToLeft();f=this._contentContainer.offsetWidth+this._contentContainer.offsetLeft;this._itemOffsetLeftArray=[];for(g=0;g<d.length;g++)this._itemOffsetLeftArray[g]=e?f-(d[g].offsetLeft+d[g].offsetWidth):d[g].offsetLeft,AdfDomUtils.containsCSSClassName(d[g],AdfConveyorBeltSupport.SELECTED_STYLE_CLASS)&&(this._selectedItem=
g);d=d[d.length-1];this._contentWidth=null==d?0:e?f-d.offsetLeft:d.offsetLeft+d.offsetWidth;this._initialRender=!0;this._firstItemDisplayed=0;d=AdfRichUIPeer.CreateSubId(a,"cbdli");this._droplistIndicator=AdfAgent.AGENT.getElementById(d);d=AdfRichUIPeer.CreateSubId(a,"dlc");this._droplistContainer=AdfAgent.AGENT.getElementById(d);this._initDroplistButtonEventHandling();this._conveyorBeltButtonWidth=this._getConveyorBeltButtonWidth();this._keepRollingRight=this._keepRollingLeft=!1};
AdfConveyorBeltHorizontal.prototype.removeConveyorBeltSupport=function(){AdfConveyorBeltHorizontal.superclass.removeConveyorBeltSupport.call(this);var a=AdfAgent.AGENT,b=this._startIndicator;a.removeBubbleEventListener(b,"mousedown",this._startButtonCall);a.removeBubbleEventListener(b,"keydown",this._startButtonCall);a.removeBubbleEventListener(b,"mouseup",this._startButtonMouseUpCall);a.removeBubbleEventListener(b,"mouseout",this._startButtonMouseOutCall);b=this._endIndicator;a.removeBubbleEventListener(b,
"mousedown",this._endButtonCall);a.removeBubbleEventListener(b,"keydown",this._endButtonCall);a.removeBubbleEventListener(b,"mouseup",this._endButtonMouseUpCall);a.removeBubbleEventListener(b,"mouseout",this._endButtonMouseOutCall);b=this._droplistIndicator;a.removeBubbleEventListener(b,"mousedown",this._droplistShowCall);a.removeBubbleEventListener(b,"keydown",this._droplistShowCall);a.removeBubbleEventListener(b,"mouseup",this._droplistButtonMouseUpCall);a.removeBubbleEventListener(b,"mouseout",
this._droplistButtonMouseOutCall);delete this._startIndicator;delete this._endIndicator;delete this._contentContainer;delete this._itemOffsetLeftArray;delete this._selectedItem;delete this._contentWidth;delete this._initialRender;delete this._firstItemDisplayed;delete this._droplistIndicator;delete this._droplistContainer;delete this._otherCBSupport;delete this._hideDroplistContainerCallback;delete this._droplistHints;delete this._conveyorBeltButtonWidth;delete this._keepRollingLeft;delete this._keepRollingRight};
AdfConveyorBeltHorizontal.prototype.registerAdditionalConveyorBeltSupport=function(a){this._otherCBSupport=a};
AdfConveyorBeltHorizontal.prototype.handleResize=function(){var a=this._isConveyorBeltNeeded(),b=this._areConveyorBeltIconsDisplayed();a?(b||(this._setButtonDisplay(!0),this._initialRender&&(this._firstItemDisplayed=this._calculateFirstItemToDisplay()),this._rollConveyor(!0)),this._setButtonState()):(this._setButtonDisplay(!1),AdfAgent.AGENT.scrollToPos(this._contentContainer,0));this._initialRender&&(this._initialRender=!1)};
AdfConveyorBeltHorizontal.prototype.addDropListElements=function(a){for(var b=this._droplistContainer,d=0;d<a.length;d++)b.appendChild(a[d])};AdfConveyorBeltHorizontal.prototype.scrollNewSelectedItemIntoView=function(a){AdfAssert.assert(0<=a&&a<this._itemOffsetLeftArray.length,"New selected item should be within known valid range of conveyor belt support");this._selectedItem=a;this._firstItemDisplayed=this._calculateFirstItemToDisplay();this._rollConveyor(!0)};
AdfConveyorBeltHorizontal.prototype.getFirstItemDisplayed=function(){return this._firstItemDisplayed};AdfConveyorBeltHorizontal.prototype.setFirstItemDisplayed=function(a){AdfAssert.assert(a&&0<=a&&a<this._itemOffsetLeftArray.length,"Must set the first item displayed to a valid number within the child range!");this._firstItemDisplayed=a};AdfConveyorBeltHorizontal.prototype.handleFocusChange=function(){this._setButtonState()};
AdfConveyorBeltHorizontal._getInnerWidth=function(a){var b=AdfAgent.AGENT.getComputedStyle(a),b=AdfAgent.getCSSLengthAsInt(b.paddingLeft)+AdfAgent.getCSSLengthAsInt(b.paddingRight);return a.offsetWidth-b};
AdfConveyorBeltHorizontal.prototype._getConveyorBeltButtonWidth=function(){var a=AdfConveyorBeltHorizontal.superclass.GetContainer.call(this),b=this._areConveyorBeltIconsDisplayed();b&&this._setButtonDisplay(!1);var d=AdfConveyorBeltHorizontal._getInnerWidth(a);this._setButtonDisplay(!0);a=AdfConveyorBeltHorizontal._getInnerWidth(a);b||this._setButtonDisplay(!1);return d-a};
AdfConveyorBeltHorizontal.prototype._isConveyorBeltNeeded=function(){var a=AdfConveyorBeltHorizontal.superclass.GetContainer.call(this),a=AdfConveyorBeltHorizontal._getInnerWidth(a);this._areConveyorBeltIconsDisplayed()&&(a+=this._conveyorBeltButtonWidth);return this._contentWidth>=a};AdfConveyorBeltHorizontal.prototype._areConveyorBeltIconsDisplayed=function(){var a=AdfConveyorBeltHorizontal.superclass.GetContainer.call(this);return AdfDomUtils.containsCSSClassName(a,AdfConveyorBeltSupport.CONVEYOR_BELT_STYLE_CLASS)};
AdfConveyorBeltHorizontal.prototype._setButtonDisplay=function(a){var b=AdfConveyorBeltHorizontal.superclass.GetContainer.call(this);a?AdfDomUtils.addCSSClassName(b,AdfConveyorBeltSupport.CONVEYOR_BELT_STYLE_CLASS):AdfDomUtils.removeCSSClassName(b,AdfConveyorBeltSupport.CONVEYOR_BELT_STYLE_CLASS)};
AdfConveyorBeltHorizontal.prototype._setButtonState=function(){this._doesContentRollLeft()?(AdfDomUtils.removeCSSClassName(this._startIndicator,AdfRichUIPeer.DISABLED_STYLECLASS),this._startIndicator.removeAttribute("aria-disabled")):(AdfDomUtils.addCSSClassName(this._startIndicator,AdfRichUIPeer.DISABLED_STYLECLASS),this._startIndicator.setAttribute("aria-disabled","true"));this._doesContentRollRight()?this._firstItemDisplayed+1<this._itemOffsetLeftArray.length?(AdfDomUtils.removeCSSClassName(this._endIndicator,
AdfRichUIPeer.DISABLED_STYLECLASS),this._endIndicator.removeAttribute("aria-disabled")):(AdfDomUtils.addCSSClassName(this._endIndicator,AdfRichUIPeer.DISABLED_STYLECLASS),this._endIndicator.setAttribute("aria-disabled","true")):(AdfDomUtils.addCSSClassName(this._endIndicator,AdfRichUIPeer.DISABLED_STYLECLASS),this._endIndicator.setAttribute("aria-disabled","true"))};
AdfConveyorBeltHorizontal.prototype._doesContentRollLeft=function(){var a=AdfPage.PAGE.getLocaleContext().isRightToLeft(),b=AdfAgent.AGENT;if(a&&b.getPlatform()!=AdfAgent.IE_PLATFORM){if(b.getPlatform()==AdfAgent.GECKO_PLATFORM)return this._contentContainer&&0>this._contentContainer.scrollLeft;a=this._contentWidth-this._contentContainer.scrollLeft;b=AdfConveyorBeltHorizontal.superclass.GetContainer.call(this);b=AdfConveyorBeltHorizontal._getInnerWidth(b);return a>b+10}return this._contentContainer&&
0<this._contentContainer.scrollLeft};
AdfConveyorBeltHorizontal.prototype._doesContentRollRight=function(){var a=AdfAgent.AGENT;if(AdfPage.PAGE.getLocaleContext().isRightToLeft()&&a.getPlatform()!=AdfAgent.IE_PLATFORM)if(a.getPlatform()==AdfAgent.GECKO_PLATFORM)a=this._contentWidth+this._contentContainer.scrollLeft;else return this._contentContainer&&0<this._contentContainer.scrollLeft;else a=this._contentWidth-this._contentContainer.scrollLeft;var b=AdfConveyorBeltHorizontal.superclass.GetContainer.call(this),b=AdfConveyorBeltHorizontal._getInnerWidth(b);
return a>b+10};
AdfConveyorBeltHorizontal.prototype._calculateFirstItemToDisplay=function(){if(void 0==this._selectedItem)return this._firstItemDisplayed;if(this._selectedItem<=this._firstItemDisplayed)return this._selectedItem;var a=this._itemOffsetLeftArray[this._selectedItem],b=AdfDomUtils.getChildElementByPosition(this._contentContainer,1,this._selectedItem),b=a+b.offsetWidth,d=AdfConveyorBeltHorizontal.superclass.GetContainer.call(this),e=AdfConveyorBeltHorizontal._getInnerWidth(d),d=e;if(b-a>d)return this._selectedItem;
for(a=1;a<=this._firstItemDisplayed;a++)d+=this._itemOffsetLeftArray[a]-this._itemOffsetLeftArray[a-1];if(b<=d)return this._firstItemDisplayed;d=e;for(a=1;a<this._itemOffsetLeftArray.length;a++)if(d+=this._itemOffsetLeftArray[a]-this._itemOffsetLeftArray[a-1],b<=d)return a;AdfAssert.assert(!0,"Code unreachable, all cases handled");return 0};
AdfConveyorBeltHorizontal.prototype._rollConveyor=function(a){var b=AdfPage.PAGE.getLocaleContext().isRightToLeft(),d=AdfAgent.AGENT,b=b&&d.getPlatform()!=AdfAgent.IE_PLATFORM?d.getPlatform()==AdfAgent.GECKO_PLATFORM?-this._itemOffsetLeftArray[this._firstItemDisplayed]:this._contentContainer.scrollWidth-this._contentContainer.offsetWidth-this._itemOffsetLeftArray[this._firstItemDisplayed]:this._itemOffsetLeftArray[this._firstItemDisplayed];a||!AdfPage.PAGE.isAnimationEnabled()?(d.scrollToPos(this._contentContainer,
b),this._setButtonState()):this._animateRollConveyor(b)};AdfConveyorBeltHorizontal.prototype._animateRollConveyor=function(a){AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_SLOW_FAST_SLOW,2*Math.abs(this._contentContainer.scrollLeft-a),[{element:this._contentContainer,properties:{scrollLeft:a}}],null,AdfConveyorBeltHorizontal._animateRollConveyorComplete,this,null)};
AdfConveyorBeltHorizontal._animateRollConveyorComplete=function(a){a._keepRollingLeft?a._otherCBSupport?a._rollMultipleLeft():a._rollLeft():a._keepRollingRight&&(a._otherCBSupport?a._rollMultipleRight():a._rollRight());a._setButtonState()};AdfConveyorBeltHorizontal.prototype._rollLeft=function(){this._doesContentRollLeft()?(this._firstItemDisplayed=0<this._firstItemDisplayed?this._firstItemDisplayed-1:0,this._rollConveyor()):this._stopRollingLeft()};
AdfConveyorBeltHorizontal.prototype._rollMultipleLeft=function(){AdfAssert.assert(null!=this._otherCBSupport,"Method should only be called if there are multiple conveyors.");this._rollLeft();this._otherCBSupport._rollLeft()};AdfConveyorBeltHorizontal.prototype._rollRight=function(){this._doesContentRollRight()?(this._firstItemDisplayed=this._firstItemDisplayed+1>=this._itemOffsetLeftArray.length?this._itemOffsetLeftArray.length-1:this._firstItemDisplayed+1,this._rollConveyor()):this._stopRollingRight()};
AdfConveyorBeltHorizontal.prototype._rollMultipleRight=function(){AdfAssert.assert(null!=this._otherCBSupport,"Method should only be called if there are multiple conveyors.");this._rollRight();this._otherCBSupport._rollRight()};AdfConveyorBeltHorizontal.prototype._stopRollingLeft=function(){this._keepRollingLeft=!1;this._rollLeftTimer&&clearInterval(this._rollLeftTimer);this._rollLeftTimer=null};
AdfConveyorBeltHorizontal.prototype._stopRollingRight=function(){this._keepRollingRight=!1;this._rollRightTimer&&clearInterval(this._rollRightTimer);this._rollRightTimer=null};
AdfConveyorBeltHorizontal.prototype._initStartButtonEventHandling=function(){var a=AdfAgent.AGENT,b=this._startIndicator;this._startButtonCall=this.createCallback(this._startConveyorBeltButtonPressed);a.addBubbleEventListener(b,"mousedown",this._startButtonCall);this._startButtonMouseUpCall=this.createCallback(this._startConveyorBeltButtonMouseUp);a.addBubbleEventListener(b,"mouseup",this._startButtonMouseUpCall);this._startButtonMouseOutCall=this.createCallback(this._startConveyorBeltButtonMouseOut);
a.addBubbleEventListener(b,"mouseout",this._startButtonMouseOutCall)};
AdfConveyorBeltHorizontal.prototype._initEndButtonEventHandling=function(){var a=AdfAgent.AGENT,b=this._endIndicator;this._endButtonCall=this.createCallback(this._endConveyorBeltButtonPressed);a.addBubbleEventListener(b,"mousedown",this._endButtonCall);this._endButtonMouseUpCall=this.createCallback(this._endConveyorBeltButtonMouseUp);a.addBubbleEventListener(b,"mouseup",this._endButtonMouseUpCall);this._endButtonMouseOutCall=this.createCallback(this._endConveyorBeltButtonMouseOut);a.addBubbleEventListener(b,
"mouseout",this._endButtonMouseOutCall)};
AdfConveyorBeltHorizontal.prototype._startConveyorBeltButtonPressed=function(a){var b=AdfAgent.AGENT,d=a.type;if("mousedown"!=d||!a.button||a.button==AdfUIInputEvent.LEFT_BUTTON_FLAG){var e=b.getEventTarget(a);AdfDomUtils.containsCSSClassName(e,AdfRichUIPeer.DISABLED_STYLECLASS)||("mousedown"==d&&this._setDepressedStyle(e,!0),this._keepRollingLeft=!0,this._otherCBSupport?this._rollMultipleLeft():this._rollLeft(),AdfPage.PAGE.isAnimationEnabled()||(d=this._otherCBSupport?this.createCallback(this._rollMultipleLeft):
this.createCallback(this._rollLeft),this._rollLeftTimer=setInterval(d,200)))}b.eatEvent(a)};AdfConveyorBeltHorizontal.prototype._startConveyorBeltButtonMouseUp=function(a){a=AdfAgent.AGENT.getEventTarget(a);this._setDepressedStyle(a,!1);this._stopRollingLeft()};AdfConveyorBeltHorizontal.prototype._startConveyorBeltButtonMouseOut=function(a){a=AdfAgent.AGENT.getEventTarget(a);this._setDepressedStyle(a,!1);this._stopRollingLeft()};
AdfConveyorBeltHorizontal.prototype._endConveyorBeltButtonPressed=function(a){var b=AdfAgent.AGENT,d=a.type;if("mousedown"!=d||!a.button||a.button==AdfUIInputEvent.LEFT_BUTTON_FLAG){var e=b.getEventTarget(a);AdfDomUtils.containsCSSClassName(e,AdfRichUIPeer.DISABLED_STYLECLASS)||("mousedown"==d&&this._setDepressedStyle(e,!0),this._keepRollingRight=!0,this._otherCBSupport?this._rollMultipleRight():this._rollRight(),AdfPage.PAGE.isAnimationEnabled()||(d=this._otherCBSupport?this.createCallback(this._rollMultipleRight):
this.createCallback(this._rollRight),this._rollRightTimer=setInterval(d,200)))}b.eatEvent(a)};AdfConveyorBeltHorizontal.prototype._endConveyorBeltButtonMouseUp=function(a){a=AdfAgent.AGENT.getEventTarget(a);this._setDepressedStyle(a,!1);this._stopRollingRight()};AdfConveyorBeltHorizontal.prototype._endConveyorBeltButtonMouseOut=function(a){a=AdfAgent.AGENT.getEventTarget(a);this._setDepressedStyle(a,!1);this._stopRollingRight()};
AdfConveyorBeltHorizontal.prototype._setDepressedStyle=function(a,b){var d=AdfConveyorBeltSupport.DEPRESSED_STYLE_CLASS;b?AdfDomUtils.addCSSClassName(a,d):AdfDomUtils.removeCSSClassName(a,d)};
AdfConveyorBeltHorizontal.prototype._initDroplistButtonEventHandling=function(){var a=AdfAgent.AGENT,b=this._droplistIndicator,d=this._createConveyorBeltPopupHints();d[AdfDhtmlPopupHints.ALIGN_ELEMENT]=b;d[AdfRichPopup.HINT_ALIGN]=AdfRichPopup.ALIGN_AFTER_END;this._droplistHints=d;d=this._droplistShowCall=this.createCallback(this._droplistButtonPressed);a.addBubbleEventListener(b,"mousedown",d);a.addBubbleEventListener(b,"keydown",d);this._droplistButtonMouseUpCall=this.createCallback(this._droplistButtonMouseUp);
a.addBubbleEventListener(b,"mouseup",this._droplistButtonMouseUpCall);this._droplistButtonMouseOutCall=this.createCallback(this._droplistButtonMouseOut);a.addBubbleEventListener(b,"mouseout",this._droplistButtonMouseOutCall)};
AdfConveyorBeltHorizontal.prototype._createConveyorBeltPopupHints=function(){var a={};a[AdfDhtmlPopupHints.AUTODISMISS]=AdfDhtmlPopupHints.AUTODISMISS_ALWAYS;a[AdfDhtmlPopupHints.FOCUS]=!0;a[AdfDhtmlPopupHints.TYPE]=AdfDhtmlPopupHints.TYPE_MENU;a[AdfDhtmlPopupHints.CLOSE_ON_ESCAPE]=!0;return a};
AdfConveyorBeltHorizontal.prototype._droplistButtonPressed=function(a){var b=AdfAgent.AGENT,d=a.type,e=a.keyCode;if("keydown"!=d||e==AdfKeyStroke.ENTER_KEY||e==AdfKeyStroke.ARROWDOWN_KEY){if("mousedown"!=d||!a.button||a.button==AdfUIInputEvent.LEFT_BUTTON_FLAG){null==this._hideDroplistContainerCallback&&(this._hideDroplistContainerCallback=this.createCallback(this._hideDroplistContainer),AdfObject.ensureClassInitialization(AdfDhtmlPopupWindow),this._droplistHints[AdfDhtmlPopupHints.CLOSE_HANDLER]=
this._hideDroplistContainerCallback,this._droplistHints[AdfDhtmlPopupHints.TITLE]=AdfAgent.AGENT.getEventTarget(a).title,this._droplistContainerParent=this._droplistContainer.parentNode);var e=AdfConveyorBeltHorizontal.superclass.GetPeer.call(this),f=e.getComponent(),g=AdfConveyorBeltSupport.DROPLIST_ID;e.isPopupVisible(f,g)?e.hidePopup(f,g):e.showPopup(f,this._droplistContainer,this._droplistHints,g);"mousedown"==d&&(d=b.getEventTarget(a),this._setDepressedStyle(d,!0))}b.eatEvent(a)}};
AdfConveyorBeltHorizontal.prototype._droplistButtonMouseUp=function(a){a=AdfAgent.AGENT.getEventTarget(a);this._setDepressedStyle(a,!1)};AdfConveyorBeltHorizontal.prototype._droplistButtonMouseOut=function(a){a=AdfAgent.AGENT.getEventTarget(a);this._setDepressedStyle(a,!1)};AdfConveyorBeltHorizontal.prototype._hideDroplistContainer=function(){this._droplistContainer&&this._droplistContainerParent.appendChild(this._droplistContainer)};