AdfUIComponents.createComponentClass("AdfRichSelectOneChoice",{componentType:"oracle.adf.RichSelectOneChoice",propertyKeys:[{name:"changed",type:"Boolean","default":!1},{name:"changedDesc",type:"String"},{name:"autoSubmit",type:"Boolean","default":!1},{name:"accessKey",type:"String"},{name:"contentStyle",type:"String"},{name:"helpTopicId",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"label",type:"String"},{name:"labelStyle",type:"String"},{name:"readOnly",type:"Boolean",
"default":!1,secured:!0},{name:"showRequired",type:"Boolean","default":!1},{name:"simple",type:"Boolean","default":!1},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"valuePassThru",type:"Boolean","default":!1,secured:!0},{name:"editable",type:"String","default":"inherit"},{name:"unselectedLabel",type:"String"},{name:"mode",type:"String","default":"default"}],
superclass:AdfUISelectOne});
AdfRichUIPeer.createPeerClass(AdfDhtmlSelectOneListbasePeer,"AdfDhtmlSelectOneChoicePeer");
AdfDhtmlSelectOneChoicePeer.InitSubclass=function(){AdfRichUIPeer.addComponentPropertyGetters(this,AdfUIEditableValue.SUBMITTED_VALUE,AdfUISelectOne.SELECT_ITEMS,AdfRichSelectOneChoice.LABEL);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichSelectOneChoice.LABEL,AdfRichSelectOneChoice.DISABLED);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.BLUR_EVENT_TYPE,AdfUIInputEvent.FOCUS_EVENT_TYPE,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.MOUSE_DOWN_EVENT_TYPE,AdfUIInputEvent.KEY_DOWN_EVENT_TYPE,
AdfUIInputEvent.KEY_PRESS_EVENT_TYPE);AdfAgent.AGENT.isTouchFirstDevice()||AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_IN_EVENT_TYPE);this._CONTENT_ID="content";this._COMPACT="compact";this._DROPDOWN_ID="drop";this._POPUP_ID="pop";this._POPUP_WRAPPER_ID="popWrap";this._SPACER_ID="sp";this._POPUP_PANEL_ID="_afrSelectOnePopupPanel";this._SCROLL_STYLE="p_AFScroll";this._SELECTED_STYLE_CLASS="p_AFSelected";this._HIGHLIGHTED_STYLE_CLASS="p_AFHighlighted";this._TEMP_OPTION_KEY="_adfTmpOpt";
this._KEYBOARD_TYPE_DELAY=250};AdfDhtmlSelectOneChoicePeer.prototype.needsFocusTargetStyleClass=function(){return!0};AdfDhtmlSelectOneChoicePeer.prototype.InitDomElement=function(a,b){AdfDhtmlSelectOneChoicePeer.superclass.InitDomElement.call(this,a,b);this.StashOldValue(a,b);this._adjustWidth(a,b)};
AdfDhtmlSelectOneChoicePeer.prototype.LazyInitialize=function(a,b){AdfDhtmlSelectOneChoicePeer.superclass.LazyInitialize.call(this,a,b);var d=AdfDhtmlEditableValuePeer.getContentNode(a,b);if(d)if(this._isCompactOrCustomModeSupported(a))a.getReadOnly()||d.setAttribute("aria-expanded","false");else if(AdfRichUIPeer.addEventHandlerToDomInstance(AdfDhtmlSelectOneChoicePeer,d,AdfDhtmlLookAndFeel.CHANGE_EVENT_TYPE),d=d.options){var e=d.length,f;for(f=0;f<e;f++)if(null==d[f].title||""==d[f].title)d[f].title=
d[f].text}};AdfDhtmlSelectOneChoicePeer.prototype.HandleComponentBlur=function(a){a=a.getSource();var b=this.getDomElement();!this.isPopupVisible(a,AdfDhtmlSelectOneChoicePeer._POPUP_PANEL_ID)&&this._isCompactOrCustomModeSupported(a)&&this.ValidateAndStashNewValue(a,b)};
AdfDhtmlSelectOneChoicePeer.prototype.HandleComponentMouseDown=function(a){if(a.getEventPhase()==AdfBaseEvent.AT_TARGET_PHASE){var b=a.getSource();if(this._isCompactOrCustomModeSupported(b)&&!b.getDisabled()&&!b.getReadOnly()){a=a.getNativeEvent();a=AdfAgent.AGENT.getEventTarget(a);var d=AdfRichUIPeer.getDomElementForComponent(b),e=AdfAgent.AGENT.getElementById(AdfRichUIPeer.createSubId(b.getClientId(),AdfDhtmlSelectOneChoicePeer._DROPDOWN_ID)),f=AdfDhtmlSelectOneChoicePeer._getLabelElementInCompactMode(b);
this._isCompact(b)&&a==f||a==AdfDhtmlEditableValuePeer.getContentNode(b)||a==e||a.parentNode==e?this.isPopupVisible(b,AdfDhtmlSelectOneChoicePeer._POPUP_PANEL_ID)?this.hidePopup(b,AdfDhtmlSelectOneChoicePeer._POPUP_PANEL_ID):this._showPopupPanel(b):(d==a||AdfDomUtils.isAncestor(d,a))&&this.isPopupVisible(b,AdfDhtmlSelectOneChoicePeer._POPUP_PANEL_ID)&&this.hidePopup(b,AdfDhtmlSelectOneChoicePeer._POPUP_PANEL_ID);AdfFocusUtils.focusElement(this._getFocusElement(b))}}};
AdfDhtmlSelectOneChoicePeer.prototype.HandleComponentClick=function(a){if(a.getEventPhase()==AdfBaseEvent.AT_TARGET_PHASE){AdfDhtmlSelectOneChoicePeer.superclass.HandleComponentClick.call(this,a);var b=a.getSource();if(this._isCompactOrCustomModeSupported(b)){a=a.getNativeEventTarget();if(this.IsItemEnabled(a)){var d=a.getAttribute(AdfDhtmlSelectOneListbasePeer._ITEM_VALUE_EXPANDO);AdfDomUtils.removeCSSClassName(a,AdfDhtmlSelectOneChoicePeer._HIGHLIGHTED_STYLE_CLASS);a=this.getDomElement();this.SetDisplayValue(b,
a,d);this.ValidateAndStashNewValue(b,a,d);this._returnToDropDown(b)}else if(!this._closingPopup&&AdfAgent.IE_PLATFORM==AdfAgent.AGENT.getPlatform()&&!b.getReadOnly()){AdfRichUIPeer.getDomElementForComponent(b);var d=AdfAgent.AGENT.getElementById(AdfRichUIPeer.createSubId(b.getClientId(),AdfDhtmlSelectOneChoicePeer._DROPDOWN_ID)),e=AdfDhtmlSelectOneChoicePeer._getLabelElementInCompactMode(b);!this._isCompact(b)||a!=e&&a!=AdfDhtmlEditableValuePeer.getContentNode(b)&&a!=d&&a.parentNode!=d||this.isPopupVisible(b,
AdfDhtmlSelectOneChoicePeer._POPUP_PANEL_ID)||this._showPopupPanel(b)}this._closingPopup=!1}}};AdfDhtmlSelectOneChoicePeer.prototype.HandleComponentKeyUp=function(a){if(AdfBaseEvent.AT_TARGET_PHASE==a.getEventPhase()&&AdfAgent.IE_PLATFORM==AdfAgent.AGENT.getPlatform()&&AdfKeyStroke.ENTER_KEY==AdfAgent.AGENT.getKeyCode(a.getNativeEvent())){var b=a.getSource();a.cancel();AdfDhtmlEditableValuePeer.getContentNode(b).blur();AdfFocusUtils.focusElement(this._getFocusElement(b))}};
AdfDhtmlSelectOneChoicePeer.prototype.HandleComponentKeyDown=function(a){this.StopArrowKeyBubbling(a);if(a.getEventPhase()==AdfBaseEvent.AT_TARGET_PHASE){var b=a.getSource();if(this._isCompactOrCustomModeSupported(b)&&!b.getReadOnly()&&!b.getDisabled()){var d=a.getNativeEventTarget(),e=a.getNativeEvent(),f=AdfAgent.AGENT.getKeyCode(e),g=this.getDomElement(),h=this.GetSubmittedValue(b,g),k=this.FindItemElementWithValue(b,h);switch(f){case AdfKeyStroke.ESC_KEY:a.cancel();this._returnToDropDown(b);break;
case AdfKeyStroke.ENTER_KEY:this.isPopupVisible(b,AdfDhtmlSelectOneChoicePeer._POPUP_PANEL_ID)?(this.ValidateAndStashNewValue(b,g,h),AdfAgent.IE_PLATFORM==AdfAgent.AGENT.getPlatform()&&(this._closingPopup=!0),this._returnToDropDown(b)):this._showPopupPanel(b);break;case AdfKeyStroke.TAB_KEY:this.isPopupVisible(b,AdfDhtmlSelectOneChoicePeer._POPUP_PANEL_ID)&&this._returnToDropDown(b);break;case AdfKeyStroke.ARROWDOWN_KEY:if(e.altKey){this._showPopupPanel(b);break}case AdfKeyStroke.ARROWUP_KEY:if(("A"==
d.tagName||"INPUT"==d.tagName)&&!this.isPopupVisible(b,AdfDhtmlSelectOneChoicePeer._POPUP_PANEL_ID)){this._showPopupPanel(b);a.cancel();break}(e=f==AdfKeyStroke.ARROWUP_KEY?this.GetPreviousEnabledItem(k):this.GetNextEnabledItem(k))||(e=this.GetFirstEnabledItem(b));d=this.isPopupVisible(b,AdfDhtmlSelectOneChoicePeer._POPUP_PANEL_ID);e!=k&&(k=""+e.getAttribute(AdfDhtmlSelectOneListbasePeer._ITEM_VALUE_EXPANDO),d?this.SetDisplayValue(b,g,k):this.ValidateAndStashNewValue(b,g,k));d&&a.cancel();break;case AdfKeyStroke.BACKSPACE_KEY:void 0!==
b._keyboardValue&&(b._keyboardValue=b._keyboardValue.slice(0,-1))}}AdfAgent.IE_PLATFORM==AdfAgent.AGENT.getPlatform()&&8>=AdfAgent.AGENT.getVersion()&&AdfKeyStroke.ENTER_KEY==AdfAgent.AGENT.getKeyCode(a.getNativeEvent())&&(a.Event.returnValue=!1)}};
AdfDhtmlSelectOneChoicePeer.prototype.HandleComponentKeyPress=function(a){this.StopArrowKeyBubbling(a);var b=this.getComponent();if(this._isCompactOrCustomModeSupported(b)&&!b.getReadOnly()&&!b.getDisabled()){var d=a.getNativeEvent();AdfAgent.AGENT.getKeyCode(d)==AdfKeyStroke.SPACE_KEY&&a.cancel();void 0===b._keyboardValue&&(b._keyboardValue="");b._keyboardValue+=d.key;this._selectItemOnTyping(b,b._keyboardValue);a=AdfPage.PAGE;b._keyboardTimer?a.rescheduleTimer(b._keyboardTimer,AdfDhtmlSelectOneChoicePeer._KEYBOARD_TYPE_DELAY):
b._keyboardTimer=a.scheduleTimer(this,AdfDhtmlSelectOneChoicePeer._clearKeyboardValue,b,AdfDhtmlSelectOneChoicePeer._KEYBOARD_TYPE_DELAY)}};AdfDhtmlSelectOneChoicePeer.prototype.HandleDomChange=function(a,b){var d=this.getDomElement();this._isNativeSelectNotSupported(d)||this.ValidateAndStashNewValue(a,d)};
AdfDhtmlSelectOneChoicePeer.prototype.PopupClosed=function(a,b,d){d==AdfDhtmlSelectOneChoicePeer._POPUP_PANEL_ID&&(d=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlSelectOneChoicePeer._POPUP_WRAPPER_ID),AdfAgent.AGENT.getElementById(d).appendChild(b),b=AdfRichUIPeer.getDomElementForComponent(a),b=AdfDhtmlEditableValuePeer.getContentNode(a,b),b.setAttribute("aria-expanded","false"),b.removeAttribute("aria-activedescendant"),AdfFocusUtils.focusElement(this._getFocusElement(a)))};
AdfDhtmlSelectOneChoicePeer.prototype.VetoShowNoteWindow=function(a){return this._isCompact(a)&&this.isPopupVisible(a,AdfDhtmlSelectOneChoicePeer._POPUP_PANEL_ID)?!0:AdfDhtmlSelectOneChoicePeer.superclass.VetoShowNoteWindow.call(this)};AdfDhtmlSelectOneChoicePeer.prototype.GetNoteWindowAlignmentNode=function(a,b){if(this._isNativeSelectNotSupported(b)){var d=this._getFocusElement(a);return this._isCompact(a)?d:d.parentNode}return this._getFocusElement(a)};
AdfDhtmlSelectOneChoicePeer.prototype.GetComponentMode=function(a){return a.getMode()};
AdfDhtmlSelectOneChoicePeer.prototype.SetDisplayValue=function(a,b,d){var e=AdfDhtmlEditableValuePeer.getContentNode(a,b);if(null!=e){var f=a.getReadOnly();AdfAssert.assertString(d);if(!f){f=this.FindItemElementWithValue(a,d);if(this._isCompactOrCustomModeSupported(a)){b=this.GetSubmittedValue(a,b);b=this.FindItemElementWithValue(a,b);this.SelectItemElement(a,f,b);b="";if(null!=f){var g=f.getAttribute("id");e.setAttribute("aria-activedescendant",g);f.firstChild&&(b=f.firstChild.nodeValue)}if(!this._isCompact(a)){AdfAgent.AGENT.getElementsByName(a.getClientId())[0].value=
d;e.value=b;e.title=b;return}}else f&&(e.title=f.title);e.value=d}}};AdfDhtmlSelectOneChoicePeer.prototype.ComponentValueChanged=function(a,b,d,e){this._removeComponentRenderedNoSelectItem(a,d);AdfDhtmlSelectOneChoicePeer.superclass.ComponentValueChanged.call(this,a,b,d,e)};AdfDhtmlSelectOneChoicePeer.prototype.GetSubmittedValue=function(a,b){return this._isCompact(a)||!this._isNativeSelectNotSupported(b)||a.getReadOnly()?AdfDhtmlSelectOneChoicePeer.superclass.GetSubmittedValue.call(this,a,b):AdfAgent.AGENT.getElementsByName(a.getClientId())[0].value};
AdfDhtmlSelectOneChoicePeer.prototype.GetItemElements=function(a){if(this._isCompactOrCustomModeSupported(a))return AdfDhtmlSelectOneChoicePeer.superclass.GetItemElements.call(this,a);var b=this.getDomElement();a=AdfDhtmlEditableValuePeer.getContentNode(a,b);return null==a?null:a.options};
AdfDhtmlSelectOneChoicePeer.prototype.GetComponentSelectItems=function(a,b){return this._isCompactOrCustomModeSupported(a)?AdfDhtmlSelectOneChoicePeer.superclass.GetComponentSelectItems.call(this,a,b):AdfDhtmlSelectOnePeer.GetSelectItemsFromOptions(a,b)};
AdfDhtmlSelectOneChoicePeer.prototype.FindItemElementWithValue=function(a,b){if(this._isCompactOrCustomModeSupported(a))return AdfDhtmlSelectOneChoicePeer.superclass.FindItemElementWithValue.call(this,a,b);var d=this.getDomElement(),d=AdfDhtmlEditableValuePeer.getContentNode(a,d);if(null==d)return null;for(var e=d.options,f=e.length,d=0;d<f;d++)if(e[d].value==b)return e[d];return null};AdfDhtmlSelectOneChoicePeer.prototype.GetInlineEditor=function(a){return AdfDhtmlSimpleLabelEditor.getInlineEditor()};
AdfDhtmlSelectOneChoicePeer.prototype.SetBusy=function(a){AdfAssert.assertBoolean(a);var b=this.getComponent();AdfAssert.assert(!b.getDisabled());AdfAssert.assert(!b.isDead());AdfDomUtils.addOrRemoveCSSClassName(a,this.getDomElement(),AdfRichUIPeer.DISABLED_STYLECLASS)};
AdfDhtmlSelectOneChoicePeer.prototype.ComponentDisabledChanged=function(a,b,d,e){a=AdfDhtmlEditableValuePeer.getContentNode(a,b);1==d?(AdfDomUtils.addCSSClassName(b,AdfRichUIPeer.DISABLED_STYLECLASS),a.setAttribute("disabled","true")):(AdfDomUtils.removeCSSClassName(b,AdfRichUIPeer.DISABLED_STYLECLASS),a.removeAttribute("disabled"))};
AdfDhtmlSelectOneChoicePeer.prototype._adjustWidth=function(a,b){var d=!this._isNativeSelectNotSupported(b);if(!(a.getReadOnly()||d||this._isCompact(a))&&(d=AdfDhtmlEditableValuePeer.getContentNode(a,b),-1!==d.style.cssText.indexOf("width"))){var e=document.getElementById(AdfRichUIPeer.createSubId(a.getClientId(),AdfDhtmlSelectOneChoicePeer._DROPDOWN_ID)),e=AdfDhtmlSelectOneChoicePeer._getComputedWidth(d)-AdfDhtmlSelectOneChoicePeer._getComputedWidth(e);AdfDomUtils.addInlineStyle(d,"width: "+e+"px",
!0)}};AdfDhtmlSelectOneChoicePeer._getComputedWidth=function(a){a=getComputedStyle(a);return AdfAgent.AGENT.getPlatform()!=AdfAgent.IE_PLATFORM&&"border-box"==a.getPropertyValue("box-sizing")?parseFloat(a.getPropertyValue("width")):parseFloat(a.getPropertyValue("width"))+parseFloat(a.getPropertyValue("padding-left"))+parseFloat(a.getPropertyValue("padding-right"))+parseFloat(a.getPropertyValue("border-left-width"))+parseFloat(a.getPropertyValue("border-right-width"))};
AdfDhtmlSelectOneChoicePeer.prototype._removeComponentRenderedNoSelectItem=function(a,b){var d=this.FindItemElementWithValue(a,b);if(d&&(d=AdfAgent.AGENT.getAttribute(d,AdfDhtmlSelectOneChoicePeer._TEMP_OPTION_KEY),!d)){var e=this.GetItemElementsParent(a),f=this.GetFirstEnabledItem(a);(d=AdfAgent.AGENT.getAttribute(f,AdfDhtmlSelectOneChoicePeer._TEMP_OPTION_KEY))&&e.removeChild(f)}};
AdfDhtmlSelectOneChoicePeer.prototype._returnToDropDown=function(a){a.getClientId();var b=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlSelectOneChoicePeer._POPUP_ID);AdfAgent.AGENT.getElementById(b);this.hidePopup(a,AdfDhtmlSelectOneChoicePeer._POPUP_PANEL_ID);AdfFocusUtils.focusElement(this._getFocusElement(a))};
AdfDhtmlSelectOneChoicePeer.prototype._showPopupPanel=function(a){AdfObject.ensureClassInitialization(AdfRichPopup);var b=a.getClientId(),d=AdfRichUIPeer.CreateSubId(b,AdfDhtmlSelectOneChoicePeer._SPACER_ID),d=AdfAgent.AGENT.getElementById(d),e=AdfRichUIPeer.CreateSubId(b,AdfDhtmlSelectOneChoicePeer._POPUP_ID),e=AdfAgent.AGENT.getElementById(e),f={};f[AdfRichPopup.HINT_ALIGN]=AdfRichPopup.ALIGN_AFTER_START;if(this._isCompact(a))f[AdfDhtmlPopupHints.TYPE]=AdfDhtmlPopupHints.TYPE_MENU,f[AdfDhtmlPopupHints.AUTODISMISS]=
AdfDhtmlPopupHints.AUTODISMISS_MENU,f[AdfDhtmlPopupHints.FOCUS]=!0,f[AdfRichPopup.HINT_ALIGN_ID]=AdfRichUIPeer.CreateSubId(b,AdfDhtmlSelectOneChoicePeer._DROPDOWN_ID);else{AdfDhtmlEditableValuePeer.getContentNode(a).setAttribute("aria-expanded","true");var b=AdfRichUIPeer.CreateSubId(b,AdfDhtmlSelectOneChoicePeer._CONTENT_ID),g=AdfAgent.AGENT.getElementById(b);if(g.disabled)return;AdfDomUtils.containsCSSClassName(e,AdfDhtmlSelectOneChoicePeer._SCROLL_STYLE)?d.style.width=g.parentNode.offsetWidth-
23+"px":d.style.width=g.parentNode.offsetWidth-7+"px";f[AdfDhtmlPopupHints.TYPE]=AdfDhtmlPopupHints.TYPE_MENU;f[AdfDhtmlPopupHints.AUTODISMISS]=AdfDhtmlPopupHints.AUTODISMISS_MENU;f[AdfDhtmlPopupHints.FOCUS]=!1;f[AdfRichPopup.HINT_ALIGN_ID]=b;f[AdfDhtmlPopupHints.ANIMATE]=AdfRichPopup.ANIMATE_FALSE}e.parentNode.removeChild(e);this.showPopup(a,e,f,AdfDhtmlSelectOneChoicePeer._POPUP_PANEL_ID);AdfDomUtils.containsCSSClassName(e,AdfDhtmlSelectOneChoicePeer._SCROLL_STYLE)&&(d=this.getDomElement(),d=this.GetSubmittedValue(a,
d),d=this.FindItemElementWithValue(a,d),this.SelectItemElement(a,d))};AdfDhtmlSelectOneChoicePeer.prototype._isCompact=function(a){return this.GetComponentMode(a)==AdfDhtmlSelectOneChoicePeer._COMPACT};AdfDhtmlSelectOneChoicePeer.prototype._isNativeSelectNotSupported=function(a){a||(a=this.getDomElement());return 0==a.getElementsByTagName("select").length};AdfDhtmlSelectOneChoicePeer.prototype._isCompactOrCustomModeSupported=function(a){return this._isCompact(a)||this._isNativeSelectNotSupported()};
AdfDhtmlSelectOneChoicePeer.prototype._getFocusElement=function(a){if(this._isCompact(a))a=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlSelectOneChoicePeer._DROPDOWN_ID);else{var b=AdfDhtmlSelectOneChoicePeer._CONTENT_ID;a=AdfRichUIPeer.CreateSubId(a.getClientId(),b)}return AdfAgent.AGENT.getElementById(a)};AdfDhtmlSelectOneChoicePeer._clearKeyboardValue=function(a){delete a._keyboardTimer;delete a._keyboardValue};
AdfDhtmlSelectOneChoicePeer.prototype._selectItemOnTyping=function(a,b){var d=a.getSelectItems(),e=d.length,f=this._selectedItemIndex(d),g=f;1==b.trim().length&&(g=f+1);this._selectMatchingItem(d,g,e,b)||this._selectMatchingItem(d,0,g,b)};
AdfDhtmlSelectOneChoicePeer.prototype._selectMatchingItem=function(a,b,d,e){for(var f=null,g=this.getDomElement(),h=this.getComponent();b<d;b++)if(f=a[b],!f.isDisabled()&&AdfDhtmlSelectOneChoicePeer._matcher(f.getLabel(),e))return a=""+f.getValue(),this.SetDisplayValue(h,g,a),!0;return!1};
AdfDhtmlSelectOneChoicePeer.prototype._selectedItemIndex=function(a){for(var b=null,b=this.getDomElement(),d=this.getComponent(),d=this.GetSubmittedValue(d,b),e=a.length,f=0;f<e;f++)if(b=a[f],b.getValue()==d)return f;return 0};AdfDhtmlSelectOneChoicePeer._matcher=function(a,b){return 0===a.toLocaleUpperCase().indexOf(b.toUpperCase())};
AdfDhtmlSelectOneChoicePeer.prototype.GetItemElementsParent=function(a){var b=a.getClientId();return this._isCompactOrCustomModeSupported(a)?AdfAgent.AGENT.getElementById(AdfRichUIPeer.CreateSubId(b,AdfDhtmlSelectOneChoicePeer._POPUP_ID)):AdfAgent.AGENT.getElementById(AdfRichUIPeer.CreateSubId(b,AdfDhtmlSelectOneChoicePeer._CONTENT_ID))};
AdfDhtmlSelectOneChoicePeer.prototype.IsItemEnabled=function(a){return"OPTION"==a.nodeName?!a.hasAttribute("disabled"):AdfDhtmlSelectOneChoicePeer.superclass.IsItemEnabled.call(this,a)};AdfDhtmlSelectOneChoicePeer._getLabelElementInCompactMode=function(a){a=AdfRichUIPeer.createSubId(a.getClientId(),AdfDhtmlSelectOneChoicePeer._DROPDOWN_ID);return document.querySelector("label[for\x3d'"+a+"']")};