AdfUIComponents.createComponentClass("AdfRichSelectOneRadio",{componentType:"oracle.adf.RichSelectOneRadio",propertyKeys:[{name:"changed",type:"Boolean","default":!1},{name:"changedDesc",type:"String"},{name:"autoSubmit",type:"Boolean","default":!1},{name:"accessKey",type:"String"},{name:"contentStyle",type:"String"},{name:"helpTopicId",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"label",type:"String"},{name:"labelStyle",type:"String"},{name:"readOnly",type:"Boolean",
"default":!1,secured:!0},{name:"showRequired",type:"Boolean","default":!1},{name:"simple",type:"Boolean","default":!1},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"valuePassThru",type:"Boolean","default":!1,secured:!0},{name:"layout",type:"String","default":"vertical"},{name:"unselectedLabel",type:"String"}],superclass:AdfUISelectOne});
AdfRichUIPeer.createPeerClass(AdfDhtmlSelectOnePeer,"AdfDhtmlSelectOneRadioPeer");AdfDhtmlSelectOneRadioPeer.InitSubclass=function(){AdfRichUIPeer.addComponentPropertyGetters(this,AdfUIEditableValue.SUBMITTED_VALUE,AdfUISelectOne.SELECT_ITEMS,AdfRichSelectOneRadio.LABEL);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichSelectOneRadio.LABEL);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.CLICK_EVENT_TYPE);this._ITEM_VALUE_EXPANDO="_adfIV"};
AdfDhtmlSelectOneRadioPeer.prototype.HandleComponentClick=function(a){AdfDhtmlSelectOneRadioPeer.superclass.HandleComponentClick.call(this,a);var b=this.getComponent(),d=null;(a=a.getNativeEventTarget())&&"LABEL"==a.tagName&&(a=a.getAttribute("for"))&&-1!=a.indexOf(b.getClientId())&&(d=a);this.Validate(b,this.GetSubmittedValue(b,this.getDomElement(),d))};
AdfDhtmlSelectOneRadioPeer.prototype.GetNoteWindowAlignmentNode=function(a,b){b||(b=this.getDomElement());var d=b.getElementsByTagName("input")[0];return d?"0"===AdfAgent.AGENT.getComputedStyle(d).opacity?d.parentElement:d:AdfDhtmlSelectOneRadioPeer.superclass.GetNoteWindowAlignmentNode.call(this,a,b)};
AdfDhtmlSelectOneRadioPeer.prototype.GetComponentSelectItems=function(a,b){var d=AdfDhtmlEditableValuePeer.getContentNode(a,b);if(null!=d){var d=d.getElementsByTagName("input"),e=[],f=null;if(null!=d)for(var g=d.length,h=0;h<g;h++)f=d[h],e[h]=new AdfSelectItem(f.value,AdfDhtmlEditableValuePeer.GetLabelElement(f).textContent,f.disabled,"t"===f.getAttribute(AdfDhtmlSelectOnePeer.NO_SELECTION_OPTION_EXPANDO));return e}};
AdfDhtmlSelectOneRadioPeer.prototype.GetSubmittedValue=function(a,b,d){b=AdfDhtmlEditableValuePeer.getContentNode(a,b);if(a.getReadOnly())return b.getAttribute(AdfDhtmlSelectOneRadioPeer._ITEM_VALUE_EXPANDO);if(d)return AdfAgent.AGENT.getElementById(d).value;a=b.getElementsByTagName("input");for(d=0;d<a.length;d++)if(a[d].checked)return a[d].value;return""};
AdfDhtmlSelectOneRadioPeer.prototype.SetDisplayValue=function(a,b,d){b=AdfDhtmlEditableValuePeer.getContentNode(a,b);if(null!=b)if(a=a.getReadOnly(),AdfAssert.assertString(d),a)AdfAgent.AGENT.setTextContent(b,d);else if(a=b.getElementsByTagName("input"),null!=a){b=a.length;for(var e=0;e<b;e++)a[e].value==d&&(a[e].checked=!0)}};AdfDhtmlSelectOneRadioPeer.prototype.GetInlineEditor=function(a){return AdfDhtmlSimpleLabelEditor.getInlineEditor()};
AdfUIComponents.createComponentClass("AdfRichSelectBooleanCheckbox",{componentType:"oracle.adf.RichSelectBooleanCheckbox",propertyKeys:[{name:"changed",type:"Boolean","default":!1},{name:"changedDesc",type:"String"},{name:"autoSubmit",type:"Boolean","default":!1},{name:"accessKey",type:"String"},{name:"contentStyle",type:"String"},{name:"helpTopicId",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"label",type:"String"},{name:"labelStyle",type:"String"},{name:"readOnly",
type:"Boolean","default":!1,secured:!0},{name:"showRequired",type:"Boolean","default":!1},{name:"simple",type:"Boolean","default":!1},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"text",type:"String"},{name:"nullValueMeans",type:"String","default":"null"},{name:"selected",type:"Boolean","default":!1}],superclass:AdfUISelectBoolean});
AdfRichUIPeer.createPeerClass(AdfDhtmlEditableValuePeer,"AdfDhtmlSelectBooleanCheckboxPeer");
AdfDhtmlSelectBooleanCheckboxPeer.InitSubclass=function(){AdfObject.ensureClassInitialization(AdfRichSelectBooleanCheckbox);AdfRichUIPeer.addComponentPropertyGetters(this,AdfUIEditableValue.SUBMITTED_VALUE,AdfRichSelectBooleanCheckbox.TEXT);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.CLICK_EVENT_TYPE);AdfAgent.AGENT.isTouchFirstDevice()||AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_IN_EVENT_TYPE);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichSelectBooleanCheckbox.TEXT);
this._inlineEditor=null;this._SELECT_BOOLEAN_VALUE_KEY="_adfSbv";this._TRCB="icon-style";this._TRCB_ID="_adfTRC"};AdfDhtmlSelectBooleanCheckboxPeer.prototype.isTristateDeterminateUnchecked=function(a){a=AdfRichUIPeer.createSubId(a.getClientId(),AdfDhtmlSelectBooleanCheckboxPeer._TRCB);return(a=AdfAgent.AGENT.getElementById(a))&&!AdfDomUtils.containsCSSClassName(a,AdfRichUIPeer.SELECTED_STYLECLASS)&&!AdfDomUtils.containsCSSClassName(a,"p_AFMixed")};
AdfDhtmlSelectBooleanCheckboxPeer.prototype.InitDomElement=function(a,b){AdfDhtmlSelectBooleanCheckboxPeer.superclass.InitDomElement.call(this,a,b);var d=a.getClientId(),d=AdfRichUIPeer.CreateSubId(d,AdfDhtmlSelectBooleanCheckboxPeer._TRCB);b.setAttribute(AdfDhtmlSelectBooleanCheckboxPeer._TRCB_ID,d);this._updateLabelIdsOnContentNode(a,b)};AdfDhtmlSelectBooleanCheckboxPeer.prototype.HandleComponentMouseOver=function(a){this.ShowNoteWindowMouseOver(a)};
AdfDhtmlSelectBooleanCheckboxPeer.prototype.HandleComponentClick=function(a){AdfDhtmlSelectBooleanCheckboxPeer.superclass.HandleComponentClick.call(this,a);var b=this.getComponent();a=a.getNativeEventTarget();var d=this.getDomElement(),d=AdfDhtmlEditableValuePeer.getContentNode(b,d),e=AdfRichUIPeer.createSubId(b.getClientId(),AdfDhtmlSelectBooleanCheckboxPeer._TRCB);if(d==a){if(e=AdfAgent.AGENT.getElementById(e))d.checked?AdfDomUtils.addCSSClassName(e,AdfRichUIPeer.SELECTED_STYLECLASS):AdfDomUtils.removeCSSClassName(e,
AdfRichUIPeer.SELECTED_STYLECLASS),AdfDomUtils.removeCSSClassName(e,"p_AFMixed")}else d&&e==a.id&&(d.checked?(d.checked=!1,AdfDomUtils.removeCSSClassName(a,"p_AFSelected")):(d.checked=!0,AdfDomUtils.addCSSClassName(a,"p_AFSelected")),AdfDomUtils.removeCSSClassName(a,"p_AFMixed"),a=d);"INPUT"==AdfAgent.AGENT.getNodeName(a)&&(a&&a.checked?this.Validate(b,!0):this.Validate(b,!1))};
AdfDhtmlSelectBooleanCheckboxPeer.prototype.GetSubmittedValue=function(a,b){var d=AdfDhtmlEditableValuePeer.getContentNode(a,b);return a.getReadOnly()?AdfAgent.AGENT.getAttribute(d,AdfDhtmlSelectBooleanCheckboxPeer._SELECT_BOOLEAN_VALUE_KEY):null!=d&&d.checked?!0:!1};
AdfDhtmlSelectBooleanCheckboxPeer.prototype.SetDisplayValue=function(a,b,d){b=AdfDhtmlEditableValuePeer.getContentNode(a,b);null!=b&&(a.getReadOnly()?"true"==d||1==d?(d=a.getText(),AdfAgent.AGENT.setTextContent(b,d)):AdfAgent.AGENT.setTextContent(b,""):(a=AdfAgent.AGENT.getElementById(b.getAttribute(AdfDhtmlSelectBooleanCheckboxPeer._TRCB_ID)),"true"==d||1==d?(b.checked=!0,a&&(AdfDomUtils.addCSSClassName(a,"p_AFSelected"),AdfDomUtils.removeCSSClassName(a,"p_AFMixed"))):(b.checked=!1,a&&(AdfDomUtils.removeCSSClassName(a,
"p_AFSelected"),AdfDomUtils.removeCSSClassName(a,"p_AFMixed")))))};AdfDhtmlSelectBooleanCheckboxPeer.prototype.GetInlineEditor=function(a){a=AdfDhtmlSelectBooleanCheckboxPeer._inlineEditor;null==a&&(a=new AdfDhtmlSelectBooleanTextEditor,AdfDhtmlSelectBooleanCheckboxPeer._inlineEditor=a);return a};
AdfDhtmlSelectBooleanCheckboxPeer.prototype.GetComponentText=function(a,b){var d=AdfDhtmlSelectBooleanCheckboxPeer.__getLabelTextElement(b,this.GetItemTextStyleClass());return null!=d?AdfAgent.AGENT.getTextContent(d):1==a.getReadOnly()?this.GetReadOnlyComponentText(a):null};
AdfDhtmlSelectBooleanCheckboxPeer.prototype.ComponentTextChanged=function(a,b,d,e){b=AdfDhtmlSelectBooleanCheckboxPeer.__getLabelTextElement(b,this.GetItemTextStyleClass());return null!=b?AdfDomUtils.handleTextChangeWithAccessKey(a,b,d):!1};
AdfDhtmlSelectBooleanCheckboxPeer.__getInlineEditableTextElement=function(a){var b=AdfDhtmlSelectBooleanCheckboxPeer.__getLabelTextElement(a,"af|selectBooleanCheckbox::item-text");null==b&&(b=AdfDhtmlSelectBooleanCheckboxPeer.__getLabelTextElement(a,"af|selectBooleanRadio::item-text"));return b};
AdfDhtmlSelectBooleanCheckboxPeer.__getLabelTextElement=function(a,b){for(var d=AdfPage.PAGE.getLookAndFeel().getStyleClass(b),e=a.getElementsByTagName("LABEL"),f=e.length,g=0;g<f;g++){var h=e[g];if(null!=h&&AdfDomUtils.containsCSSClassName(h,d))return h}return null};AdfDhtmlSelectBooleanCheckboxPeer.prototype.GetReadOnlyComponentText=function(a){a=AdfDhtmlEditableValuePeer.getContentNode(a);return AdfAgent.AGENT.getTextContent(a).substring(1)};
AdfDhtmlSelectBooleanCheckboxPeer.prototype.NeedsSpuriousDirtyValueTracking=function(){return!0};AdfDhtmlSelectBooleanCheckboxPeer.prototype.GetItemTextStyleClass=function(){return"af|selectBooleanCheckbox::item-text"};AdfDhtmlSelectBooleanCheckboxPeer.prototype.GetLabelTextStyleClass=function(){return"af|selectBooleanCheckbox::label-text"};
AdfDhtmlSelectBooleanCheckboxPeer.prototype.getLastSubmittedValue=function(a){return(a=AdfDhtmlSelectBooleanCheckboxPeer.superclass.getLastSubmittedValue.call(this,a))?"t"==a?!0:a:!1};
AdfDhtmlSelectBooleanCheckboxPeer.prototype._updateLabelIdsOnContentNode=function(a,b){var d=AdfDhtmlEditableValuePeer.getContentNode(a,b),e=document.querySelectorAll("label[for\x3d'"+d.id+"']");if(e&&0<e.length){for(var f="",g,h=0;h<e.length;h++)g=b.id+"::Label"+h,e[h].setAttribute("id",g),f+=" "+g;f=f.substring(1,f.length);d.setAttribute("aria-labelledby",f)}};
AdfUIComponents.createComponentClass("AdfRichSelectBooleanRadio",{componentType:"oracle.adf.RichSelectBooleanRadio",propertyKeys:[{name:"changed",type:"Boolean","default":!1},{name:"changedDesc",type:"String"},{name:"autoSubmit",type:"Boolean","default":!1},{name:"accessKey",type:"String"},{name:"contentStyle",type:"String"},{name:"helpTopicId",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"label",type:"String"},{name:"labelStyle",type:"String"},{name:"readOnly",type:"Boolean",
"default":!1,secured:!0},{name:"showRequired",type:"Boolean","default":!1},{name:"simple",type:"Boolean","default":!1},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"group",type:"String"},{name:"text",type:"String"},{name:"selected",type:"Boolean","default":!1}],superclass:AdfUISelectBoolean});
AdfRichUIPeer.createPeerClass(AdfDhtmlSelectBooleanCheckboxPeer,"AdfDhtmlSelectBooleanRadioPeer");
AdfDhtmlSelectBooleanRadioPeer.prototype.LazyInitialize=function(a,b){var d=AdfDhtmlEditableValuePeer.getContentNode(a,b).name,e=AdfAgent.AGENT;if(d=AdfDomUtils.getFormElement(b).elements[d]){d.length||(d=[d]);for(var f=0;f<d.length;++f){var g=d[f];if("radio"==g.type&&(g=AdfRichUIPeer.getFirstAncestorComponent(g))){var h=AdfRichUIPeer.getDomElementForComponent(g);this.IsInitialized(g,h)||(AdfDhtmlSelectBooleanRadioPeer.superclass.LazyInitialize.call(this,g,h),g!=a&&e.setExpandoProperty(h,AdfDhtmlEditableValuePeer._INITIALIZED,
"init"))}}}};AdfDhtmlSelectBooleanRadioPeer.prototype.HandleComponentClick=function(a){AdfDhtmlSelectBooleanRadioPeer.superclass.HandleComponentClick.call(this,a);var b=this.getComponent();(a=a.getNativeEventTarget())&&"radio"==a.type&&(a&&a.checked?this.Validate(b,!0):this.Validate(b,!1),this._validateUncheckedComponents(a))};
AdfDhtmlSelectBooleanRadioPeer.prototype._validateUncheckedComponents=function(a){var b=a.name;if(""!=b&&(a=AdfDomUtils.getFormElement(a).elements[b]))for(b=0;b<a.length;++b){var d=a[b];"radio"==d.type&&0==d.checked&&(d=AdfRichUIPeer.getFirstAncestorComponent(d),null==d||1!=d.getSubmittedValue()&&1!=d.getValue()||this.Validate(d,!1))}};AdfDhtmlSelectBooleanRadioPeer.prototype.GetReadOnlyComponentText=function(a){a=AdfDhtmlEditableValuePeer.getContentNode(a);return AdfAgent.AGENT.getTextContent(a)};
AdfDhtmlSelectBooleanRadioPeer.prototype.GetItemTextStyleClass=function(){return"af|selectBooleanRadio::item-text"};AdfDhtmlSelectBooleanRadioPeer.prototype.GetLabelTextStyleClass=function(){return"af|selectBooleanRadio::label-text"};
AdfUIComponents.createComponentClass("AdfRichSelectManyCheckbox",{componentType:"oracle.adf.RichSelectManyCheckbox",propertyKeys:[{name:"changed",type:"Boolean","default":!1},{name:"changedDesc",type:"String"},{name:"autoSubmit",type:"Boolean","default":!1},{name:"accessKey",type:"String"},{name:"contentStyle",type:"String"},{name:"helpTopicId",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"label",type:"String"},{name:"labelStyle",type:"String"},{name:"readOnly",type:"Boolean",
"default":!1,secured:!0},{name:"showRequired",type:"Boolean","default":!1},{name:"simple",type:"Boolean","default":!1},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"valuePassThru",type:"Boolean","default":!1,secured:!0},{name:"layout",type:"String","default":"vertical"}],superclass:AdfUISelectMany});
AdfRichUIPeer.createPeerClass(AdfDhtmlSelectManyPeer,"AdfDhtmlSelectManyCheckboxPeer");AdfDhtmlSelectManyCheckboxPeer.InitSubclass=function(){AdfRichUIPeer.addComponentPropertyGetters(this,AdfUIEditableValue.SUBMITTED_VALUE,AdfUISelectMany.SELECT_ITEMS,AdfRichSelectManyCheckbox.LABEL);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichSelectManyCheckbox.LABEL);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.CLICK_EVENT_TYPE)};
AdfDhtmlSelectManyCheckboxPeer.prototype.HandleComponentClick=function(a){AdfDhtmlSelectManyCheckboxPeer.superclass.HandleComponentClick.call(this,a);var b=this.getComponent();a=a.getNativeEventTarget();"INPUT"==AdfAgent.AGENT.getNodeName(a)&&(a=this.GetSubmittedValue(b,a),this.Validate(b,a))};
AdfDhtmlSelectManyCheckboxPeer.prototype.GetNoteWindowAlignmentNode=function(a,b){b||(b=this.getDomElement());var d=b.getElementsByTagName("input")[0];return d?"0"===AdfAgent.AGENT.getComputedStyle(d).opacity?d.parentElement:d:AdfDhtmlSelectManyCheckboxPeer.superclass.GetNoteWindowAlignmentNode.call(this,a,b)};
AdfDhtmlSelectManyCheckboxPeer.prototype.SetDisplayValue=function(a,b,d){AdfAssert.assertDomElement(b);AdfAssert.assertArray(d);if(a=this.GetCheckboxes(a,b))for(b=0;b<a.length;b++){var e=a[b],f=AdfCollections.indexOf(d,e.value);e.checked=0<=f}};AdfDhtmlSelectManyCheckboxPeer.prototype.GetInlineEditor=function(a){return AdfDhtmlSimpleLabelEditor.getInlineEditor()};