AdfUIComponents.createComponentClass("AdfRichInputNumberSpinbox",{componentType:"oracle.adf.RichInputNumberSpinbox",propertyKeys:[{name:"changed",type:"Boolean","default":!1},{name:"changedDesc",type:"String"},{name:"autoSubmit",type:"Boolean","default":!1},{name:"accessKey",type:"String"},{name:"contentStyle",type:"String"},{name:"helpTopicId",type:"String"},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"label",type:"String"},{name:"labelStyle",type:"String"},{name:"readOnly",type:"Boolean",
"default":!1,secured:!0},{name:"showRequired",type:"Boolean","default":!1},{name:"simple",type:"Boolean","default":!1},{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"editable",type:"String","default":"inherit"},{name:"placeholder",type:"String"},{name:"columns",type:"Number"},{name:"maximum",type:"Object",secured:!0},{name:"minimum",type:"Object",secured:!0},
{name:"stepSize",type:"Object","default":1,secured:!0}],superclass:AdfUIInput});
AdfRichInputNumberSpinbox.InitSubclass=function(){AdfUIComponent.SetPropertyType(AdfRichInputNumberSpinbox,"value","Number")};AdfRichInputNumberSpinbox.prototype.AddRangeMessage=function(a){if(this.IsEmpty(a)||isNaN(a))return!1;var b=this.getProperty("minimum"),c=this.getProperty("maximum");if(null==b&&null==c)return!1;this.ValidateValue(a);if(this.getValid())return!1;if(null!=b&&null!=c)return!0;if(null!=b){if(!(a>b))return!0}else if(null!=c&&!(a<c))return!0;return!1};
AdfRichUIPeer.createPeerClass(AdfDhtmlInputBasePeer,"AdfDhtmlInputNumberSpinboxBasePeer");AdfDhtmlInputNumberSpinboxBasePeer.InitSubclass=function(){AdfRichUIPeer.addComponentPropertyGetters(this,AdfRichInputNumberSpinbox.LABEL);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichInputNumberSpinbox.LABEL);this._LEAD_ZERO="_adfLeadingZero"};AdfDhtmlInputNumberSpinboxBasePeer.prototype.getLeadingZero=function(){return this.getDomElement().getAttribute(AdfDhtmlInputNumberSpinboxBasePeer._LEAD_ZERO)};
AdfDhtmlInputNumberSpinboxBasePeer.prototype.SetDisplayValue=function(a,b,d){AdfAssert.assertString(d);this.getLeadingZero()&&(b=parseFloat(d),!isNaN(b)&&10>b&&(d="0"+b));a=AdfDhtmlEditableValuePeer.getContentNode(a);"INPUT"==a.tagName?(a.value=d,a.title=d):AdfAgent.AGENT.setTextContent(a,d)};AdfDhtmlInputNumberSpinboxBasePeer.prototype.LazyInitialize=function(a,b){AdfDhtmlInputNumberSpinboxBasePeer.superclass.LazyInitialize.call(this,a,b);this._createClientSideValidator(a,b)};
AdfDhtmlInputNumberSpinboxBasePeer.prototype.ShouldShowHint=function(a,b){return!1};AdfDhtmlInputNumberSpinboxBasePeer.prototype.GetValidatorHints=function(a){return null};AdfDhtmlInputNumberSpinboxBasePeer.prototype._createClientSideValidator=function(a,b){AdfAssert.assertDomElement(b);var d=a.getMinimum(),e=a.getMaximum();void 0!==AdfPage.PAGE.getDomWindow().TrRangeValidator&&(d=new TrRangeValidator(e,d,null),a.addValidator(d))};
AdfRichUIPeer.createPeerClass(AdfDhtmlInputNumberSpinboxBasePeer,"AdfDhtmlInputNumberSpinboxPeer");
AdfDhtmlInputNumberSpinboxPeer.InitSubclass=function(){AdfObject.ensureClassInitialization(AdfRichInputNumberSpinbox);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.BLUR_EVENT_TYPE,AdfUIInputEvent.MOUSE_OUT_EVENT_TYPE,AdfUIInputEvent.MOUSE_UP_EVENT_TYPE,AdfUIInputEvent.MOUSE_DOWN_EVENT_TYPE,AdfUIInputEvent.KEY_DOWN_EVENT_TYPE,AdfUIInputEvent.KEY_PRESS_EVENT_TYPE);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichInputNumberSpinbox.DISABLED);this._timerId=
this._currentSpinMode=null;this._INC="increment";this._DEC="decrement";this._INC_ID="_adfInc";this._DEC_ID="_adfDec"};AdfDhtmlInputNumberSpinboxPeer.prototype.GetStepSize=function(a){return a.getStepSize()};
AdfDhtmlInputNumberSpinboxPeer.prototype.InitDomElement=function(a,b){AdfDhtmlInputNumberSpinboxPeer.superclass.InitDomElement.call(this,a,b);var d=AdfDhtmlEditableValuePeer.getContentNode(a,b),e=a.getClientId(),f=AdfRichUIPeer.CreateSubId(e,AdfDhtmlInputNumberSpinboxPeer._INC),e=AdfRichUIPeer.CreateSubId(e,AdfDhtmlInputNumberSpinboxPeer._DEC);b.setAttribute(AdfDhtmlInputNumberSpinboxPeer._INC_ID,f);b.setAttribute(AdfDhtmlInputNumberSpinboxPeer._DEC_ID,e);if(!a.getReadOnly()&&!a.getDisabled()&&(d=
AdfStrings.trim(d.value),""!=d)){if(f=a.getConverter())try{var g=f.getAsObject(d,null);void 0===g&&(g=d);d=parseFloat(g)}catch(h){}else d=parseFloat(d);g=this._getMin(a);f=this._getMax(a);this._updateButtons(b,d>=f,d<=g)}};AdfDhtmlInputNumberSpinboxPeer.prototype.HandleComponentMouseOut=function(a){this.getComponent().getDisabled()||(a=this._getAnchor(AdfAgent.AGENT.getEventTarget(a.getNativeEvent())),this._isActionButton(a)&&self.clearInterval(this._timerId))};
AdfDhtmlInputNumberSpinboxPeer.prototype.HandleComponentMouseDown=function(a){!this.getComponent().getDisabled()&&(a=this._getAnchor(AdfAgent.AGENT.getEventTarget(a.getNativeEvent())),a=this._isActionButton(a))&&(this.getDomElement(),this._currentSpinMode=a,this._timerId=self.setInterval(this.createCallback(this._initRepeat),1E3))};
AdfDhtmlInputNumberSpinboxPeer.prototype.HandleComponentClick=function(a){var b=this.getComponent();!b.getDisabled()&&(AdfDhtmlInputNumberSpinboxPeer.superclass.HandleComponentClick.call(this,a),a=this._getAnchor(AdfAgent.AGENT.getEventTarget(a.getNativeEvent())),a=this._isActionButton(a))&&("inc"==a?this._manipulateValue(!0):"dec"==a&&this._manipulateValue(!1),a=AdfDhtmlEditableValuePeer.getContentNode(b),this.RunValidation(b,a))};
AdfDhtmlInputNumberSpinboxPeer.prototype.HandleComponentBlur=function(a){var b=this.getComponent();if(!b.getReadOnly())if(AdfDhtmlInputNumberSpinboxPeer.superclass.HandleComponentBlur.call(this,a),a=this._getSpinboxValue(b),isNaN(a))this._updateButtons(null,!0,!0);else if(null==a)this._updateButtons(null,!1,!1);else{var d=this._getMax(b),b=this._getMin(b);this._updateButtons(null,a>=d,a<=b)}};
AdfDhtmlInputNumberSpinboxPeer.prototype.HandleComponentMouseUp=function(a){this.getComponent().getDisabled()||(a=this._getAnchor(AdfAgent.AGENT.getEventTarget(a.getNativeEvent())),this._isActionButton(a)&&self.clearInterval(this._timerId))};
AdfDhtmlInputNumberSpinboxPeer.prototype.HandleComponentKeyDown=function(a){this.StopArrowKeyBubbling(a);var b=AdfAgent.AGENT.getKeyCode(a.getNativeEvent()),d=this.getComponent();switch(b){case AdfKeyStroke.ENTER_KEY:this.RunValidation(d,a.getNativeEventTarget());break;case AdfKeyStroke.ARROWUP_KEY:this._manipulateValue(!0);this.RunValidation(d,a.getNativeEventTarget());break;case AdfKeyStroke.ARROWDOWN_KEY:this._manipulateValue(!1);this.RunValidation(d,a.getNativeEventTarget());break;case AdfKeyStroke.END_KEY:a.getNativeEvent().ctrlKey&&
null!=d.getMaximum()&&this._setVisibleValue(d,d.getMaximum());break;case AdfKeyStroke.HOME_KEY:a.getNativeEvent().ctrlKey&&null!=d.getMinimum()&&this._setVisibleValue(d,d.getMinimum())}};AdfDhtmlInputNumberSpinboxPeer.prototype.HandleComponentKeyPress=function(a){this.StopArrowKeyBubbling(a)};AdfDhtmlInputNumberSpinboxPeer.prototype.GetInlineEditor=function(a){return AdfDhtmlSimpleLabelEditor.getInlineEditor()};
AdfDhtmlInputNumberSpinboxPeer.prototype.ComponentDisabledChanged=function(a,b,d,e){a=AdfDhtmlEditableValuePeer.getContentNode(a,b);1==d?(AdfDomUtils.addCSSClassName(b,AdfRichUIPeer.DISABLED_STYLECLASS),a.setAttribute("disabled","true"),this._updateButtons(null,!0,!0)):(AdfDomUtils.removeCSSClassName(b,AdfRichUIPeer.DISABLED_STYLECLASS),this._updateButtons(null,!1,!1),a.removeAttribute("disabled"))};
AdfDhtmlInputNumberSpinboxPeer.prototype._initRepeat=function(){this.focus(this.getComponent());self.clearInterval(this._timerId);this._timerId=self.setInterval(this.createCallback(this._repeatSpinbox),100)};AdfDhtmlInputNumberSpinboxPeer.prototype._repeatSpinbox=function(){"inc"==this._currentSpinMode?this._manipulateValue(!0):"dec"==this._currentSpinMode&&this._manipulateValue(!1)};
AdfDhtmlInputNumberSpinboxPeer.prototype._handleButtonClicks=function(a,b,d){AdfAssert.assertBoolean(d);var e=this._getMin(a),f=this._getMax(a),g=this.GetStepSize(a),h=f-g,k=e+g,l=null;1==d?null==b?l=null!=a.getMinimum()?null!=a.getMaximum()?f:k:null!=a.getMaximum()?f:0:b>h?l=f:(l=b+g,l<e&&(l=e)):null==b?l=null!=a.getMinimum()?e:null!=a.getMaximum()?h:0:b<k?l=e:(l=b-g,l>f&&(l=f));a=a.getConverter();a instanceof AdfMissingConverter&&(a=null);if(a&&null!=l)try{var m=a.getAsObject(a.getAsString(l,null),
null);null!=m&&(l=m)}catch(n){}return l};AdfDhtmlInputNumberSpinboxPeer.prototype._isActionButton=function(a){if(a){var b=this.getDomElement(),d=b.getAttribute(AdfDhtmlInputNumberSpinboxPeer._INC_ID),b=b.getAttribute(AdfDhtmlInputNumberSpinboxPeer._DEC_ID);return a.id==d?"inc":a.id==b?"dec":null}return null};
AdfDhtmlInputNumberSpinboxPeer.prototype._manipulateValue=function(a){AdfAssert.assertBoolean(a);var b=this.getComponent(),d=this._getSpinboxValue(b);isNaN(d)||(a=this._handleButtonClicks(b,d,a),this._setVisibleValue(b,a))};
AdfDhtmlInputNumberSpinboxPeer.prototype._getSpinboxValue=function(a){var b=AdfUIUtils.trim(AdfDhtmlEditableValuePeer.getContentNode(a).value);if(""==b)return null;var d,e=a.getConverter();try{e&&(d=e.getAsObject(b,null)),void 0===d&&(d=parseFloat(b),isNaN(d)&&AdfLogger.LOGGER.warning("inputNumberSpinbox: The value '",b,"' could not be converted to a number.")),b=d}catch(f){this.Validate(a,b),b=NaN}return b};
AdfDhtmlInputNumberSpinboxPeer.prototype._setVisibleValue=function(a,b){var d=a.getConverter();d instanceof AdfMissingConverter&&(d=null);var e;if(d&&null!=b&&(e=d.getAsString(b,null),null==e)){AdfLogger.LOGGER.warning("inputNumberSpinbox: The new value '",b,"' could not be converted for display.");return}var d=this._getMax(a),f=this._getMin(a);this._updateButtons(null,b>=d,b<=f);null!=e&&(b=e);null==b&&(b="");e=this.getDomElement();AdfDhtmlEditableValuePeer.getContentNode(a,e).setAttribute("aria-valuenow",
b.toString());this.SetDisplayValue(a,e,b.toString())};AdfDhtmlInputNumberSpinboxPeer.prototype._getMin=function(a){a=a.getMinimum();null==a&&(a=-Number.MAX_VALUE);return a};AdfDhtmlInputNumberSpinboxPeer.prototype._getMax=function(a){a=a.getMaximum();null==a&&(a=Number.MAX_VALUE);return a};
AdfDhtmlInputNumberSpinboxPeer.prototype._getAnchor=function(a){var b=AdfAgent.AGENT;for("DIV"==b.getNodeName(a)&&a.children[0]&&(a=a.children[0]);a;){if("INPUT"==b.getNodeName(a)||"LABEL"==b.getNodeName(a))return null;if("A"==b.getNodeName(a))return a;a=a.parentNode}};
AdfDhtmlInputNumberSpinboxPeer.prototype._updateButtons=function(a,b,d){AdfAssert.assertDomElementOrNull(a);AdfAssert.assertBoolean(b);AdfAssert.assertBoolean(d);var e=AdfAgent.AGENT,f;f=a?a:this.getDomElement();a=e.getElementById(f.getAttribute(AdfDhtmlInputNumberSpinboxPeer._INC_ID));e=e.getElementById(f.getAttribute(AdfDhtmlInputNumberSpinboxPeer._DEC_ID));AdfDomUtils.addOrRemoveCSSClassName(d,e,AdfRichUIPeer.DISABLED_STYLECLASS);AdfDomUtils.addOrRemoveCSSClassName(b,a,AdfRichUIPeer.DISABLED_STYLECLASS);
AdfDomUtils.addOrRemoveCSSClassName(d,e.parentNode,AdfRichUIPeer.DISABLED_STYLECLASS);AdfDomUtils.addOrRemoveCSSClassName(b,a.parentNode,AdfRichUIPeer.DISABLED_STYLECLASS)};