AdfUIComponents.createComponentClass("AdfUIShowOne",{componentType:"org.apache.myfaces.trinidad.ShowOne"});
AdfUIComponents.createComponentClass("AdfRichPanelTabbed",{componentType:"oracle.adf.RichPanelTabbed",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"contentDelivery",type:"String","default":"lazyUncached"},{name:"dimensionsFrom",type:"String","default":"parent"},{name:"maxTabSize",type:"String","default":"infinity"},{name:"minTabSize",
type:"String","default":"0px"},{name:"truncationStyle",type:"String","default":"none"},{name:"verticalTabMode",type:"String","default":"iconOnly"},{name:"position",type:"String","default":"above"},{name:"tabRemoval",type:"String","default":"none"}],eventNames:["item"],superclass:AdfUIShowOne});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlPanelTabbedPeer",!1);
AdfDhtmlPanelTabbedPeer.InitSubclass=function(){AdfRichUIPeer.addComponentPropertyChanges(this,"verticalTabMode");AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.KEY_UP_EVENT_TYPE,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.FOCUS_EVENT_TYPE,AdfUIInputEvent.BLUR_EVENT_TYPE,AdfUIInputEvent.MOUSE_DOWN_EVENT_TYPE,AdfUIInputEvent.MOUSE_UP_EVENT_TYPE);AdfAgent.AGENT.isTouchFirstDevice()||AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_IN_EVENT_TYPE,AdfUIInputEvent.MOUSE_OUT_EVENT_TYPE);
this._TAB_HEADER="tabh";this._TAB_FOOTER="tabf";this._TAB_VERTICAL_CONTAINER="tabp";this._TAB_VERTICAL="tabv";this._TAB_BODY_OUTER="tabb";this._TAB_BODY_INNER="tabbc";this.TAB_SUB_ID_ABOVE="ti";this.TAB_SUB_ID_BELOW="tiB";this.TAB_SUB_ID_ICON="icon";this.TAB_SUB_ID_ICON_BELOW="iconB";this._EXPANDO_ROWKEY_ATTRIBUTE="_afrPtKey";this._TAB_SUB_ID_TOGGLE_ICON="tb";this._TAB_ID_CONVEYOR_SUFFIX="Cnvr";this._EXPANDO_COMPRESSED_LAYOUT_LINK="_afrOfwLnk";this._EXPANDO_DISCLOSED_TAB_ID="_afrDisTab";this._ANCHOR_SUB_ID_ABOVE=
"disAcr";this._ANCHOR_SUB_ID_BELOW="disAcrBlw";this._ANCHOR_SUB_ID_BELOW_LENGTH=this._ANCHOR_SUB_ID_BELOW.length;this._REMOVE_ICON_ABOVE_ID="rmAbv";this._REMOVE_ICON_BELOW_ID="rmBlw";this._HIGHLIGHTED_STYLE_CLASS="p_AFHighlighted";this._ELLIPSIS_SUBID="_afrEps";this._TAB_CONTENT="_afrTabCnt";this._INVERTED_POSITION_MAP={above:"below",below:"above",start:"end",end:"start",left:"right",right:"left"};this._compressedLayoutMode="notSupported";var a=AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|panelTabbed-tr-layout-type"),
b=AdfAgent.AGENT,b=b.getPlatform()==AdfAgent.IE_PLATFORM&&7==Math.floor(b.getVersion());this._compressedLayoutMode="overflow"==a?"overflow":"overflow-droplist"==a||b?"overflow-droplist":"conveyorBelt"};
AdfDhtmlPanelTabbedPeer.prototype.InitDomElement=function(a,b){AdfDhtmlPanelTabbedPeer.superclass.InitDomElement.call(this,a,b);var d=AdfAgent.getAgent(),e=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlPanelTabbedPeer._TAB_HEADER);this._headerDiv=d.getElementById(e);var f=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlPanelTabbedPeer._TAB_FOOTER);this._footerDiv=d.getElementById(f);var g=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlPanelTabbedPeer._TAB_VERTICAL);this._vertDiv=d.getElementById(g);
var h=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlPanelTabbedPeer._TAB_VERTICAL_CONTAINER);this._tabsParentDiv=d.getElementById(h);this._toggleTextIconId=AdfRichUIPeer.CreateSubId(g,AdfDhtmlPanelTabbedPeer._TAB_SUB_ID_TOGGLE_ICON);e="conveyorBelt"==AdfDhtmlPanelTabbedPeer._compressedLayoutMode?AdfRichUIPeer.CreateSubId(e,"cbc"):AdfRichUIPeer.CreateSubId(e,"oc");this._headerTabsDiv=AdfAgent.AGENT.getElementById(e);f="conveyorBelt"==AdfDhtmlPanelTabbedPeer._compressedLayoutMode?AdfRichUIPeer.CreateSubId(f,
"cbc"):AdfRichUIPeer.CreateSubId(f,"oc");this._footerTabsDiv=AdfAgent.AGENT.getElementById(f);f=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlPanelTabbedPeer._TAB_BODY_OUTER);this._bodyOuterDiv=d.getElementById(f);f=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlPanelTabbedPeer._TAB_BODY_INNER);this._bodyInnerDiv=d.getElementById(f);d=AdfRichUIPeer.CreateSubId(g,"cbc");this._verticalTabsDiv=this.IsVerticalConveyorSupported()?AdfAgent.AGENT.getElementById(d):this._vertDiv;this._stretchedOnLastResize=
!0;AdfPage.PAGE.__registerDescendantResizeNotifyComponent(a)};
AdfDhtmlPanelTabbedPeer.prototype.BindToComponent=function(a,b){AdfDhtmlPanelTabbedPeer.superclass.BindToComponent.call(this,a,b);var d=AdfDhtmlPanelTabbedPeer.GetRecentTabClientId();if(null!=d){var e,f;1==AdfDhtmlPanelTabbedPeer.IsRecentTabOnTheBelowBar()?(e=AdfDhtmlPanelTabbedPeer._ANCHOR_SUB_ID_BELOW,f=AdfDhtmlPanelTabbedPeer._ANCHOR_SUB_ID_ABOVE):(e=AdfDhtmlPanelTabbedPeer._ANCHOR_SUB_ID_ABOVE,f=AdfDhtmlPanelTabbedPeer._ANCHOR_SUB_ID_BELOW);this._selectedChildId=d;e=AdfRichUIPeer.CreateSubId(d,
e);e=AdfAgent.AGENT.getElementById(e);null==e&&(e=AdfRichUIPeer.CreateSubId(d,f),e=AdfAgent.AGENT.getElementById(e));null!=e&&AdfFocusUtils.focusElement(e);AdfDhtmlPanelTabbedPeer._recentTabClientId=null;AdfDhtmlPanelTabbedPeer._recentTabOnTheBelowBar=null}};AdfDhtmlPanelTabbedPeer.prototype.HandleComponentMouseOver=function(a){this._handleIcon(a,!0,!1)};AdfDhtmlPanelTabbedPeer.prototype.HandleComponentMouseDown=function(a){this._handleIcon(a,!1,!0)};
AdfDhtmlPanelTabbedPeer.prototype.HandleComponentMouseUp=function(a){this._handleIcon(a,!1,!1)};AdfDhtmlPanelTabbedPeer.prototype.HandleComponentMouseOut=function(a){this._handleIcon(a,!1,!1)};
AdfDhtmlPanelTabbedPeer.prototype.HandleComponentKeyUp=function(a){var b=a.getNativeEvent(),d=a.getKeyCode(),e=a.getNativeEventTarget();a.isCanceled()||(b.ctrlKey&&b.altKey&&d==AdfKeyStroke.F4_KEY?(a=this._getCurrencyFromDomElement(e,this.getDomElement()),null!=a&&(b=AdfPage.PAGE.findComponent(a),!b.getDisabled()&&this._canRemove(a)&&(this._saveAndRemoveCompressedLayout(),AdfFocusUtils.focusNextTabStop(e,null,!0),AdfItemEvent.queueItemRemoveEvent(b)))):d==AdfKeyStroke.ARROWUP_KEY||d==AdfKeyStroke.ARROWLEFT_KEY?
this._isTabLink(e)&&((e=AdfFocusUtils.getPreviousFocusableDescendant(this._getTabContainer(),e))||(e=AdfFocusUtils.getLastFocusableDescendant(this._getTabContainer())),e&&(e.focus(),this._hasConveyorBeltSupport()&&this._getConveyorBeltSupport().handleFocusChange(),a.cancel())):d!=AdfKeyStroke.ARROWDOWN_KEY&&d!=AdfKeyStroke.ARROWRIGHT_KEY||!this._isTabLink(e)||((e=AdfFocusUtils.getNextFocusableDescendant(this._getTabContainer(),e))||(e=AdfFocusUtils.getFirstFocusableDescendant(this._getTabContainer())),
e&&(e.focus(),this._hasConveyorBeltSupport()&&this._getConveyorBeltSupport().handleFocusChange(),a.cancel())))};AdfDhtmlPanelTabbedPeer.prototype._getTabContainer=function(){return this._vertDiv?this._vertDiv:null==AdfAgent.AGENT.getAttribute(this._headerDiv,AdfDhtmlPanelTabbedPeer._EXPANDO_DISCLOSED_TAB_ID)?this._footerDiv:this._headerDiv};
AdfDhtmlPanelTabbedPeer.prototype._isTabLink=function(a){if(null==a)return!1;var b=a.id;if(null==b)return!1;b=b.split("::");if(1>=b.length)return!1;b=b[b.length-1];return b!=AdfDhtmlPanelTabbedPeer._ANCHOR_SUB_ID_ABOVE&&b!=AdfDhtmlPanelTabbedPeer._ANCHOR_SUB_ID_BELOW||null==this._getCurrencyFromDomElement(a,this.getDomElement())?!1:!0};
AdfDhtmlPanelTabbedPeer.prototype.HandleComponentClick=function(a){if(!a.isCanceled()&&a.isLeftButtonPressed()){var b=this.getComponent(),d=a.getNativeEventTarget();if("1"==AdfAgent.AGENT.getExpandoProperty(d,AdfDhtmlPanelTabbedPeer._EXPANDO_COMPRESSED_LAYOUT_LINK))this._selectTab(d),a.cancel();else if(this._isOnTabTextToggleButton(d))this.toggleTabText(),a.cancel();else{var e=this._getCurrencyFromDomElement(d,this.getDomElement());if(null!=e&&(a.cancel(),a=AdfPage.PAGE.findComponent(e),!a.getDisabled()))if(this._isOnRemoveButton(e,
d))this._canRemove(e)&&(this.hideAllPopups(b),this._saveAndRemoveCompressedLayout(),d.parentNode.className&&d.parentNode.className!=AdfDhtmlPanelTabbedPeer._compressedLayoutElementStyleClass||AdfFocusUtils.focusNextTabStop(d,null,!0),AdfItemEvent.queueItemRemoveEvent(a));else{var f=this.GetOldDisclosedChild(b);if(a!=f){var d=d.id,g=d.length-AdfDhtmlPanelTabbedPeer._ANCHOR_SUB_ID_BELOW_LENGTH,h=!1;0<=g&&(h=g==d.lastIndexOf(AdfDhtmlPanelTabbedPeer._ANCHOR_SUB_ID_BELOW,g));AdfDhtmlPanelTabbedPeer.SetRecentTabInfo(e,
h);this._saveAndRemoveCompressedLayout();(e=this.QueueClientDisclosureChanges(f,a))&&e.isCanceled()&&this._updateOverflow(0);this.NewTabSelected(b)}else this.TabReselected(b,a)}}}};AdfDhtmlPanelTabbedPeer.prototype.HandleComponentFocus=function(a){this._handleTabFocusOrBlur(a,!0)};AdfDhtmlPanelTabbedPeer.prototype.HandleComponentBlur=function(a){this._handleTabFocusOrBlur(a,!1)};AdfDhtmlPanelTabbedPeer.prototype.TabReselected=function(a,b){};AdfDhtmlPanelTabbedPeer.prototype.NewTabSelected=function(a){};
AdfDhtmlPanelTabbedPeer.prototype.GetBodyOuterElement=function(){return this._bodyOuterDiv};AdfDhtmlPanelTabbedPeer.prototype.GetBodyInnerElement=function(){return this._bodyInnerDiv};AdfDhtmlPanelTabbedPeer.prototype.GetVertTabsElement=function(){return this._vertDiv};AdfDhtmlPanelTabbedPeer.prototype.UseInvertedRenderingPosition=function(){return!1};
AdfDhtmlPanelTabbedPeer.prototype._getRenderingPosition=function(a){a=a.getPosition();return this.UseInvertedRenderingPosition()?AdfDhtmlPanelTabbedPeer._INVERTED_POSITION_MAP[a]:a};AdfDhtmlPanelTabbedPeer.prototype._hasSubIdInId=function(a,b,d){a=a.id;if(null==a)return!1;a=a.split("::");if(1>=a.length)return!1;a=a[a.length-1];return!a||a!=b&&a!=d?!1:!0};
AdfDhtmlPanelTabbedPeer.prototype._findChildFromSubId=function(a,b,d){return this._hasSubIdInId(a,b,d)&&(a=this._getCurrencyFromDomElement(a,this.getDomElement()),null!=a)?AdfPage.PAGE.findComponent(a):null};AdfDhtmlPanelTabbedPeer.prototype._displayIcon=function(a,b,d){d||(d=b.getIcon());d&&(a.src=d)};
AdfDhtmlPanelTabbedPeer.prototype._handleIcon=function(a,b,d){a=a.getNativeEventTarget();var e=this._findChildFromSubId(a,AdfDhtmlPanelTabbedPeer.TAB_SUB_ID_ICON);null==e&&(e=this._findChildFromSubId(a,AdfDhtmlPanelTabbedPeer.TAB_SUB_ID_ICON_BELOW));e&&(e.getDisabled()||AdfRichUIPeer.isInlineSVGIcon(e)||(b?this._displayIcon(a,e,e.getHoverIcon()):d?this._displayIcon(a,e,e.getDepressedIcon()):e.getDisclosed()?this._displayIcon(a,e,e.getDepressedIcon()):this._displayIcon(a,e,e.getIcon())))};
AdfDhtmlPanelTabbedPeer.prototype._handleTabFocusOrBlur=function(a,b){a.cancel();var d=a.getNativeEventTarget(),e=d.id;null==e||(e=e.split("::"),1>=e.length||(e=e[e.length-1],e!=AdfDhtmlPanelTabbedPeer._ANCHOR_SUB_ID_ABOVE&&e!=AdfDhtmlPanelTabbedPeer._ANCHOR_SUB_ID_BELOW))||(d=this._getCurrencyFromDomElement(d,this.getDomElement()),null!=d&&(d=AdfRichUIPeer.createSubId(d,e==AdfDhtmlPanelTabbedPeer._ANCHOR_SUB_ID_ABOVE?AdfDhtmlPanelTabbedPeer.TAB_SUB_ID_ABOVE:AdfDhtmlPanelTabbedPeer.TAB_SUB_ID_BELOW),
d=AdfAgent.getAgent().getElementById(d),null!=d&&(b?AdfDomUtils.addCSSClassName(d,AdfDhtmlPanelTabbedPeer._HIGHLIGHTED_STYLE_CLASS):AdfDomUtils.removeCSSClassName(d,AdfDhtmlPanelTabbedPeer._HIGHLIGHTED_STYLE_CLASS))))};AdfDhtmlPanelTabbedPeer.prototype.needsResizeNotify=function(a){return!0};
AdfDhtmlPanelTabbedPeer.prototype.ResizeNotify=function(a,b,d,e){var f=this.getComponent();this._isVertical(f)?b!=e&&(this._resizeVerticalTabs(),this._updateOverflow(e)):a!=d&&("ellipsis"==this.getComponent().getTruncationStyle()?this._resizeTabs(a,d):this._updateOverflow(d))};
AdfDhtmlPanelTabbedPeer.prototype.ComponentVerticalTabModeChanged=function(a,b,d,e){a=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlPanelTabbedPeer._TAB_VERTICAL_CONTAINER);a=AdfAgent.AGENT.getElementById(a);if(!a)return!0;AdfDomUtils.addOrRemoveCSSClassName("iconOnly"==d,this.getDomElement(),"p_AFIconified");AdfDomUtils.addOrRemoveCSSClassName("iconOnly"==d,a,"p_AFIconified");if(a=AdfAgent.AGENT.getElementById(this._toggleTextIconId))d="iconOnly"==d?"af_panelTabbed.TIP_SHOW_TAB_TEXT":"af_panelTabbed.TIP_HIDE_TAB_TEXT",
a.title=AdfPage.PAGE.getLookAndFeel().getTranslatedString(d);this._resizeVerticalTabs(!0);return!0};
AdfDhtmlPanelTabbedPeer.prototype._updateOverflow=function(a){var b=this.getComponent(),d=this._getRenderingPosition(b);if("above"==d||"both"==d){var e=AdfRichUIPeer.CreateSubId(b.getClientId(),AdfDhtmlPanelTabbedPeer._TAB_HEADER),f=this._getChildElements(e,this._headerTabsDiv);this._resizeOverflow(e,f,a,!0)}if("below"==d||"both"==d)d=AdfRichUIPeer.CreateSubId(b.getClientId(),AdfDhtmlPanelTabbedPeer._TAB_FOOTER),e=this._getChildElements(d,this._footerTabsDiv),this._resizeOverflow(d,e,a,!1);this._isVertical(b)&&
(b=AdfRichUIPeer.CreateSubId(b.getClientId(),AdfDhtmlPanelTabbedPeer._TAB_VERTICAL),d=this._getChildElements(b,this._verticalTabsDiv),this._resizeVerticalConveyor(b,d,a))};
AdfDhtmlPanelTabbedPeer.prototype._resizeTabs=function(a,b){AdfLogger.LOGGER.finer("Available width for tabs changed from "+a+" to "+b);var d=this.getComponent(),e=this._getRenderingPosition(d);if("above"==e||"both"==e){var f=AdfRichUIPeer.CreateSubId(d.getClientId(),AdfDhtmlPanelTabbedPeer._TAB_HEADER);this._resizeHeaderOrFooterTabs(f,a,b,!0)}if("below"==e||"both"==e)d=AdfRichUIPeer.CreateSubId(d.getClientId(),AdfDhtmlPanelTabbedPeer._TAB_FOOTER),this._resizeHeaderOrFooterTabs(d,a,b,!1)};
AdfDhtmlPanelTabbedPeer.prototype._resizeVerticalTabs=function(a){var b=this._getRenderingPosition(this.getComponent()),d=this.GetBodyOuterElement();if(!d.style.width||a){a=!1;var e=AdfPage.PAGE.getLocaleContext().isRightToLeft();if("left"==b||"start"==b&&!e||"end"==b&&e)a=!0;b=this.GetVertTabsElement();a?d.style.left=b.offsetWidth+"px":d.style.right=b.offsetWidth+"px"}};
AdfDhtmlPanelTabbedPeer.prototype._resizeHeaderOrFooterTabs=function(a,b,d,e){if(!this.GetVertTabsElement()){d=e?this._headerTabsDiv:this._footerTabsDiv;var f=this._getChildElements(a,d);0!=f.length&&this._layoutTabs(b,d.offsetWidth,a,f,e)}};
AdfDhtmlPanelTabbedPeer.prototype.ComponentRemoved=function(a){this._removeCompressedLayoutSupport();delete this._headerDiv;delete this._headerTabsDiv;delete this._footerDiv;delete this._footerTabsDiv;delete this._bodyOuterDiv;delete this._bodyInnerDiv;AdfPage.PAGE.__unregisterDescendantResizeNotifyComponent(a);AdfDhtmlPanelTabbedPeer.superclass.ComponentRemoved.call(this,a)};
AdfDhtmlPanelTabbedPeer.prototype._getOverflowSupport=function(a,b,d){a=new AdfOverflowSupport(a,this,"both",d);for(d=0;d<b.length;d++){var e=b[d];1==e.nodeType&&(a.createStep(),a.addElement(e),a.addOverflowElement(this._createCompressedLayoutPopupElement(e)))}return a};
AdfDhtmlPanelTabbedPeer.prototype._getOverflowDroplistSupport=function(a,b,d){a=new AdfOverflowSupport(a,this,"droplist",d);d=[];for(var e=0;e<b.length;e++){var f=b[e];1==f.nodeType&&(a.createStep(),a.addElement(f),"none"!=f.style.display&&(a.addOverflowElement(this._createCompressedLayoutPopupElement(f)),d.push(this._createCompressedLayoutPopupElement(f))))}a.addDropListElements(d);return a};
AdfDhtmlPanelTabbedPeer.prototype._createHorizontalConveyorBeltSupport=function(a,b){for(var d=AdfConveyorBeltSupport.createHorizontalSupport(a,this),e=[],f=AdfRichUIPeer.CreateSubId(a,"cbs"),g=0;g<b.length;g++){var h=b[g];1==h.nodeType&&h.getAttribute("id")!=f&&"none"!=h.style.display&&e.push(this._createCompressedLayoutPopupElement(h))}d.addDropListElements(e);if(e=AdfDhtmlPanelTabbedPeer._conveyorBeltFirstItem)d.setFirstItemDisplayed(e),AdfDhtmlPanelTabbedPeer._conveyorBeltFirstItem=null;return d};
AdfDhtmlPanelTabbedPeer.GetRecentTabClientId=function(){return AdfDhtmlPanelTabbedPeer._recentTabClientId};AdfDhtmlPanelTabbedPeer.IsRecentTabOnTheBelowBar=function(){return AdfDhtmlPanelTabbedPeer._recentTabOnTheBelowBar};AdfDhtmlPanelTabbedPeer.SetRecentTabInfo=function(a,b){AdfDhtmlPanelTabbedPeer._recentTabClientId=a;AdfDhtmlPanelTabbedPeer._recentTabOnTheBelowBar=b};
AdfDhtmlPanelTabbedPeer.prototype._changeSelected=function(a,b,d,e,f){d=AdfRichUIPeer.CreateSubId(b,d);if(d=AdfAgent.getAgent().getElementById(d))AdfDomUtils.addOrRemoveCSSClassName(f,d,"p_AFSelected"),b=AdfRichUIPeer.CreateSubId(b,e),(b=AdfAgent.getAgent().getElementById(b))&&!AdfRichUIPeer.isInlineSVGIcon(a)&&(f?this._displayIcon(b,a,a.getDepressedIcon()):this._displayIcon(b,a,a.getIcon()))};
AdfDhtmlPanelTabbedPeer.prototype.QueueClientDisclosureChanges=function(a,b){var d=null!=a;if(!d&&!this.IsDisclosedTabRequired()||1==a.getDisclosed()){var e=this.getComponent();if("immediate"==e.getContentDelivery())AdfPage.PAGE.isAttachmentMode()?(d&&(d=a.getClientId(),this._changeSelected(a,d,AdfDhtmlPanelTabbedPeer.TAB_SUB_ID_ABOVE,AdfDhtmlPanelTabbedPeer.TAB_SUB_ID_ICON,!1),this._changeSelected(a,d,AdfDhtmlPanelTabbedPeer.TAB_SUB_ID_BELOW,AdfDhtmlPanelTabbedPeer.TAB_SUB_ID_ICON_BELOW,!1),d=a.getPeer(),
d.bind(a),d.getDomElement().parentNode.style.display="none",a.setDisclosed(!1),this._setOldDisclosedChild(e,null)),b&&(d=b.getPeer(),d.bind(b),d.getDomElement().parentNode.style.display="",d=b.getClientId(),this._changeSelected(b,d,AdfDhtmlPanelTabbedPeer.TAB_SUB_ID_ABOVE,AdfDhtmlPanelTabbedPeer.TAB_SUB_ID_ICON,!0),this._changeSelected(b,d,AdfDhtmlPanelTabbedPeer.TAB_SUB_ID_BELOW,AdfDhtmlPanelTabbedPeer.TAB_SUB_ID_ICON_BELOW,!0),b.setDisclosed(!0),this._setOldDisclosedChild(e,b.getClientId())),AdfPage.PAGE.doResizeNotify(e)):
AdfLogger.LOGGER.warning("PanelTabbed contentDelivery\x3dimmediate is not supported outside of attachment mode. Disclose ability is disabled while in this state.");else{if(d)return e=a.getPeer(),e.bind(a),e.queueDisclosureEvent(!1,!0,b);e=b.getPeer();e.bind(b);return e.queueDisclosureEvent(!0,!0)}}else AdfLogger.LOGGER.severe("Unexpected panelTabbed showDetailItem disclosure state for queueing client events")};AdfDhtmlPanelTabbedPeer.prototype.IsDisclosedTabRequired=function(a){return!0};
AdfDhtmlPanelTabbedPeer.prototype.IsVerticalConveyorSupported=function(a){return!0};
AdfDhtmlPanelTabbedPeer.prototype._createCompressedLayoutPopupElement=function(a){var b=AdfAgent.AGENT,d=b.getAttribute(a,AdfDhtmlPanelTabbedPeer._EXPANDO_ROWKEY_ATTRIBUTE),e=a.getElementsByTagName("a")[0],f=a.getElementsByTagName("a")[1],g=a.getElementsByTagName("img")[0],h=AdfPage.PAGE.getLookAndFeel(),k;g&&(g=g.cloneNode(!0),g.id&&(g.id+=AdfDhtmlPanelTabbedPeer._TAB_ID_CONVEYOR_SUFFIX));e&&-1==e.className.indexOf("p_AFDisabled")?(e=e.cloneNode(!0),e.id&&(e.id+=AdfDhtmlPanelTabbedPeer._TAB_ID_CONVEYOR_SUFFIX),
e._rowKey=d,b.setExpandoProperty(e,AdfDhtmlPanelTabbedPeer._EXPANDO_COMPRESSED_LAYOUT_LINK,"1"),k=AdfDhtmlPanelTabbedPeer._compressedLayoutElementStyleClass,null==k&&(k="conveyorBelt"==AdfDhtmlPanelTabbedPeer._compressedLayoutMode?h.getStyleClass("AFConveyorBeltElement"):h.getStyleClass("AFOverflowElement"),AdfDhtmlPanelTabbedPeer._compressedLayoutElementStyleClass=k)):(k=e.innerHTML,e=a.ownerDocument.createElement("div"),e.innerHTML=k,k=AdfDhtmlPanelTabbedPeer._compressedLayoutElementDisabledStyleClass,
null==k&&(k="conveyorBelt"==AdfDhtmlPanelTabbedPeer._compressedLayoutMode?h.getStyleClass("AFConveyorBeltElementDisabled"):h.getStyleClass("AFOverflowElementDisabled"),AdfDhtmlPanelTabbedPeer._compressedLayoutElementDisabledStyleClass=k));f&&(f=f.cloneNode(!0),f.id&&(f.id+=AdfDhtmlPanelTabbedPeer._TAB_ID_CONVEYOR_SUFFIX));h=a.ownerDocument.createElement("table");h.cellPadding=0;h.cellSpacing=0;h.style.width="100%";var l=h.insertRow(-1);b.setAttribute(l,AdfDhtmlPanelTabbedPeer._EXPANDO_ROWKEY_ATTRIBUTE,
d);b=l.insertCell(-1);g&&b.appendChild(g);g=l.insertCell(-1);g.style.width="100%";b=a.ownerDocument.createElement("div");b.className=k;g.appendChild(b);b.appendChild(e);e=l.insertCell(-1);f&&(a=a.ownerDocument.createElement("div"),a.className=k,e.appendChild(a),a.appendChild(f));return h};
AdfDhtmlPanelTabbedPeer.prototype._selectTab=function(a){var b=this.getComponent();this.hideAllPopups(b);if(a=a._rowKey){var d=AdfPage.PAGE.findComponent(a),b=this.GetOldDisclosedChild(b);d.getDisabled()||(d==b?this._hasConveyorBeltSupport()&&this._handleConveyorBeltNewSelection(d.getClientId()):(AdfDhtmlPanelTabbedPeer.SetRecentTabInfo(a,null),this._saveAndRemoveCompressedLayout(),(b=this.QueueClientDisclosureChanges(b,d))&&b.isCanceled()&&this._updateOverflow(0)))}};
AdfDhtmlPanelTabbedPeer.prototype._saveAndRemoveCompressedLayout=function(){var a=this._getConveyorBeltSupport();a&&(AdfDhtmlPanelTabbedPeer._conveyorBeltFirstItem=a.getFirstItemDisplayed());this._removeCompressedLayoutSupport()};AdfDhtmlPanelTabbedPeer.prototype._hasConveyorBeltSupport=function(){return null!=this._headerConveyorBeltSupport||null!=this._footerConveyorBeltSupport||null!=this._verticalConveyorBeltSupport};
AdfDhtmlPanelTabbedPeer.prototype._getConveyorBeltSupport=function(){if(null!=this._headerConveyorBeltSupport)return this._headerConveyorBeltSupport;if(null!=this._footerConveyorBeltSupport)return this._footerConveyorBeltSupport;if(null!=this._verticalConveyorBeltSupport)return this._verticalConveyorBeltSupport};
AdfDhtmlPanelTabbedPeer.prototype._handleConveyorBeltNewSelection=function(a){if(this._hasConveyorBeltSupport()){var b=AdfRichUIPeer.createSubId(a,this._headerConveyorBeltSupport||this._verticalConveyorBeltSupport?AdfDhtmlPanelTabbedPeer.TAB_SUB_ID_ABOVE:AdfDhtmlPanelTabbedPeer.TAB_SUB_ID_BELOW);a=AdfAgent.getAgent().getElementById(b);for(var d=this._getConveyorBeltSupport(),e=0,b=this._getChildElements(b,this._getTabsDiv()),f=0;f<b.length;f++)if(1==b[f].nodeType){if(b[f]==a){d.scrollNewSelectedItemIntoView(e);
this._headerConveyorBeltSupport&&this._footerConveyorBeltSupport&&this._footerConveyorBeltSupport.scrollNewSelectedItemIntoView(e);break}e++}}};AdfDhtmlPanelTabbedPeer.prototype._getTabsDiv=function(){if(this._cbTabsDiv)return this._cbTabsDiv;this._headerConveyorBeltSupport?this._cbTabsDiv=this._headerTabsDiv:this._footerConveyorBeltSupport?this._cbTabsDiv=this._footerTabsDiv:this._verticalConveyorBeltSupport&&(this._cbTabsDiv=this._vertDiv)};
AdfDhtmlPanelTabbedPeer.prototype._getChildren=function(){var a=AdfAgent.getAgent(),b=this.getComponent(),d=[],e=this._getRenderingPosition(b),f="above"==e||"both"==e?this._headerTabsDiv:this._footerTabsDiv,b="above"==e||"both"==e?AdfRichUIPeer.CreateSubId(b.getClientId(),AdfDhtmlPanelTabbedPeer._TAB_HEADER):AdfRichUIPeer.CreateSubId(b.getClientId(),AdfDhtmlPanelTabbedPeer._TAB_FOOTER);if(this.getDomElement())for(f=this._getChildElements(b,f),b=0;b<f.length;b++)1==f[b].nodeType&&(e=a.getAttribute(f[b],
AdfDhtmlPanelTabbedPeer._EXPANDO_ROWKEY_ATTRIBUTE),(e=AdfPage.PAGE.findComponent(e))&&d.push(e));return d};AdfDhtmlPanelTabbedPeer.prototype._getChildElements=function(a,b){for(var d=b.childNodes,e=[],f="conveyorBelt"==AdfDhtmlPanelTabbedPeer._compressedLayoutMode,g=f?AdfRichUIPeer.CreateSubId(a,"cbs"):null,h=d.length,k=0;k<h;k++){var l=d[k];1!=l.nodeType||f&&l.getAttribute("id")==g||e.push(l)}return e};
AdfDhtmlPanelTabbedPeer.prototype._getCurrencyFromDomElement=function(a,b){AdfAssert.assertDomElement(a);var d=a,e=AdfAgent.getAgent();if(null==d||1!=d.nodeType)return null;for(var f=e.getAttribute(d,AdfDhtmlPanelTabbedPeer._EXPANDO_ROWKEY_ATTRIBUTE);null==f;){if(null==d||d==b)return null;d=d.parentNode;if(null==d||1!=d.nodeType)return null;f=e.getAttribute(d,AdfDhtmlPanelTabbedPeer._EXPANDO_ROWKEY_ATTRIBUTE)}return f};
AdfDhtmlPanelTabbedPeer.prototype.GetOldDisclosedChild=function(a){a=AdfAgent.getAgent();var b=null;this._vertDiv?b=a.getAttribute(this._vertDiv,AdfDhtmlPanelTabbedPeer._EXPANDO_DISCLOSED_TAB_ID):(b=a.getAttribute(this._headerDiv,AdfDhtmlPanelTabbedPeer._EXPANDO_DISCLOSED_TAB_ID),null==b&&(b=a.getAttribute(this._footerDiv,AdfDhtmlPanelTabbedPeer._EXPANDO_DISCLOSED_TAB_ID)));return AdfPage.PAGE.findComponent(b)};
AdfDhtmlPanelTabbedPeer.prototype._setOldDisclosedChild=function(a,b){var d=AdfAgent.getAgent();this._vertDiv?d.setAttribute(this._vertDiv,AdfDhtmlPanelTabbedPeer._EXPANDO_DISCLOSED_TAB_ID,b):null==d.getAttribute(this._headerDiv,AdfDhtmlPanelTabbedPeer._EXPANDO_DISCLOSED_TAB_ID)?d.setAttribute(this._footerDiv,AdfDhtmlPanelTabbedPeer._EXPANDO_DISCLOSED_TAB_ID,b):d.setAttribute(this._headerDiv,AdfDhtmlPanelTabbedPeer._EXPANDO_DISCLOSED_TAB_ID,b)};
AdfDhtmlPanelTabbedPeer.prototype._canRemove=function(a){a=AdfPage.PAGE.findComponent(a);if(a.getDisabled()||a.getRemove&&(a=a.getRemove())&&("no"==a||"disabled"==a))return!1;a=this.getComponent().getTabRemoval();if("none"==a)return!1;if("all"==a)return!0;if("allExceptLast"==a)return 1<this._getChildren().length;AdfLogger.LOGGER.warning("Unexpected panelTabbed tabRemoval type: "+a);return!1};
AdfDhtmlPanelTabbedPeer.prototype._isOnRemoveButton=function(a,b){var d=AdfRichUIPeer.createSubId(a,AdfDhtmlPanelTabbedPeer._REMOVE_ICON_ABOVE_ID),e=AdfRichUIPeer.createSubId(a,AdfDhtmlPanelTabbedPeer._REMOVE_ICON_BELOW_ID);if(b.id&&-1<b.id.lastIndexOf(d)||-1<b.id.lastIndexOf(e))return!0;var f=b.parentNode;return(f=f&&f.id)&&(-1<f.lastIndexOf(d)||-1<f.lastIndexOf(e))};
AdfDhtmlPanelTabbedPeer.prototype._isOnTabTextToggleButton=function(a){return a.id&&a.id==this._toggleTextIconId?!0:(a=(a=a.parentNode)&&a.id)&&a.id==this._toggleTextIconId};AdfDhtmlPanelTabbedPeer.prototype.toggleTabText=function(){var a=this.getComponent();"iconOnly"==a.getProperty("verticalTabMode")?a.setProperty("verticalTabMode","iconAndText"):a.setProperty("verticalTabMode","iconOnly")};
AdfDhtmlPanelTabbedPeer.prototype._getTabContentElement=function(a){a=a.getAttribute("id");a=AdfRichUIPeer.CreateSubId(a,AdfDhtmlPanelTabbedPeer._TAB_CONTENT);return AdfAgent.AGENT.getElementById(a)};AdfDhtmlPanelTabbedPeer.prototype._getEllipsisElement=function(a){a=a.getAttribute("id");a=AdfRichUIPeer.CreateSubId(a,AdfDhtmlPanelTabbedPeer._ELLIPSIS_SUBID);return AdfAgent.AGENT.getElementById(a)};
AdfDhtmlPanelTabbedPeer.prototype._layoutTabs=function(a,b,d,e,f){a=e.length;var g=this.getComponent();this._maxTabSize||(this._maxTabSize=g.getMaxTabSize(),this._maxTabSize=null==this._maxTabSize||"infinity"==this._maxTabSize?0:parseFloat(this._maxTabSize));this._minTabSize||(this._minTabSize=g.getMinTabSize(),this._minTabSize=parseFloat(this._minTabSize),null==this._minTabSize&&(this._minTabSize=32));if(0<this._maxTabSize&&this._minTabSize>this._maxTabSize)AdfLogger.LOGGER.warning("Minimum tab width should not be greater than maximum tab width: min\x3d"+
this._minTabSize+", max\x3d "+this._maxTabSize);else{if(!this._overflowLimit){this._overflowLimit=this._minTabSize*a;!this._tabOverlapWidth&&1<a&&(this._tabOverlapWidth=e[0].offsetWidth-(e[1].offsetLeft-e[0].offsetLeft));for(g=0;g<a;g++){var h=e[g];tabContentElement=this._getTabContentElement(h);this._getEllipsisElement(h).style.display="none";this._overflowLimit+=h.offsetWidth-tabContentElement.offsetWidth-this._tabOverlapWidth}this._tabOverlapWidth&&(this._overflowLimit+=this._tabOverlapWidth)}b<
this._overflowLimit?(this._setTabSizes(e,this._minTabSize),this._resizeOverflow(d,e,b,f)):(b=Math.floor((b-this._tabOverlapWidth)/a),this._hideOverflow(),this._setTabSizes(e,b,!0))}};
AdfDhtmlPanelTabbedPeer.prototype._setTabSizes=function(a,b,d){for(var e=!1,f=0;f<a.length;f++){var g=a[f];tabContentElement=this._getTabContentElement(g);var h=this._getEllipsisElement(g),k=tabContentElement.style.width;tabContentElement.style.width="";tabContentElement.style.overflow="";h.style.display="none";g=g.offsetWidth;g=d?b-(g-tabContentElement.offsetWidth)+this._tabOverlapWidth:b;0<this._maxTabSize&&g>this._maxTabSize&&(g=this._maxTabSize);tabContentElement.offsetWidth>g&&(h.style.display=
"inline",tabContentElement.style.overflow="hidden",g-=h.offsetWidth);tabContentElement.style.width=g+"px";e||k==tabContentElement.style.width||(e=!0)}return e};
AdfDhtmlPanelTabbedPeer.prototype._resizeVerticalConveyor=function(a,b,d){!this._verticalConveyorBeltSupport&&this.IsVerticalConveyorSupported()&&(b=this.getComponent(),b=AdfRichUIPeer.CreateSubId(b.getClientId(),AdfDhtmlPanelTabbedPeer._TAB_VERTICAL_CONTAINER),this._verticalConveyorBeltSupport=AdfConveyorBeltSupport.createVerticalSupport(b,a,this),a=AdfDhtmlPanelTabbedPeer._conveyorBeltFirstItem)&&(this._verticalConveyorBeltSupport.setFirstItemDisplayed(a),AdfDhtmlPanelTabbedPeer._conveyorBeltFirstItem=
null);this._verticalConveyorBeltSupport&&this._verticalConveyorBeltSupport.handleResize()};
AdfDhtmlPanelTabbedPeer.prototype._resizeOverflow=function(a,b,d,e){var f=AdfDhtmlPanelTabbedPeer._compressedLayoutMode;"overflow"==f?e?(this._headerOverflowSupport||(this._headerOverflowSupport=this._getOverflowSupport(a,b,"after")),this._headerOverflowSupport&&this._headerOverflowSupport.handleResize()):(this._footerOverflowSupport||(this._footerOverflowSupport=this._getOverflowSupport(a,b,"before")),this._footerOverflowSupport&&this._footerOverflowSupport.handleResize()):"overflow-droplist"==f?
e?(this._headerOverflowSupport||(this._headerOverflowSupport=this._getOverflowDroplistSupport(a,b,"after")),this._headerOverflowSupport&&this._headerOverflowSupport.handleResize()):(this._footerOverflowSupport||(this._footerOverflowSupport=this._getOverflowDroplistSupport(a,b,"before")),this._footerOverflowSupport&&this._footerOverflowSupport.handleResize()):"conveyorBelt"==f&&(e?(this._headerConveyorBeltSupport||(this._headerConveyorBeltSupport=this._createHorizontalConveyorBeltSupport(a,b,d),this._footerConveyorBeltSupport&&
(this._footerConveyorBeltSupport.registerAdditionalConveyorBeltSupport(this._headerConveyorBeltSupport),this._headerConveyorBeltSupport.registerAdditionalConveyorBeltSupport(this._footerConveyorBeltSupport))),this._headerConveyorBeltSupport&&this._headerConveyorBeltSupport.handleResize()):(this._footerConveyorBeltSupport||(this._footerConveyorBeltSupport=this._createHorizontalConveyorBeltSupport(a,b,d),this._headerConveyorBeltSupport&&(this._footerConveyorBeltSupport.registerAdditionalConveyorBeltSupport(this._headerConveyorBeltSupport),
this._headerConveyorBeltSupport.registerAdditionalConveyorBeltSupport(this._footerConveyorBeltSupport))),this._footerConveyorBeltSupport&&this._footerConveyorBeltSupport.handleResize()))};
AdfDhtmlPanelTabbedPeer.prototype._hideOverflow=function(){var a=AdfDhtmlPanelTabbedPeer._compressedLayoutMode,b=this.getComponent();this._isVertical(b)&&this._verticalConveyorBeltSupport&&this._verticalConveyorBeltSupport.handleResize();"conveyorBelt"==a?(this._headerConveyorBeltSupport&&this._headerConveyorBeltSupport.handleResize(),this._footerConveyorBeltSupport&&this._footerConveyorBeltSupport.handleResize()):(this._headerOverflowSupport&&this._headerOverflowSupport.removeAllItemsFromOverflow(),
this._footerOverflowSupport&&this._footerOverflowSupport.removeAllItemsFromOverflow())};
AdfDhtmlPanelTabbedPeer.prototype._removeCompressedLayoutSupport=function(){this._headerOverflowSupport&&(this._headerOverflowSupport.removeOverflowSupport(!0),this._headerOverflowSupport=null);this._footerOverflowSupport&&(this._footerOverflowSupport.removeOverflowSupport(!0),this._footerOverflowSupport=null);this._headerConveyorBeltSupport&&(this._headerConveyorBeltSupport.removeConveyorBeltSupport(),this._headerConveyorBeltSupport=null);this._footerConveyorBeltSupport&&(this._footerConveyorBeltSupport.removeConveyorBeltSupport(),
this._footerConveyorBeltSupport=null);this._verticalConveyorBeltSupport&&(this._verticalConveyorBeltSupport.removeConveyorBeltSupport(),this._verticalConveyorBeltSupport=null)};AdfDhtmlPanelTabbedPeer.prototype.getContainerId=function(a){return AdfRichUIPeer.createSubId(this.getComponent().getClientId(),AdfDhtmlPanelTabbedPeer._TAB_BODY_INNER)};AdfDhtmlPanelTabbedPeer.prototype._isVertical=function(a){a=this._getRenderingPosition(a);return"start"==a||"end"==a||"left"==a||"right"==a};
AdfDhtmlPanelTabbedPeer.prototype._isHorizontal=function(a){return!this._isVertical(a)};
function AdfConveyorBeltSupport(a,b){this.Init(a,b)}AdfObject.createSubclass(AdfConveyorBeltSupport);AdfConveyorBeltSupport.InitClass=function(){AdfConveyorBeltSupport.CONVEYOR_BELT_STYLE_CLASS="p_AFConveyorBelt";AdfConveyorBeltSupport.DEPRESSED_STYLE_CLASS="p_AFDepressed";AdfConveyorBeltSupport.SELECTED_STYLE_CLASS="p_AFSelected";AdfConveyorBeltSupport.DROPLIST_ID="_afrCbDl"};
AdfConveyorBeltSupport.prototype.Init=function(a,b){AdfConveyorBeltSupport.superclass.Init.call(this);this._peer=b;this._container=AdfAgent.AGENT.getElementById(a)};AdfConveyorBeltSupport.createHorizontalSupport=function(a,b){return new AdfConveyorBeltHorizontal(a,b)};AdfConveyorBeltSupport.createVerticalSupport=function(a,b,d){return new AdfConveyorBeltVertical(a,b,d)};AdfConveyorBeltSupport.prototype.removeConveyorBeltSupport=function(){delete this._peer;delete this._container};
AdfConveyorBeltSupport.prototype.registerAdditionalConveyorBeltSupport=function(a){AdfAssert.failedInAbstractFunction()};AdfConveyorBeltSupport.prototype.handleResize=function(){AdfAssert.failedInAbstractFunction()};AdfConveyorBeltSupport.prototype.addDropListElements=function(a){AdfAssert.failedInAbstractFunction()};AdfConveyorBeltSupport.prototype.scrollNewSelectedItemIntoView=function(a){AdfAssert.failedInAbstractFunction()};AdfConveyorBeltSupport.prototype.getFirstItemDisplayed=function(){AdfAssert.failedInAbstractFunction()};
AdfConveyorBeltSupport.prototype.setFirstItemDisplayed=function(a){AdfAssert.failedInAbstractFunction()};AdfConveyorBeltSupport.prototype.handleFocusChange=function(){AdfAssert.failedInAbstractFunction()};AdfConveyorBeltSupport.prototype.GetPeer=function(){return this._peer};AdfConveyorBeltSupport.prototype.GetContainer=function(){return this._container};
function AdfConveyorBeltVertical(a,b,d){this.Init(a,b,d)}AdfObject.createSubclass(AdfConveyorBeltVertical,AdfConveyorBeltSupport);
AdfConveyorBeltVertical.prototype.Init=function(a,b,d){AdfConveyorBeltVertical.superclass.Init.call(this,a,d);a=AdfRichUIPeer.CreateSubId(b,"tcbi");this._topIndicator=AdfAgent.AGENT.getElementById(a);this._initTopButtonEventHandling();a=AdfRichUIPeer.CreateSubId(b,"bcbi");this._bottomIndicator=AdfAgent.AGENT.getElementById(a);this._initBottomButtonEventHandling();a=AdfRichUIPeer.CreateSubId(b,"cbc");this._contentContainer=AdfAgent.AGENT.getElementById(a);d=AdfDomUtils.getChildElements(this._contentContainer);
a=[];for(var e=0;e<d.length;e++){var f=d[e];1==f.nodeType&&"none"!=f.style.display&&a.push(f)}this._itemOffsetTopArray=[];for(d=0;d<a.length;d++)this._itemOffsetTopArray[d]=a[d].offsetTop,AdfDomUtils.containsCSSClassName(a[d],AdfConveyorBeltSupport.SELECTED_STYLE_CLASS)&&(this._selectedItem=d);a=a[a.length-1];this._contentHeight=null==a?0:a.offsetTop+a.offsetHeight;this._initialRender=!0;this._firstItemDisplayed=0;this._buttonHeight=this._getButtonHeight(b);this._toggleButtonHeight=0;b=AdfRichUIPeer.CreateSubId(b,
"toggle");if(b=AdfAgent.AGENT.getElementById(b))this._toggleButtonHeight=b.offsetHeight;this._keepRollingDown=this._keepRollingUp=!1};
AdfConveyorBeltVertical.prototype.removeConveyorBeltSupport=function(){AdfConveyorBeltVertical.superclass.removeConveyorBeltSupport.call(this);var a=AdfAgent.AGENT,b=this._topIndicator;a.removeBubbleEventListener(b,"mousedown",this._topButtonCall);a.removeBubbleEventListener(b,"keydown",this._topButtonCall);a.removeBubbleEventListener(b,"mouseup",this._topButtonMouseUpCall);a.removeBubbleEventListener(b,"mouseout",this._topButtonMouseOutCall);b=this._bottomIndicator;a.removeBubbleEventListener(b,
"mousedown",this._bottomButtonCall);a.removeBubbleEventListener(b,"keydown",this._bottomButtonCall);a.removeBubbleEventListener(b,"mouseup",this._bottomButtonMouseUpCall);a.removeBubbleEventListener(b,"mouseout",this._bottomButtonMouseOutCall);delete this._topIndicator;delete this._bottomIndicator;delete this._contentContainer;delete this._itemOffsetTopArray;delete this._selectedItem;delete this._contentHeight;delete this._initialRender;delete this._firstItemDisplayed;delete this._buttonHeight;delete this._toggleButtonHeight;
delete this._keepRollingUp;delete this._keepRollingDown};AdfConveyorBeltVertical.prototype.registerAdditionalConveyorBeltSupport=function(a){AdfAssert.assert(1,"Method not supported for vertical conveyor belt.")};
AdfConveyorBeltVertical.prototype.handleResize=function(){this._contentContainer.removeAttribute("style");var a=AdfConveyorBeltVertical.superclass.GetContainer.call(this),a=AdfConveyorBeltVertical._getInnerHeight(a);if(this._contentContainer.offsetHeight>a){a=a-this._buttonHeight-this._toggleButtonHeight;0>a&&(a=0);var b=this._contentContainer.scrollTop;this._contentContainer.setAttribute("style","height: "+a+"px;");this._areConveyorBeltIconsDisplayed()?AdfAgent.AGENT.scrollToPos(this._contentContainer,
null,b):(this._setButtonDisplay(!0),this._initialRender&&(this._firstItemDisplayed=this._calculateFirstItemToDisplay()),this._rollConveyor(!0));this._setButtonState()}else this._setButtonDisplay(!1),AdfAgent.AGENT.scrollToPos(this._contentContainer,null,0);this._initialRender&&(this._initialRender=!1)};AdfConveyorBeltVertical.prototype.addDropListElements=function(a){AdfAssert.assert(1,"Method not supported for vertical conveyor belt.")};
AdfConveyorBeltVertical.prototype.scrollNewSelectedItemIntoView=function(a){AdfAssert.assert(1,"Method not supported for vertical conveyor belt.")};AdfConveyorBeltVertical.prototype.getFirstItemDisplayed=function(){return this._firstItemDisplayed};AdfConveyorBeltVertical.prototype.setFirstItemDisplayed=function(a){AdfAssert.assert(a&&0<=a&&a<this._itemOffsetTopArray.length,"Must set the first item displayed to a valid number within the child range!");this._firstItemDisplayed=a};
AdfConveyorBeltVertical.prototype.handleFocusChange=function(){this._setButtonState()};AdfConveyorBeltVertical._getInnerHeight=function(a){var b=AdfAgent.AGENT.getComputedStyle(a),b=AdfAgent.getCSSLengthAsInt(b.paddingTop)+AdfAgent.getCSSLengthAsInt(b.paddingBottom);return a.offsetHeight-b};
AdfConveyorBeltVertical.prototype._getButtonHeight=function(a){a=AdfAgent.AGENT.getElementById(a);var b=this._contentContainer.getAttribute("style");AdfAssert.assert(null==b||""==b);b=AdfConveyorBeltVertical.superclass.GetContainer.call(this);AdfAssert.assert(!AdfDomUtils.containsCSSClassName(b,AdfConveyorBeltSupport.CONVEYOR_BELT_STYLE_CLASS));b=a.offsetHeight;this._setButtonDisplay(!0);a=a.offsetHeight;this._setButtonDisplay(!1);return a-b};
AdfConveyorBeltVertical.prototype._areConveyorBeltIconsDisplayed=function(){var a=AdfConveyorBeltVertical.superclass.GetContainer.call(this);return AdfDomUtils.containsCSSClassName(a,AdfConveyorBeltSupport.CONVEYOR_BELT_STYLE_CLASS)};AdfConveyorBeltVertical.prototype._setButtonDisplay=function(a){var b=AdfConveyorBeltVertical.superclass.GetContainer.call(this);a?AdfDomUtils.addCSSClassName(b,AdfConveyorBeltSupport.CONVEYOR_BELT_STYLE_CLASS):AdfDomUtils.removeCSSClassName(b,AdfConveyorBeltSupport.CONVEYOR_BELT_STYLE_CLASS)};
AdfConveyorBeltVertical.prototype._setButtonState=function(){this._doesContentRollUp()?(AdfDomUtils.removeCSSClassName(this._topIndicator,AdfRichUIPeer.DISABLED_STYLECLASS),this._topIndicator.removeAttribute("aria-disabled")):(AdfDomUtils.addCSSClassName(this._topIndicator,AdfRichUIPeer.DISABLED_STYLECLASS),this._topIndicator.setAttribute("aria-disabled","true"));this._doesContentRollDown()?this._firstItemDisplayed+1<this._itemOffsetTopArray.length?(AdfDomUtils.removeCSSClassName(this._bottomIndicator,
AdfRichUIPeer.DISABLED_STYLECLASS),this._bottomIndicator.removeAttribute("aria-disabled")):(AdfDomUtils.addCSSClassName(this._bottomIndicator,AdfRichUIPeer.DISABLED_STYLECLASS),this._bottomIndicator.setAttribute("aria-disabled","true")):(AdfDomUtils.addCSSClassName(this._bottomIndicator,AdfRichUIPeer.DISABLED_STYLECLASS),this._bottomIndicator.setAttribute("aria-disabled","true"))};AdfConveyorBeltVertical.prototype._doesContentRollUp=function(){return 0<this._contentContainer.scrollTop};
AdfConveyorBeltVertical.prototype._doesContentRollDown=function(){var a=this._contentHeight-this._contentContainer.scrollTop,b=this._getContainerHeightMinusButtons();return a>b};AdfConveyorBeltVertical.prototype._getContainerHeightMinusButtons=function(){var a=AdfConveyorBeltVertical.superclass.GetContainer.call(this);return AdfConveyorBeltVertical._getInnerHeight(a)-this._buttonHeight-this._toggleButtonHeight};
AdfConveyorBeltVertical.prototype._calculateFirstItemToDisplay=function(){if(void 0==this._selectedItem)return this._firstItemDisplayed;if(this._selectedItem<=this._firstItemDisplayed)return this._selectedItem;var a=this._itemOffsetTopArray[this._selectedItem],b=AdfDomUtils.getChildElementByPosition(this._contentContainer,1,this._selectedItem),b=a+b.offsetHeight,d=this._getContainerHeightMinusButtons();if(b-a>d)return this._selectedItem;for(var a=d,e=1;e<=this._firstItemDisplayed;e++)a+=this._itemOffsetTopArray[e]-
this._itemOffsetTopArray[e-1];if(b<=a)return this._firstItemDisplayed;a=d;for(d=1;d<this._itemOffsetTopArray.length;d++)if(a+=this._itemOffsetTopArray[d]-this._itemOffsetTopArray[d-1],b<=a)return d;AdfAssert.assert(!0,"Code unreachable, all cases handled");return 0};
AdfConveyorBeltVertical.prototype._rollConveyor=function(a){var b=AdfAgent.AGENT,d;d=this._itemOffsetTopArray[this._firstItemDisplayed];a||!AdfPage.PAGE.isAnimationEnabled()?(b.scrollToPos(this._contentContainer,null,d),this._setButtonState()):this._animateRollConveyor(d)};
AdfConveyorBeltVertical.prototype._animateRollConveyor=function(a){AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_SLOW_FAST_SLOW,2*Math.abs(this._contentContainer.scrollTop-a),[{element:this._contentContainer,properties:{scrollTop:a}}],null,AdfConveyorBeltVertical._animateRollConveyorComplete,this,null)};AdfConveyorBeltVertical._animateRollConveyorComplete=function(a){a._keepRollingUp?a._rollUp():a._keepRollingDown&&a._rollDown();a._setButtonState()};
AdfConveyorBeltVertical.prototype._rollUp=function(){this._doesContentRollUp()?(this._firstItemDisplayed=0<this._firstItemDisplayed?this._firstItemDisplayed-1:0,this._rollConveyor()):this._stopRollingUp()};AdfConveyorBeltVertical.prototype._rollDown=function(){this._doesContentRollDown()?(this._firstItemDisplayed=this._firstItemDisplayed+1>=this._itemOffsetTopArray.length?this._itemOffsetTopArray.length-1:this._firstItemDisplayed+1,this._rollConveyor()):this._stopRollingDown()};
AdfConveyorBeltVertical.prototype._stopRollingUp=function(){this._keepRollingUp=!1;this._rollUpTimer&&clearInterval(this._rollUpTimer);this._rollUpTimer=null};AdfConveyorBeltVertical.prototype._stopRollingDown=function(){this._keepRollingDown=!1;this._rollDownTimer&&clearInterval(this._rollDownTimer);this._rollDownTimer=null};
AdfConveyorBeltVertical.prototype._initTopButtonEventHandling=function(){var a=AdfAgent.AGENT,b=this._topIndicator;this._topButtonCall=this.createCallback(this._topConveyorBeltButtonPressed);a.addBubbleEventListener(b,"mousedown",this._topButtonCall);this._topButtonMouseUpCall=this.createCallback(this._topConveyorBeltButtonMouseUp);a.addBubbleEventListener(b,"mouseup",this._topButtonMouseUpCall);this._topButtonMouseOutCall=this.createCallback(this._topConveyorBeltButtonMouseOut);a.addBubbleEventListener(b,
"mouseout",this._topButtonMouseOutCall)};
AdfConveyorBeltVertical.prototype._initBottomButtonEventHandling=function(){var a=AdfAgent.AGENT,b=this._bottomIndicator;this._bottomButtonCall=this.createCallback(this._bottomConveyorBeltButtonPressed);a.addBubbleEventListener(b,"mousedown",this._bottomButtonCall);this._bottomButtonMouseUpCall=this.createCallback(this._bottomConveyorBeltButtonMouseUp);a.addBubbleEventListener(b,"mouseup",this._bottomButtonMouseUpCall);this._bottomButtonMouseOutCall=this.createCallback(this._bottomConveyorBeltButtonMouseOut);a.addBubbleEventListener(b,
"mouseout",this._bottomButtonMouseOutCall)};
AdfConveyorBeltVertical.prototype._topConveyorBeltButtonPressed=function(a){var b=AdfAgent.AGENT,d=a.type;if("mousedown"!=d||!a.button||a.button==AdfUIInputEvent.LEFT_BUTTON_FLAG){var e=b.getEventTarget(a);AdfDomUtils.containsCSSClassName(e,AdfRichUIPeer.DISABLED_STYLECLASS)||("mousedown"==d&&this._setDepressedStyle(e,!0),this._keepRollingUp=!0,this._rollUp(),AdfPage.PAGE.isAnimationEnabled()||(d=this.createCallback(this._rollUp),this._rollUpTimer=setInterval(d,200)))}b.eatEvent(a)};
AdfConveyorBeltVertical.prototype._topConveyorBeltButtonMouseUp=function(a){a=AdfAgent.AGENT.getEventTarget(a);this._setDepressedStyle(a,!1);this._stopRollingUp()};AdfConveyorBeltVertical.prototype._topConveyorBeltButtonMouseOut=function(a){a=AdfAgent.AGENT.getEventTarget(a);this._setDepressedStyle(a,!1);this._stopRollingUp()};
AdfConveyorBeltVertical.prototype._bottomConveyorBeltButtonPressed=function(a){var b=AdfAgent.AGENT,d=a.type;if("mousedown"!=d||!a.button||a.button==AdfUIInputEvent.LEFT_BUTTON_FLAG){var e=b.getEventTarget(a);AdfDomUtils.containsCSSClassName(e,AdfRichUIPeer.DISABLED_STYLECLASS)||("mousedown"==d&&this._setDepressedStyle(e,!0),this._keepRollingDown=!0,this._rollDown(),AdfPage.PAGE.isAnimationEnabled()||(d=this.createCallback(this._rollDown),this._rollDownTimer=setInterval(d,200)))}b.eatEvent(a)};
AdfConveyorBeltVertical.prototype._bottomConveyorBeltButtonMouseUp=function(a){a=AdfAgent.AGENT.getEventTarget(a);this._setDepressedStyle(a,!1);this._stopRollingDown()};AdfConveyorBeltVertical.prototype._bottomConveyorBeltButtonMouseOut=function(a){a=AdfAgent.AGENT.getEventTarget(a);this._setDepressedStyle(a,!1);this._stopRollingDown()};
AdfConveyorBeltVertical.prototype._setDepressedStyle=function(a,b){var d=AdfConveyorBeltSupport.DEPRESSED_STYLE_CLASS;b?AdfDomUtils.addCSSClassName(a,d):AdfDomUtils.removeCSSClassName(a,d)};
function AdfConveyorBeltHorizontal(a,b){this.Init(a,b)}AdfObject.createSubclass(AdfConveyorBeltHorizontal,AdfConveyorBeltSupport);
AdfConveyorBeltHorizontal.prototype.Init=function(a,b){AdfConveyorBeltHorizontal.superclass.Init.call(this,a,b);var d=AdfRichUIPeer.CreateSubId(a,"scbi");this._startIndicator=AdfAgent.AGENT.getElementById(d);this._initStartButtonEventHandling();d=AdfRichUIPeer.CreateSubId(a,"ecbi");this._endIndicator=AdfAgent.AGENT.getElementById(d);this._initEndButtonEventHandling();d=AdfRichUIPeer.CreateSubId(a,"cbc");this._contentContainer=AdfAgent.AGENT.getElementById(d);for(var e=AdfDomUtils.getChildElements(this._contentContainer),
d=[],f=AdfRichUIPeer.CreateSubId(a,"cbs"),g=0;g<e.length;g++){var h=e[g];1==h.nodeType&&h.getAttribute("id")!=f&&"none"!=h.style.display&&d.push(h)}e=AdfPage.PAGE.getLocaleContext().isRightToLeft();f=this._contentContainer.offsetWidth+this._contentContainer.offsetLeft;this._itemOffsetLeftArray=[];for(g=0;g<d.length;g++)this._itemOffsetLeftArray[g]=e?f-(d[g].offsetLeft+d[g].offsetWidth):d[g].offsetLeft,AdfDomUtils.containsCSSClassName(d[g],AdfConveyorBeltSupport.SELECTED_STYLE_CLASS)&&(this._selectedItem=
g);d=d[d.length-1];this._contentWidth=null==d?0:e?f-d.offsetLeft:d.offsetLeft+d.offsetWidth;this._initialRender=!0;this._firstItemDisplayed=0;d=AdfRichUIPeer.CreateSubId(a,"cbdli");this._droplistIndicator=AdfAgent.AGENT.getElementById(d);d=AdfRichUIPeer.CreateSubId(a,"dlc");this._droplistContainer=AdfAgent.AGENT.getElementById(d);this._initDroplistButtonEventHandling();this._conveyorBeltButtonWidth=this._getConveyorBeltButtonWidth();this._keepRollingRight=this._keepRollingLeft=!1};
AdfConveyorBeltHorizontal.prototype.removeConveyorBeltSupport=function(){AdfConveyorBeltHorizontal.superclass.removeConveyorBeltSupport.call(this);var a=AdfAgent.AGENT,b=this._startIndicator;a.removeBubbleEventListener(b,"mousedown",this._startButtonCall);a.removeBubbleEventListener(b,"keydown",this._startButtonCall);a.removeBubbleEventListener(b,"mouseup",this._startButtonMouseUpCall);a.removeBubbleEventListener(b,"mouseout",this._startButtonMouseOutCall);b=this._endIndicator;a.removeBubbleEventListener(b,
"mousedown",this._endButtonCall);a.removeBubbleEventListener(b,"keydown",this._endButtonCall);a.removeBubbleEventListener(b,"mouseup",this._endButtonMouseUpCall);a.removeBubbleEventListener(b,"mouseout",this._endButtonMouseOutCall);b=this._droplistIndicator;a.removeBubbleEventListener(b,"mousedown",this._droplistShowCall);a.removeBubbleEventListener(b,"keydown",this._droplistShowCall);a.removeBubbleEventListener(b,"mouseup",this._droplistButtonMouseUpCall);a.removeBubbleEventListener(b,"mouseout",
this._droplistButtonMouseOutCall);delete this._startIndicator;delete this._endIndicator;delete this._contentContainer;delete this._itemOffsetLeftArray;delete this._selectedItem;delete this._contentWidth;delete this._initialRender;delete this._firstItemDisplayed;delete this._droplistIndicator;delete this._droplistContainer;delete this._otherCBSupport;delete this._hideDroplistContainerCallback;delete this._droplistHints;delete this._conveyorBeltButtonWidth;delete this._keepRollingLeft;delete this._keepRollingRight};
AdfConveyorBeltHorizontal.prototype.registerAdditionalConveyorBeltSupport=function(a){this._otherCBSupport=a};
AdfConveyorBeltHorizontal.prototype.handleResize=function(){var a=this._isConveyorBeltNeeded(),b=this._areConveyorBeltIconsDisplayed();a?(b||(this._setButtonDisplay(!0),this._initialRender&&(this._firstItemDisplayed=this._calculateFirstItemToDisplay()),this._rollConveyor(!0)),this._setButtonState()):(this._setButtonDisplay(!1),AdfAgent.AGENT.scrollToPos(this._contentContainer,0));this._initialRender&&(this._initialRender=!1)};
AdfConveyorBeltHorizontal.prototype.addDropListElements=function(a){for(var b=this._droplistContainer,d=0;d<a.length;d++)b.appendChild(a[d])};AdfConveyorBeltHorizontal.prototype.scrollNewSelectedItemIntoView=function(a){AdfAssert.assert(0<=a&&a<this._itemOffsetLeftArray.length,"New selected item should be within known valid range of conveyor belt support");this._selectedItem=a;this._firstItemDisplayed=this._calculateFirstItemToDisplay();this._rollConveyor(!0)};
AdfConveyorBeltHorizontal.prototype.getFirstItemDisplayed=function(){return this._firstItemDisplayed};AdfConveyorBeltHorizontal.prototype.setFirstItemDisplayed=function(a){AdfAssert.assert(a&&0<=a&&a<this._itemOffsetLeftArray.length,"Must set the first item displayed to a valid number within the child range!");this._firstItemDisplayed=a};AdfConveyorBeltHorizontal.prototype.handleFocusChange=function(){this._setButtonState()};
AdfConveyorBeltHorizontal._getInnerWidth=function(a){var b=AdfAgent.AGENT.getComputedStyle(a),b=AdfAgent.getCSSLengthAsInt(b.paddingLeft)+AdfAgent.getCSSLengthAsInt(b.paddingRight);return a.offsetWidth-b};
AdfConveyorBeltHorizontal.prototype._getConveyorBeltButtonWidth=function(){var a=AdfConveyorBeltHorizontal.superclass.GetContainer.call(this),b=this._areConveyorBeltIconsDisplayed();b&&this._setButtonDisplay(!1);var d=AdfConveyorBeltHorizontal._getInnerWidth(a);this._setButtonDisplay(!0);a=AdfConveyorBeltHorizontal._getInnerWidth(a);b||this._setButtonDisplay(!1);return d-a};
AdfConveyorBeltHorizontal.prototype._isConveyorBeltNeeded=function(){var a=AdfConveyorBeltHorizontal.superclass.GetContainer.call(this),a=AdfConveyorBeltHorizontal._getInnerWidth(a);this._areConveyorBeltIconsDisplayed()&&(a+=this._conveyorBeltButtonWidth);return this._contentWidth>=a};AdfConveyorBeltHorizontal.prototype._areConveyorBeltIconsDisplayed=function(){var a=AdfConveyorBeltHorizontal.superclass.GetContainer.call(this);return AdfDomUtils.containsCSSClassName(a,AdfConveyorBeltSupport.CONVEYOR_BELT_STYLE_CLASS)};
AdfConveyorBeltHorizontal.prototype._setButtonDisplay=function(a){var b=AdfConveyorBeltHorizontal.superclass.GetContainer.call(this);a?AdfDomUtils.addCSSClassName(b,AdfConveyorBeltSupport.CONVEYOR_BELT_STYLE_CLASS):AdfDomUtils.removeCSSClassName(b,AdfConveyorBeltSupport.CONVEYOR_BELT_STYLE_CLASS)};
AdfConveyorBeltHorizontal.prototype._setButtonState=function(){this._doesContentRollLeft()?(AdfDomUtils.removeCSSClassName(this._startIndicator,AdfRichUIPeer.DISABLED_STYLECLASS),this._startIndicator.removeAttribute("aria-disabled")):(AdfDomUtils.addCSSClassName(this._startIndicator,AdfRichUIPeer.DISABLED_STYLECLASS),this._startIndicator.setAttribute("aria-disabled","true"));this._doesContentRollRight()?this._firstItemDisplayed+1<this._itemOffsetLeftArray.length?(AdfDomUtils.removeCSSClassName(this._endIndicator,
AdfRichUIPeer.DISABLED_STYLECLASS),this._endIndicator.removeAttribute("aria-disabled")):(AdfDomUtils.addCSSClassName(this._endIndicator,AdfRichUIPeer.DISABLED_STYLECLASS),this._endIndicator.setAttribute("aria-disabled","true")):(AdfDomUtils.addCSSClassName(this._endIndicator,AdfRichUIPeer.DISABLED_STYLECLASS),this._endIndicator.setAttribute("aria-disabled","true"))};
AdfConveyorBeltHorizontal.prototype._doesContentRollLeft=function(){var a=AdfPage.PAGE.getLocaleContext().isRightToLeft(),b=AdfAgent.AGENT;if(a&&b.getPlatform()!=AdfAgent.IE_PLATFORM){if(b.getPlatform()==AdfAgent.GECKO_PLATFORM)return this._contentContainer&&0>this._contentContainer.scrollLeft;a=this._contentWidth-this._contentContainer.scrollLeft;b=AdfConveyorBeltHorizontal.superclass.GetContainer.call(this);b=AdfConveyorBeltHorizontal._getInnerWidth(b);return a>b+10}return this._contentContainer&&
0<this._contentContainer.scrollLeft};
AdfConveyorBeltHorizontal.prototype._doesContentRollRight=function(){var a=AdfAgent.AGENT;if(AdfPage.PAGE.getLocaleContext().isRightToLeft()&&a.getPlatform()!=AdfAgent.IE_PLATFORM)if(a.getPlatform()==AdfAgent.GECKO_PLATFORM)a=this._contentWidth+this._contentContainer.scrollLeft;else return this._contentContainer&&0<this._contentContainer.scrollLeft;else a=this._contentWidth-this._contentContainer.scrollLeft;var b=AdfConveyorBeltHorizontal.superclass.GetContainer.call(this),b=AdfConveyorBeltHorizontal._getInnerWidth(b);
return a>b+10};
AdfConveyorBeltHorizontal.prototype._calculateFirstItemToDisplay=function(){if(void 0==this._selectedItem)return this._firstItemDisplayed;if(this._selectedItem<=this._firstItemDisplayed)return this._selectedItem;var a=this._itemOffsetLeftArray[this._selectedItem],b=AdfDomUtils.getChildElementByPosition(this._contentContainer,1,this._selectedItem),b=a+b.offsetWidth,d=AdfConveyorBeltHorizontal.superclass.GetContainer.call(this),e=AdfConveyorBeltHorizontal._getInnerWidth(d),d=e;if(b-a>d)return this._selectedItem;
for(a=1;a<=this._firstItemDisplayed;a++)d+=this._itemOffsetLeftArray[a]-this._itemOffsetLeftArray[a-1];if(b<=d)return this._firstItemDisplayed;d=e;for(a=1;a<this._itemOffsetLeftArray.length;a++)if(d+=this._itemOffsetLeftArray[a]-this._itemOffsetLeftArray[a-1],b<=d)return a;AdfAssert.assert(!0,"Code unreachable, all cases handled");return 0};
AdfConveyorBeltHorizontal.prototype._rollConveyor=function(a){var b=AdfPage.PAGE.getLocaleContext().isRightToLeft(),d=AdfAgent.AGENT,b=b&&d.getPlatform()!=AdfAgent.IE_PLATFORM?d.getPlatform()==AdfAgent.GECKO_PLATFORM?-this._itemOffsetLeftArray[this._firstItemDisplayed]:this._contentContainer.scrollWidth-this._contentContainer.offsetWidth-this._itemOffsetLeftArray[this._firstItemDisplayed]:this._itemOffsetLeftArray[this._firstItemDisplayed];a||!AdfPage.PAGE.isAnimationEnabled()?(d.scrollToPos(this._contentContainer,
b),this._setButtonState()):this._animateRollConveyor(b)};AdfConveyorBeltHorizontal.prototype._animateRollConveyor=function(a){AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_SLOW_FAST_SLOW,2*Math.abs(this._contentContainer.scrollLeft-a),[{element:this._contentContainer,properties:{scrollLeft:a}}],null,AdfConveyorBeltHorizontal._animateRollConveyorComplete,this,null)};
AdfConveyorBeltHorizontal._animateRollConveyorComplete=function(a){a._keepRollingLeft?a._otherCBSupport?a._rollMultipleLeft():a._rollLeft():a._keepRollingRight&&(a._otherCBSupport?a._rollMultipleRight():a._rollRight());a._setButtonState()};AdfConveyorBeltHorizontal.prototype._rollLeft=function(){this._doesContentRollLeft()?(this._firstItemDisplayed=0<this._firstItemDisplayed?this._firstItemDisplayed-1:0,this._rollConveyor()):this._stopRollingLeft()};
AdfConveyorBeltHorizontal.prototype._rollMultipleLeft=function(){AdfAssert.assert(null!=this._otherCBSupport,"Method should only be called if there are multiple conveyors.");this._rollLeft();this._otherCBSupport._rollLeft()};AdfConveyorBeltHorizontal.prototype._rollRight=function(){this._doesContentRollRight()?(this._firstItemDisplayed=this._firstItemDisplayed+1>=this._itemOffsetLeftArray.length?this._itemOffsetLeftArray.length-1:this._firstItemDisplayed+1,this._rollConveyor()):this._stopRollingRight()};
AdfConveyorBeltHorizontal.prototype._rollMultipleRight=function(){AdfAssert.assert(null!=this._otherCBSupport,"Method should only be called if there are multiple conveyors.");this._rollRight();this._otherCBSupport._rollRight()};AdfConveyorBeltHorizontal.prototype._stopRollingLeft=function(){this._keepRollingLeft=!1;this._rollLeftTimer&&clearInterval(this._rollLeftTimer);this._rollLeftTimer=null};
AdfConveyorBeltHorizontal.prototype._stopRollingRight=function(){this._keepRollingRight=!1;this._rollRightTimer&&clearInterval(this._rollRightTimer);this._rollRightTimer=null};
AdfConveyorBeltHorizontal.prototype._initStartButtonEventHandling=function(){var a=AdfAgent.AGENT,b=this._startIndicator;this._startButtonCall=this.createCallback(this._startConveyorBeltButtonPressed);a.addBubbleEventListener(b,"mousedown",this._startButtonCall);this._startButtonMouseUpCall=this.createCallback(this._startConveyorBeltButtonMouseUp);a.addBubbleEventListener(b,"mouseup",this._startButtonMouseUpCall);this._startButtonMouseOutCall=this.createCallback(this._startConveyorBeltButtonMouseOut);
a.addBubbleEventListener(b,"mouseout",this._startButtonMouseOutCall)};
AdfConveyorBeltHorizontal.prototype._initEndButtonEventHandling=function(){var a=AdfAgent.AGENT,b=this._endIndicator;this._endButtonCall=this.createCallback(this._endConveyorBeltButtonPressed);a.addBubbleEventListener(b,"mousedown",this._endButtonCall);this._endButtonMouseUpCall=this.createCallback(this._endConveyorBeltButtonMouseUp);a.addBubbleEventListener(b,"mouseup",this._endButtonMouseUpCall);this._endButtonMouseOutCall=this.createCallback(this._endConveyorBeltButtonMouseOut);a.addBubbleEventListener(b,
"mouseout",this._endButtonMouseOutCall)};
AdfConveyorBeltHorizontal.prototype._startConveyorBeltButtonPressed=function(a){var b=AdfAgent.AGENT,d=a.type;if("mousedown"!=d||!a.button||a.button==AdfUIInputEvent.LEFT_BUTTON_FLAG){var e=b.getEventTarget(a);AdfDomUtils.containsCSSClassName(e,AdfRichUIPeer.DISABLED_STYLECLASS)||("mousedown"==d&&this._setDepressedStyle(e,!0),this._keepRollingLeft=!0,this._otherCBSupport?this._rollMultipleLeft():this._rollLeft(),AdfPage.PAGE.isAnimationEnabled()||(d=this._otherCBSupport?this.createCallback(this._rollMultipleLeft):
this.createCallback(this._rollLeft),this._rollLeftTimer=setInterval(d,200)))}b.eatEvent(a)};AdfConveyorBeltHorizontal.prototype._startConveyorBeltButtonMouseUp=function(a){a=AdfAgent.AGENT.getEventTarget(a);this._setDepressedStyle(a,!1);this._stopRollingLeft()};AdfConveyorBeltHorizontal.prototype._startConveyorBeltButtonMouseOut=function(a){a=AdfAgent.AGENT.getEventTarget(a);this._setDepressedStyle(a,!1);this._stopRollingLeft()};
AdfConveyorBeltHorizontal.prototype._endConveyorBeltButtonPressed=function(a){var b=AdfAgent.AGENT,d=a.type;if("mousedown"!=d||!a.button||a.button==AdfUIInputEvent.LEFT_BUTTON_FLAG){var e=b.getEventTarget(a);AdfDomUtils.containsCSSClassName(e,AdfRichUIPeer.DISABLED_STYLECLASS)||("mousedown"==d&&this._setDepressedStyle(e,!0),this._keepRollingRight=!0,this._otherCBSupport?this._rollMultipleRight():this._rollRight(),AdfPage.PAGE.isAnimationEnabled()||(d=this._otherCBSupport?this.createCallback(this._rollMultipleRight):
this.createCallback(this._rollRight),this._rollRightTimer=setInterval(d,200)))}b.eatEvent(a)};AdfConveyorBeltHorizontal.prototype._endConveyorBeltButtonMouseUp=function(a){a=AdfAgent.AGENT.getEventTarget(a);this._setDepressedStyle(a,!1);this._stopRollingRight()};AdfConveyorBeltHorizontal.prototype._endConveyorBeltButtonMouseOut=function(a){a=AdfAgent.AGENT.getEventTarget(a);this._setDepressedStyle(a,!1);this._stopRollingRight()};
AdfConveyorBeltHorizontal.prototype._setDepressedStyle=function(a,b){var d=AdfConveyorBeltSupport.DEPRESSED_STYLE_CLASS;b?AdfDomUtils.addCSSClassName(a,d):AdfDomUtils.removeCSSClassName(a,d)};
AdfConveyorBeltHorizontal.prototype._initDroplistButtonEventHandling=function(){var a=AdfAgent.AGENT,b=this._droplistIndicator,d=this._createConveyorBeltPopupHints();d[AdfDhtmlPopupHints.ALIGN_ELEMENT]=b;d[AdfRichPopup.HINT_ALIGN]=AdfRichPopup.ALIGN_AFTER_END;this._droplistHints=d;d=this._droplistShowCall=this.createCallback(this._droplistButtonPressed);a.addBubbleEventListener(b,"mousedown",d);a.addBubbleEventListener(b,"keydown",d);this._droplistButtonMouseUpCall=this.createCallback(this._droplistButtonMouseUp);
a.addBubbleEventListener(b,"mouseup",this._droplistButtonMouseUpCall);this._droplistButtonMouseOutCall=this.createCallback(this._droplistButtonMouseOut);a.addBubbleEventListener(b,"mouseout",this._droplistButtonMouseOutCall)};
AdfConveyorBeltHorizontal.prototype._createConveyorBeltPopupHints=function(){var a={};a[AdfDhtmlPopupHints.AUTODISMISS]=AdfDhtmlPopupHints.AUTODISMISS_ALWAYS;a[AdfDhtmlPopupHints.FOCUS]=!0;a[AdfDhtmlPopupHints.TYPE]=AdfDhtmlPopupHints.TYPE_MENU;a[AdfDhtmlPopupHints.CLOSE_ON_ESCAPE]=!0;return a};
AdfConveyorBeltHorizontal.prototype._droplistButtonPressed=function(a){var b=AdfAgent.AGENT,d=a.type,e=a.keyCode;if("keydown"!=d||e==AdfKeyStroke.ENTER_KEY||e==AdfKeyStroke.ARROWDOWN_KEY){if("mousedown"!=d||!a.button||a.button==AdfUIInputEvent.LEFT_BUTTON_FLAG){null==this._hideDroplistContainerCallback&&(this._hideDroplistContainerCallback=this.createCallback(this._hideDroplistContainer),AdfObject.ensureClassInitialization(AdfDhtmlPopupWindow),this._droplistHints[AdfDhtmlPopupHints.CLOSE_HANDLER]=
this._hideDroplistContainerCallback,this._droplistHints[AdfDhtmlPopupHints.TITLE]=AdfAgent.AGENT.getEventTarget(a).title,this._droplistContainerParent=this._droplistContainer.parentNode);var e=AdfConveyorBeltHorizontal.superclass.GetPeer.call(this),f=e.getComponent(),g=AdfConveyorBeltSupport.DROPLIST_ID;e.isPopupVisible(f,g)?e.hidePopup(f,g):e.showPopup(f,this._droplistContainer,this._droplistHints,g);"mousedown"==d&&(d=b.getEventTarget(a),this._setDepressedStyle(d,!0))}b.eatEvent(a)}};
AdfConveyorBeltHorizontal.prototype._droplistButtonMouseUp=function(a){a=AdfAgent.AGENT.getEventTarget(a);this._setDepressedStyle(a,!1)};AdfConveyorBeltHorizontal.prototype._droplistButtonMouseOut=function(a){a=AdfAgent.AGENT.getEventTarget(a);this._setDepressedStyle(a,!1)};AdfConveyorBeltHorizontal.prototype._hideDroplistContainer=function(){this._droplistContainer&&this._droplistContainerParent.appendChild(this._droplistContainer)};