AdfUIComponents.createComponentClass("AdfRichCommandToolbarButton",{componentType:"oracle.adf.RichCommandToolbarButton",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"useWindow",type:"Boolean","default":!1},{name:"windowModalityType",type:"String","default":"modeless"},{name:"windowEmbedStyle",type:"String","default":"window"},{name:"windowHeight",
type:"Number"},{name:"windowWidth",type:"Number"},{name:"iconDelivery",type:"String","default":"auto"},{name:"accessKey",type:"String"},{name:"actionDelivery",type:"String","default":"clientServer",secured:!0},{name:"partialSubmit",type:"Boolean","default":!0},{name:"disabled",type:"Boolean","default":!1,secured:!0},{name:"depressedIcon",type:"String"},{name:"hoverIcon",type:"String"},{name:"disabledIcon",type:"String"},{name:"icon",type:"String"},{name:"text",type:"String"},{name:"type",type:"String",
"default":"default"},{name:"selected",type:"Boolean","default":!1}],superclass:AdfUICommand});
AdfRichCommandToolbarButton.prototype.getAccessibleName=function(){return this.getShortDesc()};
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlCommandToolbarButtonPeer");
AdfDhtmlCommandToolbarButtonPeer.InitSubclass=function(){AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.KEY_DOWN_EVENT_TYPE,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.MOUSE_DOWN_EVENT_TYPE,AdfUIInputEvent.MOUSE_UP_EVENT_TYPE);AdfAgent.AGENT.isTouchFirstDevice()||AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.MOUSE_IN_EVENT_TYPE,AdfUIInputEvent.MOUSE_OUT_EVENT_TYPE);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichCommandToolbarButton.DISABLED,AdfRichCommandToolbarButton.SELECTED,
AdfRichCommandToolbarButton.SHORT_DESC,AdfRichCommandToolbarButton.TEXT);AdfRichUIPeer.addComponentPropertyGetters(this,AdfRichCommandToolbarButton.TEXT);this._POPUP_ELEMENT="popEl";this._POPUP_CONTAINER="popCtr";this._POPUP_CONTEXT_AREA="popArea";this._POPUP_CONTENT_ID="popup";this._POPUP_ID="_afrPopId";this._AFR_GROUPID="_afrGrp";this._DEPRESSED_STYLE_CLASS="p_AFDepressed";this._SELECTED_STYLE_CLASS="p_AFSelected";this._BUSY="_busy"};
AdfDhtmlCommandToolbarButtonPeer.prototype.BindToComponent=function(a,b){AdfDhtmlCommandToolbarButtonPeer.superclass.BindToComponent.call(this,a,b);this._actionDisabled=AdfDomUtils.containsCSSClassName(b,"p_AFActionDisabled")};
AdfDhtmlCommandToolbarButtonPeer.prototype.HandleComponentKeyDown=function(a){if(!a.isCanceled()){var b=a.getKeyCode(),d=this.getComponent(),e=this._getPopupId();if(this._isEventInRootElement(a)){var f=this._actionDisabled&&(b==AdfKeyStroke.ENTER_KEY||b==AdfKeyStroke.SPACE_KEY);b==AdfKeyStroke.ARROWDOWN_KEY||f?this._openPopupMenu(e,!0,a):b==AdfKeyStroke.SPACE_KEY&&(f=d.getProperty(AdfDhtmlCommandToolbarButtonPeer._BUSY),d.getDisabled()||f||(this._execute(),a.cancel()))}b==AdfKeyStroke.ESC_KEY&&(e||
(e=d.getClientId()),this.hidePopup(d,e))}};AdfDhtmlCommandToolbarButtonPeer.prototype.HandleComponentClick=function(a){if(a.isLeftButtonPressed()&&!this._actionDisabled&&!this._isInPopupSelector(a)&&this._isEventInRootElement(a)){a=this.getComponent();var b=a.getProperty(AdfDhtmlCommandToolbarButtonPeer._BUSY);a.getDisabled()||b||this._execute()}};AdfDhtmlCommandToolbarButtonPeer.prototype.HandleComponentMouseOver=function(a){!this.getComponent().getDisabled()&&this._isEventInRootElement(a)&&this._displayMouseOverIcon(this.getComponent())};
AdfDhtmlCommandToolbarButtonPeer.prototype.HandleComponentMouseOut=function(a){var b=this.getComponent();!b.getDisabled()&&this._isEventInRootElement(a)&&(b.getSelected()?(this._setDepressedStyle(b,!0),this._displayMouseDownIcon(b)):(this._setDepressedStyle(b,!1),this._displayDefaultIcon(b)))};
AdfDhtmlCommandToolbarButtonPeer.prototype.HandleComponentMouseUp=function(a){var b=this.getComponent();!b.getDisabled()&&a.isLeftButtonPressed()&&this._isEventInRootElement(a)&&(this._setDepressedStyle(b,!1),this._displayMouseOverIcon(b))};
AdfDhtmlCommandToolbarButtonPeer.prototype.HandleComponentMouseDown=function(a){var b=this.getComponent(),d=a.isLeftButtonPressed();!b.getDisabled()&&d&&this._isEventInRootElement(a)&&(this._setDepressedStyle(b,!0),this._displayMouseDownIcon(b),this._actionDisabled||this._isInPopupSelector(a))&&(b=this._getPopupId(),this._openPopupMenu(b,!1,a))};
AdfDhtmlCommandToolbarButtonPeer.prototype.ComponentDisabledChanged=function(a,b,d,e){e=AdfDomUtils.getFirstDescendentElement(b,"A");1==d?(AdfDomUtils.addCSSClassName(b,AdfRichUIPeer.DISABLED_STYLECLASS),e.removeAttribute("href"),this._displayDisabledIcon(a),this._setAriaDisabled(a),e.setAttribute(AdfFocusUtils.DESCENDANT_FOCUSABLE,"false")):(AdfDomUtils.removeCSSClassName(b,AdfRichUIPeer.DISABLED_STYLECLASS),e.setAttribute("href","#"),this._displayDefaultIcon(a),this._removeAriaDisabled(a),e.setAttribute(AdfFocusUtils.DESCENDANT_FOCUSABLE,
"true"))};
AdfDhtmlCommandToolbarButtonPeer.prototype.ComponentSelectedChanged=function(a,b,d,e){e=a.getType();d?(this._setDepressedStyle(a,!0),AdfDomUtils.addCSSClassName(b,AdfDhtmlCommandToolbarButtonPeer._SELECTED_STYLE_CLASS),this._displayMouseDownIcon(a),"radio"==e&&(this._toggleRadioGroupItems(),this._enableAriaChecked(a)),"check"==e&&this._enableAriaPressed(a)):(this._setDepressedStyle(a,!1),AdfDomUtils.removeCSSClassName(b,AdfDhtmlCommandToolbarButtonPeer._SELECTED_STYLE_CLASS),this._displayDefaultIcon(a),"radio"==
e&&this._disableAriaChecked(a),"check"==e&&this._disableAriaPressed(a))};AdfDhtmlCommandToolbarButtonPeer.prototype.ComponentShortDescChanged=function(a,b,d,e){b.setAttribute("title",d);if(a=this._getIconElement(a))a.setAttribute("title",d),a.setAttribute("alt",d)};AdfDhtmlCommandToolbarButtonPeer.prototype.ComponentTextChanged=AdfDomUtils.__componentTextChanged;AdfDhtmlCommandToolbarButtonPeer.prototype.GetInlineEditor=function(a){return AdfDhtmlSimpleTextEditor.getInlineEditor()};
AdfDhtmlCommandToolbarButtonPeer.prototype.GetComponentText=function(a,b){var d=AdfRichUIPeer.CreateSubId(a.getClientId(),AdfDhtmlCommandToolbarButtonPeer._POPUP_CONTEXT_AREA);if(d=(d=AdfAgent.AGENT.getElementById(d))?AdfDomUtils.getPreviousElement(d):b){if(d=AdfDomUtils.getFirstDescendentElement(d,"span"))if(d=AdfAgent.AGENT.getTextContent(d),""!=d)return d;return null}AdfAssert.assert(!1,"Unable to find the element containing the text")};
AdfDhtmlCommandToolbarButtonPeer.prototype.SetBusy=function(a){var b=this.getComponent(),d=this.getDomElement();!AdfDomUtils.getFormElement(d)||b.getDisabled()||AdfPage.PAGE.isAttachmentMode()||(AdfDomUtils.addOrRemoveCSSClassName(a,d,AdfRichUIPeer.DISABLED_STYLECLASS),b.setProperty(AdfDhtmlCommandToolbarButtonPeer._BUSY,a,!1,AdfUIComponent.PROPAGATE_NEVER))};
AdfDhtmlCommandToolbarButtonPeer.prototype.PopupClosed=function(a,b,d){AdfDhtmlCommandToolbarButtonPeer.superclass.PopupClosed.call(this,a,b);a=a.getClientId();d==a&&(d=AdfRichUIPeer.createSubId(a,AdfDhtmlCommandToolbarButtonPeer._POPUP_CONTAINER),(d=AdfAgent.AGENT.getElementById(d))&&d.appendChild(b))};AdfDhtmlCommandToolbarButtonPeer.prototype.__preferredSizeChangeNotify=function(a){this.bind(a);a=this.getComponentParent(a);var b=null!=a?a.getPeer():null;b&&b.__preferredSizeChangeNotify&&b.__preferredSizeChangeNotify(a)};
AdfDhtmlCommandToolbarButtonPeer.prototype._execute=function(){var a=this.getComponent(),b=new AdfActionEvent(a);b.queue(a.getPartialSubmit());b.isCanceled()||(b=a.getType(),"check"==b?a.setSelected(!a.getSelected()):"radio"==b&&this._toggleRadioGroupItems())};
AdfDhtmlCommandToolbarButtonPeer.prototype._openPopupMenu=function(a,b,d){var e=this.getComponent(),f=e.getClientId(),g=AdfRichUIPeer.createSubId(f,AdfDhtmlCommandToolbarButtonPeer._POPUP_ELEMENT);if(AdfAgent.AGENT.getElementById(g))if(g=this.getDomElement(),null!=a)e=AdfPage.PAGE.findComponent(a).getPeer(),a={},a[AdfDhtmlPopupHints.ALIGN_ELEMENT]=g,a[AdfRichPopup.HINT_ALIGN]=AdfRichPopup.ALIGN_AFTER_START,a[AdfDhtmlPopupHints.FOCUS]=b,e.show(a),d.cancel();else{a=AdfRichUIPeer.createSubId(f,AdfDhtmlCommandToolbarButtonPeer._POPUP_CONTAINER);
var h=AdfAgent.AGENT.getElementById(a);if(null!=h){for(var k=h.firstChild;k&&8==k.nodeType;)k=k.nextSibling;if(null!=k){a={};var l=AdfRichUIPeer.createSubId(f,AdfDhtmlCommandToolbarButtonPeer._POPUP_CONTENT_ID);k.id!=l&&(h=h.ownerDocument.createElement("div"),h.appendChild(k),k=h,k.id=l);a[AdfDhtmlPopupHints.AUTODISMISS]=AdfDhtmlPopupHints.AUTODISMISS_ALWAYS;a[AdfDhtmlPopupHints.ALIGN_ELEMENT]=g;a[AdfRichPopup.HINT_ALIGN]=AdfRichPopup.ALIGN_AFTER_START;a[AdfDhtmlPopupHints.FOCUS]=b;this.showPopup(e,
k,a,f);d.cancel()}}}};AdfDhtmlCommandToolbarButtonPeer.prototype._toggleRadioGroupItems=function(){for(var a=this.getComponent(),b=this.getDomElement(),b=this._getGroupId(b),d=a.getParent(),d=d.getPeer().getDescendantComponents(d),e=0;e<d.length;e++){var f=d[e],g=AdfRichUIPeer.getDomElementForComponent(f),g=this._getGroupId(g);b==g&&f!=a&&f.getType&&"radio"==f.getType()&&this._toggleComponentUnselected(f)}a.setSelected(!0)};AdfDhtmlCommandToolbarButtonPeer.prototype._getGroupId=function(a){return a.getAttribute(AdfDhtmlCommandToolbarButtonPeer._AFR_GROUPID)};
AdfDhtmlCommandToolbarButtonPeer.prototype._toggleComponentUnselected=function(a){a.setSelected(!1);this._setDepressedStyle(a,!1);this._displayDefaultIcon(a)};AdfDhtmlCommandToolbarButtonPeer.prototype._getIconElement=function(a){a=a.getClientId();a=AdfRichUIPeer.createSubId(a,"icon");return AdfAgent.AGENT.getElementById(a)};AdfDhtmlCommandToolbarButtonPeer.prototype._displayDefaultIcon=function(a){this._displayIcon(a,null)};
AdfDhtmlCommandToolbarButtonPeer.prototype._displayMouseDownIcon=function(a){this._displayIcon(a,a.getDepressedIcon())};AdfDhtmlCommandToolbarButtonPeer.prototype._displayMouseOverIcon=function(a){a.getSelected()||this._displayIcon(a,a.getHoverIcon())};AdfDhtmlCommandToolbarButtonPeer.prototype._displayDisabledIcon=function(a){this._displayIcon(a,a.getDisabledIcon())};
AdfDhtmlCommandToolbarButtonPeer.prototype._displayIcon=function(a,b){if(AdfRichUIPeer.isInlineSVGIcon(a))b&&AdfLogger.LOGGER.warning("component: ",a.getClientId(),", depressed, disabled and hover icons are not supported when iconDelivery is inline/fetchAndInline for svg icons.CSS styles can be applied on inline SVG to handle these states.Icon url: ",b);else{var d=a.getIcon(),e=this._getIconElement(a);e&&d&&(e.src=b||d)}};
AdfDhtmlCommandToolbarButtonPeer.prototype._setDepressedStyle=function(a,b){var d=AdfRichUIPeer.getDomElementForComponent(a),e=AdfDhtmlCommandToolbarButtonPeer._DEPRESSED_STYLE_CLASS;b?AdfDomUtils.addCSSClassName(d,e):AdfDomUtils.removeCSSClassName(d,e)};
AdfDhtmlCommandToolbarButtonPeer.prototype._isInPopupSelector=function(a){var b=this.getComponent().getClientId(),d=AdfRichUIPeer.createSubId(b,AdfDhtmlCommandToolbarButtonPeer._POPUP_CONTEXT_AREA);for(a=a.getNativeEventTarget();null!=a&&a.id!=b;){if(a.id==d)return!0;a=a.parentNode}return!1};
AdfDhtmlCommandToolbarButtonPeer.prototype._getPopupId=function(){var a=this.getComponent(),a=AdfRichUIPeer.createSubId(a.getClientId(),AdfDhtmlCommandToolbarButtonPeer._POPUP_ELEMENT),a=AdfAgent.AGENT.getElementById(a);if(!a)return null;var a=a.parentNode,b=a.getAttribute(AdfDhtmlCommandToolbarButtonPeer._POPUP_ID);null==b&&(b=a.parentNode.getAttribute(AdfDhtmlCommandToolbarButtonPeer._POPUP_ID));return b};
AdfDhtmlCommandToolbarButtonPeer.prototype._isEventInRootElement=function(a){var b=a.getNativeEventTarget();a=this._getPopupId();for(var d=null!=a,e=this.getDomElement();b.parentNode&&(!d||a!=b.id);b=b.parentNode)if(b==e)return!0;return!1};AdfDhtmlCommandToolbarButtonPeer.prototype._enableAriaPressed=function(a){a=this.getDomElement();"A"!=a.tagName&&(a=AdfDomUtils.getDescendentElement(a,"a",0));a.setAttribute("aria-pressed","true")};
AdfDhtmlCommandToolbarButtonPeer.prototype._disableAriaPressed=function(a){a=this.getDomElement();"A"!=a.tagName&&(a=AdfDomUtils.getDescendentElement(a,"a",0));a.setAttribute("aria-pressed","false")};AdfDhtmlCommandToolbarButtonPeer.prototype._enableAriaChecked=function(a){a=this.getDomElement();"A"!=a.tagName&&(a=AdfDomUtils.getDescendentElement(a,"a",0));var b="button"==a.getAttribute("role").toLowerCase()?"aria-pressed":"aria-checked";a.setAttribute(b,"true")};
AdfDhtmlCommandToolbarButtonPeer.prototype._disableAriaChecked=function(a){a=this.getDomElement();"A"!=a.tagName&&(a=AdfDomUtils.getDescendentElement(a,"a",0));var b="button"==a.getAttribute("role").toLowerCase()?"aria-pressed":"aria-checked";a.setAttribute(b,"false")};AdfDhtmlCommandToolbarButtonPeer.prototype._setAriaDisabled=function(a){a=this.getDomElement();"A"!=a.tagName&&(a=AdfDomUtils.getDescendentElement(a,"a",0));a.setAttribute("aria-disabled","true")};
AdfDhtmlCommandToolbarButtonPeer.prototype._removeAriaDisabled=function(a){a=this.getDomElement();"A"!=a.tagName&&(a=AdfDomUtils.getDescendentElement(a,"a",0));a.removeAttribute("aria-disabled")};
AdfUIComponents.createComponentClass("AdfRichToolbar",{componentType:"oracle.adf.RichToolbar",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"flex",type:"Number","default":0},{name:"stretchId",type:"String"}],superclass:AdfUIPanel});
AdfRichToolbar.HORIZONTAL="horizontal";AdfRichToolbar.VERTICAL="vertical";
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlToolbarPeer",!1);AdfDhtmlToolbarPeer.InitSubclass=function(){AdfObject.ensureClassInitialization(AdfToolbarUtils);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.KEY_DOWN_EVENT_TYPE,AdfUIInputEvent.KEY_PRESS_EVENT_TYPE,AdfUIInputEvent.FOCUS_EVENT_TYPE)};
AdfDhtmlToolbarPeer.prototype.InitDomElement=function(a,b){AdfDhtmlToolbarPeer.superclass.InitDomElement.call(this,a,b);var d=a.getClientId(),e=AdfRichUIPeer.CreateSubId(d,"eoc"),f=AdfAgent.AGENT;if(this._isOverflowSupported=(this._overflowContainer=f.getElementById(e))?!0:!1)e=AdfRichUIPeer.CreateSubId(d,"eoi"),this._overflowIndicator=f.getElementById(e),AdfPage.PAGE.__registerDescendantResizeNotifyComponent(a);d=b.getElementsByTagName("table")[0];this._childContainers=f.getTableRowCells(f.getTableRow(d,
0));(this._isSingleTabstop=null==AdfFocusUtils.getFirstUnmarkedTabstop(b))?this._activeDescendant=AdfFocusUtils.setupCompositeWidget(b):this._isOverflowSupported&&this._overflowIndicator.setAttribute("tabIndex","0")};AdfDhtmlToolbarPeer.prototype.needsChildVisibilityChanges=function(a){return!0};AdfDhtmlToolbarPeer.prototype.needsResizeNotify=function(a){return!0};
AdfDhtmlToolbarPeer.prototype.getDescendantComponents=function(a,b){b||(b=[]);AdfDhtmlToolbarPeer.superclass.getDescendantComponents.call(this,a,b);1==this._isOverflowSupported&&AdfOverflowSupport.getOverflowChildComponents(a,b);return b};AdfDhtmlToolbarPeer.prototype.resetActiveDescendant=function(){this._isSingleTabstop&&(this._activeDescendant&&this._activeDescendant.setAttribute("tabIndex","-1"),this._activeDescendant=AdfFocusUtils.setFirstActiveDescendant(this.getDomElement()))};
AdfDhtmlToolbarPeer.prototype.ResizeNotify=function(a,b,d,e){a=this.getDomElement();b=this.getComponent();d=b.getClientId();if(0!=this._isOverflowSupported||b.getStretchId()){this._unStretch();if(1==this._isOverflowSupported){if(!this._overflowSupport)for(this._overflowSupport=new AdfOverflowSupport(d,this,"end",null,null,this._isSingleTabstop),a=a.getElementsByTagName("table")[0],b=AdfAgent.AGENT,a=b.getTableRowCells(b.getTableRow(a,0)),b=0,d=a[0];d;)this._overflowSupport.createStep(),this._overflowSupport.addElement(d),
d=AdfDomUtils.getFirstChildElement(d),AdfToolbarUtils.isValidOverflowElement(d)&&(d=this._createOverflowElement(d),this._overflowSupport.addOverflowElement(d)),b++,d=a[b];this._overflowSupport.handleResize()}this._reStretch();this._activeDescendant&&(0<this._activeDescendant.offsetWidth||0<this._activeDescendant.offsetHeight)||this.resetActiveDescendant()}};AdfDhtmlToolbarPeer.prototype.ChildVisibilityChanged=function(a,b,d){AdfPage.PAGE.addPartialTargets(this.getComponent());return!1};
AdfDhtmlToolbarPeer.prototype.GetPreferredWidth=function(){if(this._preferredWidth)AdfLogger.LOGGER.fine("toolbar#GetPreferredWidth called, returned cached value of: "+this._preferredWidth);else{var a=this.getDomElement().firstChild;this._unStretch();this._overflowSupport&&this._overflowSupport.removeAllItemsFromOverflow();this._preferredWidth=a.offsetWidth;this._reStretch();AdfLogger.LOGGER.fine("toolbar#GetPreferredWidth called, returned calculated value of: "+this._preferredWidth)}return this._preferredWidth};
AdfDhtmlToolbarPeer.prototype.GetMinimumWidth=function(){if(!this._minimumWidth)if(0==this._isOverflowSupported)this._minimumWidth=this.GetPreferredWidth();else if(this._childContainers&&0<this._childContainers.length){var a=this._overflowIndicator.style.display,b=this._overflowIndicator;b.style.display="block";var d=AdfAgent.AGENT.getComputedStyle(b);this._minimumWidth=b.offsetWidth+AdfAgent.getCSSLengthAsInt(d.marginLeft)+AdfAgent.getCSSLengthAsInt(d.marginRight);b.style.display=a;a=this.GetPreferredWidth();
this._minimumWidth>a&&(this._minimumWidth=a)}else this._minimumWidth=0;return this._minimumWidth};
AdfDhtmlToolbarPeer.prototype.ComponentRemoved=function(a){this._overflowSupport&&(this._overflowSupport.removeOverflowSupport(),delete this._overflowSupport);delete this._overflowContainer;delete this._overflowIndicator;delete this._childContainers;delete this._isOverflowSupported;delete this._preferredWidth;delete this._minimumWidth;AdfPage.PAGE.__unregisterDescendantResizeNotifyComponent(a);AdfDhtmlToolbarPeer.superclass.ComponentRemoved.call(this,a)};
AdfDhtmlToolbarPeer.prototype.HandleComponentKeyDown=function(a){if(!a.isCanceled()){var b=AdfAgent.AGENT,d=a.getKeyCode();b.getPreferredKeyEventForRepetition()==AdfUIInputEvent.KEY_DOWN_EVENT_TYPE&&this._handleArrowKeys(d,a)}};AdfDhtmlToolbarPeer.prototype.HandleComponentKeyPress=function(a){if(!a.isCanceled()&&AdfAgent.AGENT.getPreferredKeyEventForRepetition()==AdfUIInputEvent.KEY_PRESS_EVENT_TYPE){var b=a.getKeyCode();this._handleArrowKeys(b,a)}};
AdfDhtmlToolbarPeer.prototype.HandleComponentFocus=function(a){if(this._isSingleTabstop){var b=a.getSource(),d=a.getNativeEvent(),d=AdfAgent.AGENT.getEventTarget(d),e=b.getClientId(),e=AdfAgent.AGENT.getElementById(e);e==this.getDomElement()&&(e=d);d==this._overflowIndicator?this._activeDescendant!=d&&this._updateActiveDescendant(d):AdfToolbarUtils.isInOverflow(e)?(b=AdfFocusUtils.getFirstFocusableDescendant(e))&&this._overflowSupport.updateActiveDescendant(b):AdfToolbarUtils.isOnToolbar(b)&&(b=AdfFocusUtils.getFirstFocusableDescendant(e))&&
b!=this._activeDescendant&&this._updateActiveDescendant(b);a.cancel()}};AdfDhtmlToolbarPeer.prototype.SimulateMouseOnDescendant=function(a,b,d){AdfDhtmlToolbarPeer.superclass.SimulateMouseOnDescendant.call(this,a,b,d);this._isOverflowSupported&&this._overflowSupport.isInOverflow(b)&&this._overflowSupport.showOverflowPopup()};
AdfDhtmlToolbarPeer.prototype.__preferredSizeChangeNotify=function(a){this.bind(a);this._minimumWidth=this._preferredWidth=null;a=this.getComponentParent(a);var b=null!=a?a.getPeer():null;b&&b.__preferredSizeChangeNotify&&b.__preferredSizeChangeNotify(a)};AdfDhtmlToolbarPeer.prototype._unStretch=function(){var a=this._getStretchElement();a&&(a.parentNode.style.width="")};
AdfDhtmlToolbarPeer.prototype._reStretch=function(){var a=this._getStretchElement();if(a)if(AdfToolbarUtils.isInOverflow(a))a.parentNode.style.width="100%";else{var b=AdfAgent.AGENT.getWindowWidth()+"px";a.parentNode.style.width=b}};
AdfDhtmlToolbarPeer.prototype._createOverflowElement=function(a){var b=this._getStretchElement(),b=a==b?"auto":"100%",d=a.ownerDocument.createElement("table");d.cellPadding=0;d.cellSpacing=0;d.style.width="100%";d.role="presentation";var e=d.insertRow(-1),f=e.insertCell(-1);f.setAttribute(AdfToolbarUtils.OVERFLOW_KEY,"true");f.setAttribute("role","presentation");AdfDomUtils.addCSSClassName(f,AdfToolbarUtils.OVERFLOW_CELL_STYLE_CLASS);a=this._overflowSupport.createSwapPosition(a);f.appendChild(a);
e.insertCell(-1).style.width=b;return d};AdfDhtmlToolbarPeer.prototype._getStretchElement=function(){var a=this.getComponent(),b=a.getStretchId();if(b){if(a=a.findComponent(b))return b=a.getClientId(),AdfAgent.AGENT.getElementById(b);AdfLogger.LOGGER.warning("Unable to find client component for stretch id "+b)}return null};
AdfDhtmlToolbarPeer.prototype._handleArrowKeys=function(a,b){var d=b.getNativeEvent();if(!(d.ctrlKey||d.altKey||d.shiftKey||d.metaKey)){var d=AdfAgent.AGENT.getEventTarget(d),e=b.getSource().getClientId(),e=AdfAgent.AGENT.getElementById(e);e==this.getDomElement()&&(e=d);if(AdfToolbarUtils.isInOverflow(e))if(this._isSingleTabstop)switch(a){case AdfKeyStroke.ARROWUP_KEY:case AdfKeyStroke.ARROWLEFT_KEY:this._overflowSupport.focusPreviousChild(this._overflowContainer);b.cancel();break;case AdfKeyStroke.ARROWDOWN_KEY:case AdfKeyStroke.ARROWRIGHT_KEY:this._overflowSupport.focusNextChild(this._overflowContainer),
b.cancel()}else switch(a){case AdfKeyStroke.ARROWUP_KEY:case AdfKeyStroke.ARROWLEFT_KEY:AdfFocusUtils.focusPreviousTabStop(d,this._overflowContainer);b.cancel();break;case AdfKeyStroke.ARROWDOWN_KEY:case AdfKeyStroke.ARROWRIGHT_KEY:AdfFocusUtils.focusNextTabStop(d,this._overflowContainer),b.cancel()}else switch(a){case AdfKeyStroke.ARROWLEFT_KEY:this._moveHighlightToPreviousItem(b);b.cancel();break;case AdfKeyStroke.ARROWRIGHT_KEY:this._moveHighlightToNextItem(b),b.cancel()}}};
AdfDhtmlToolbarPeer.prototype._moveHighlightToPreviousItem=function(a){this._isSingleTabstop&&this._canMoveFocus()?(a=this.getDomElement(),(a=AdfFocusUtils.focusPreviousActiveDescendant(a,this._activeDescendant))?this._activeDescendant=a:AdfDhtmlToolbarPeer._moveFocus(this._activeDescendant,!0)):(a=a.getNativeEvent(),a=AdfAgent.AGENT.getEventTarget(a),AdfDhtmlToolbarPeer._moveFocus(a,!0))};
AdfDhtmlToolbarPeer.prototype._moveHighlightToNextItem=function(a){this._isSingleTabstop&&this._canMoveFocus()?(a=this.getDomElement(),(a=AdfFocusUtils.focusNextActiveDescendant(a,this._activeDescendant))?this._activeDescendant=a:AdfDhtmlToolbarPeer._moveFocus(this._activeDescendant)):(a=a.getNativeEvent(),a=AdfAgent.AGENT.getEventTarget(a),AdfDhtmlToolbarPeer._moveFocus(a))};
AdfDhtmlToolbarPeer._moveFocus=function(a,b){var d=b?AdfFocusUtils.getPreviousTabStop(a):AdfFocusUtils.getNextTabStop(a);d&&AdfFocusUtils.focusElement(d)};
AdfDhtmlToolbarPeer.prototype._canMoveFocus=function(){AdfAssert.assertDomElement(this._activeDescendant);AdfAssert.assert("0"==this._activeDescendant.getAttribute("tabindex"),"The toolbar's active descendant should have tabindex 0");this._activeDescendant||(AdfLogger.LOGGER.warning("Toolbar has lost its assigned activeDescendant!"),this.resetActiveDescendant());return null!=this._activeDescendant};
AdfDhtmlToolbarPeer.prototype._updateActiveDescendant=function(a){AdfAssert.assertDomElement(a);this._activeDescendant&&this._activeDescendant.setAttribute("tabIndex","-1");a.setAttribute("tabIndex","0");this._activeDescendant=a};
function AdfToolbarUtils(){}AdfObject.createSubclass(AdfToolbarUtils);AdfToolbarUtils.InitClass=function(){this.OVERFLOW_KEY="_afrOflw";this.OVERFLOW_CELL_STYLE_CLASS="AFToolbarOverflowCell"};AdfToolbarUtils.isValidOverflowElement=function(a){if(null==a)return!1;a=AdfPage.PAGE.findComponent(a.id);return void 0!=window.AdfRichSpacer&&a instanceof AdfRichSpacer||void 0!=window.AdfRichImage&&a instanceof AdfRichImage?!1:!0};AdfToolbarUtils.isInOverflow=function(a){return"true"==a.parentNode.getAttribute(AdfToolbarUtils.OVERFLOW_KEY)};
AdfToolbarUtils.isOnToolbar=function(a){return a instanceof AdfRichToolbar?!0:(a=a.getParent())&&a instanceof AdfRichToolbar};