AdfUIComponents.createComponentClass("AdfRichToolbox",{componentType:"oracle.adf.RichToolbox",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0}],superclass:AdfUIPanel});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlToolboxPeer",!1);AdfDhtmlToolboxPeer.InitSubclass=function(){AdfObject.ensureClassInitialization(AdfToolbarUtils)};AdfDhtmlToolboxPeer.prototype.InitDomElement=function(a,b){AdfDhtmlToolboxPeer.superclass.InitDomElement.call(this,a,b);AdfPage.PAGE.__registerDescendantResizeNotifyComponent(a)};
AdfDhtmlToolboxPeer.prototype.ComponentRemoved=function(a){delete this._rows;AdfPage.PAGE.__unregisterDescendantResizeNotifyComponent(a);AdfDhtmlToolboxPeer.superclass.ComponentRemoved.call(this,a)};AdfDhtmlToolboxPeer.prototype.needsResizeNotify=function(a){return!0};
AdfDhtmlToolboxPeer.prototype.ResizeNotify=function(a,b,d,e){this._areRowsValid()||(AdfLogger.LOGGER.fine("toolbox#ResizeNotify, toolbox row size stale or not yet defined, recalculate row sizes"),this._initRows());a=AdfAgent.AGENT;b=this.getDomElement();d-=a.getOuterWidth(b,0);b=AdfDomUtils.getFirstChildElement(b);d-=a.getOuterWidth(b,0);for(a=0;a<this._rows.length;a++){b=this._rows[a];e=d-b.childPeers.length;var f=e-b.totalWidth;0>f?(AdfLogger.LOGGER.fine("toolbox#ResizeNotify, resizing toolbar row "+
a+", available width "+e+", is smaller than row width "+b.totalWidth+", attempt to overflow. "),this._overflowChildren(b,e,-f)):(AdfLogger.LOGGER.fine("toolbox#ResizeNotify, resizing toolbar row "+a+", available width "+e+", is not smaller than row width "+b.totalWidth+", attempt to stretch."),this._stretchChildren(b,e,f))}};AdfDhtmlToolboxPeer.prototype.__preferredSizeChangeNotify=function(a){this.bind(a);this._rows=null};
AdfDhtmlToolboxPeer.prototype._overflowChildren=function(a,b,d){for(b=a.childPeers.length-1;0<=b;--b){var e=a.childPeers[b];if(null==e){AdfLogger.LOGGER.severe("Unexpected null peer for toolbox child at index: ",b);break}var f=e.getDomElement();if(null==f){AdfLogger.LOGGER.warning("Unexpected child ["+b+"] found in toolbox component.");break}f.style.width="";var g=this._getPadding(f);if(e.GetPreferredWidth){var h=e.GetPreferredWidth()+g,k;k=e.GetMinimumWidth()+g;k=Math.max(h-d,k);g=k-g;f.parentNode.style.width=
k+1+"px";f.style.width=g+"px"}d-=h-k;0>=d?spaceToRemoved=0:f.parentNode.style.width=f.offsetWidth+1+"px"}};
AdfDhtmlToolboxPeer.prototype._stretchChildren=function(a,b,d){d=a.childPeers.length;for(var e=d-1,f=0;f<d;f++){var g=a.childPeers[f];if(null==g){AdfLogger.LOGGER.severe("Unexpected null peer for toolbox child at index: ",f);break}var h=g.getDomElement();if(null==h){AdfLogger.LOGGER.warning("Unexpected child ["+f+"] found in toolbox component.");break}h.style.width="";var k=this._getPadding(h);if(g.GetPreferredWidth){var l=g.GetPreferredWidth(),k=l+k,g=g.getComponent(),g=g.getFlex?g.getFlex()||0:
0;0<g?h.parentNode.style.width=g/a.totalFlex*b+"px":f==e&&0==a.totalFlex?h.parentNode.style.width=b+"px":(h.parentNode.style.width=k+1+"px",h.style.width=l+"px")}else h.parentNode.style.width=f==e&&0==a.totalFlex?b+"px":h.offsetWidth+1+"px"}};AdfDhtmlToolboxPeer.prototype._initRows=function(){this._rows=[];for(var a=this.getDomElement().firstChild.childNodes,b=a.length,d=0;d<b;d++)this._rows[d]=this._getRowInfo(a[d])};
AdfDhtmlToolboxPeer.prototype._getRowInfo=function(a){var b=AdfAgent.AGENT,d=[],e=0,f=0,g=0;a=a.getElementsByTagName("tr")[0].childNodes;for(var h=a.length,k=0;k<h;k++){var l=a[k],m=AdfDomUtils.getFirstChildElement(l);if(m&&m.id){var n=m.id;l.style.width="";if(l=AdfPage.PAGE.findComponent(n))n=l.getPeer(),d.push(n),n.GetPreferredWidth?(m=n.GetPreferredWidth()+this._getPadding(m),e+=m,m=null!=l.getFlex&&null!=l.getFlex()?l.getFlex():0,g+=m):(m=b.getOuterWidth(m,m.offsetWidth),e+=m,f+=m)}}return{childPeers:d,
totalWidth:e,fixedWidth:f,totalFlex:g}};AdfDhtmlToolboxPeer.prototype._getPadding=function(a){a=AdfAgent.AGENT.getComputedStyle(a);var b=AdfAgent.getCSSLengthAsInt;return b(a.paddingLeft)+b(a.paddingRight)+b(a.marginLeft)+b(a.marginRight)};
AdfDhtmlToolboxPeer.prototype._areRowsValid=function(){if(!this._rows)return!1;for(var a=0;a<this._rows.length;a++)for(var b=this._rows[a],d=0;d<b.childPeers.length;d++){var e=b.childPeers[d];if(null==e)return AdfLogger.LOGGER.fine("Toolbox cached rows are not valid, due to unexpected null peer for toolbox child at row: "+a+", index: "+d),!1;if(null==e.getDomElement())return AdfLogger.LOGGER.fine("Toolbox cached rows are not valid, due to toolbar peer without component (perhaps due to ppr) at row: "+
a+", index: "+d),!1}return!0};
function AdfToolbarUtils(){}AdfObject.createSubclass(AdfToolbarUtils);AdfToolbarUtils.InitClass=function(){this.OVERFLOW_KEY="_afrOflw";this.OVERFLOW_CELL_STYLE_CLASS="AFToolbarOverflowCell"};AdfToolbarUtils.isValidOverflowElement=function(a){if(null==a)return!1;a=AdfPage.PAGE.findComponent(a.id);return void 0!=window.AdfRichSpacer&&a instanceof AdfRichSpacer||void 0!=window.AdfRichImage&&a instanceof AdfRichImage?!1:!0};AdfToolbarUtils.isInOverflow=function(a){return"true"==a.parentNode.getAttribute(AdfToolbarUtils.OVERFLOW_KEY)};
AdfToolbarUtils.isOnToolbar=function(a){return a instanceof AdfRichToolbar?!0:(a=a.getParent())&&a instanceof AdfRichToolbar};